name: workflow_api
description: workflow api proto
# version: 1.0.0
# homepage: https://www.example.com
# author: ericwindmill <eric@ericwindmill.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  twirp_dart_core: any
