// Code generated by protoc-gen-twirp v5.5.0, DO NOT EDIT.
// source: api.proto

package core

import bytes "bytes"
import strings "strings"
import context "context"
import fmt "fmt"
import ioutil "io/ioutil"
import http "net/http"

import jsonpb "github.com/golang/protobuf/jsonpb"
import proto "github.com/golang/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// =====================
// WorkflowAPI Interface
// =====================

type WorkflowAPI interface {
	RunWorkflow(context.Context, *RunWorkflowRequest) (*BasicResponse, error)

	Ping(context.Context, *EmptyMessage) (*BasicResponse, error)

	PublishWorkflow(context.Context, *PublishWorkflowRequest) (*BasicResponse, error)

	ListWorkflows(context.Context, *ProjectRequest) (*ListWorkflowResponse, error)

	CreateProject(context.Context, *ProjectRequest) (*BasicResponse, error)

	AddUserToProject(context.Context, *AddUserRequest) (*BasicResponse, error)

	ListRemoteEngines(context.Context, *ProjectRequest) (*ListRemoteEnginesResponse, error)

	RegisterRemoteEngine(context.Context, *RegisterRemoteEngineRequest) (*BasicResponse, error)

	GetRemoteEngine(context.Context, *RemoteEngineRequest) (*RemoteEngine, error)

	RemoteEngineHealthCheck(context.Context, *RemoteEngineHealthRequest) (*RemoteEngineHealthResponse, error)

	GetStepPackage(context.Context, *StepPackageRequest) (*StepPackageResponse, error)

	ViewQueue(context.Context, *ViewQueueRequest) (*QueueResponse, error)

	GetAllSteps(context.Context, *AllStepsRequest) (*AllStepsResponse, error)

	SearchSteps(context.Context, *AllStepsRequest) (*AllStepsResponse, error)
}

// ===========================
// WorkflowAPI Protobuf Client
// ===========================

type workflowAPIProtobufClient struct {
	client HTTPClient
	urls   [14]string
}

// NewWorkflowAPIProtobufClient creates a Protobuf client that implements the WorkflowAPI interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewWorkflowAPIProtobufClient(addr string, client HTTPClient) WorkflowAPI {
	prefix := urlBase(addr) + WorkflowAPIPathPrefix
	urls := [14]string{
		prefix + "RunWorkflow",
		prefix + "Ping",
		prefix + "PublishWorkflow",
		prefix + "ListWorkflows",
		prefix + "CreateProject",
		prefix + "AddUserToProject",
		prefix + "ListRemoteEngines",
		prefix + "RegisterRemoteEngine",
		prefix + "GetRemoteEngine",
		prefix + "RemoteEngineHealthCheck",
		prefix + "GetStepPackage",
		prefix + "ViewQueue",
		prefix + "GetAllSteps",
		prefix + "SearchSteps",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &workflowAPIProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &workflowAPIProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *workflowAPIProtobufClient) RunWorkflow(ctx context.Context, in *RunWorkflowRequest) (*BasicResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "RunWorkflow")
	out := new(BasicResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIProtobufClient) Ping(ctx context.Context, in *EmptyMessage) (*BasicResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "Ping")
	out := new(BasicResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[1], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIProtobufClient) PublishWorkflow(ctx context.Context, in *PublishWorkflowRequest) (*BasicResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "PublishWorkflow")
	out := new(BasicResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[2], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIProtobufClient) ListWorkflows(ctx context.Context, in *ProjectRequest) (*ListWorkflowResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "ListWorkflows")
	out := new(ListWorkflowResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[3], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIProtobufClient) CreateProject(ctx context.Context, in *ProjectRequest) (*BasicResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "CreateProject")
	out := new(BasicResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[4], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIProtobufClient) AddUserToProject(ctx context.Context, in *AddUserRequest) (*BasicResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "AddUserToProject")
	out := new(BasicResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[5], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIProtobufClient) ListRemoteEngines(ctx context.Context, in *ProjectRequest) (*ListRemoteEnginesResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "ListRemoteEngines")
	out := new(ListRemoteEnginesResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[6], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIProtobufClient) RegisterRemoteEngine(ctx context.Context, in *RegisterRemoteEngineRequest) (*BasicResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "RegisterRemoteEngine")
	out := new(BasicResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[7], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIProtobufClient) GetRemoteEngine(ctx context.Context, in *RemoteEngineRequest) (*RemoteEngine, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "GetRemoteEngine")
	out := new(RemoteEngine)
	err := doProtobufRequest(ctx, c.client, c.urls[8], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIProtobufClient) RemoteEngineHealthCheck(ctx context.Context, in *RemoteEngineHealthRequest) (*RemoteEngineHealthResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "RemoteEngineHealthCheck")
	out := new(RemoteEngineHealthResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[9], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIProtobufClient) GetStepPackage(ctx context.Context, in *StepPackageRequest) (*StepPackageResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "GetStepPackage")
	out := new(StepPackageResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[10], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIProtobufClient) ViewQueue(ctx context.Context, in *ViewQueueRequest) (*QueueResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "ViewQueue")
	out := new(QueueResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[11], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIProtobufClient) GetAllSteps(ctx context.Context, in *AllStepsRequest) (*AllStepsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "GetAllSteps")
	out := new(AllStepsResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[12], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIProtobufClient) SearchSteps(ctx context.Context, in *AllStepsRequest) (*AllStepsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "SearchSteps")
	out := new(AllStepsResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[13], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// =======================
// WorkflowAPI JSON Client
// =======================

type workflowAPIJSONClient struct {
	client HTTPClient
	urls   [14]string
}

// NewWorkflowAPIJSONClient creates a JSON client that implements the WorkflowAPI interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewWorkflowAPIJSONClient(addr string, client HTTPClient) WorkflowAPI {
	prefix := urlBase(addr) + WorkflowAPIPathPrefix
	urls := [14]string{
		prefix + "RunWorkflow",
		prefix + "Ping",
		prefix + "PublishWorkflow",
		prefix + "ListWorkflows",
		prefix + "CreateProject",
		prefix + "AddUserToProject",
		prefix + "ListRemoteEngines",
		prefix + "RegisterRemoteEngine",
		prefix + "GetRemoteEngine",
		prefix + "RemoteEngineHealthCheck",
		prefix + "GetStepPackage",
		prefix + "ViewQueue",
		prefix + "GetAllSteps",
		prefix + "SearchSteps",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &workflowAPIJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &workflowAPIJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *workflowAPIJSONClient) RunWorkflow(ctx context.Context, in *RunWorkflowRequest) (*BasicResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "RunWorkflow")
	out := new(BasicResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIJSONClient) Ping(ctx context.Context, in *EmptyMessage) (*BasicResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "Ping")
	out := new(BasicResponse)
	err := doJSONRequest(ctx, c.client, c.urls[1], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIJSONClient) PublishWorkflow(ctx context.Context, in *PublishWorkflowRequest) (*BasicResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "PublishWorkflow")
	out := new(BasicResponse)
	err := doJSONRequest(ctx, c.client, c.urls[2], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIJSONClient) ListWorkflows(ctx context.Context, in *ProjectRequest) (*ListWorkflowResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "ListWorkflows")
	out := new(ListWorkflowResponse)
	err := doJSONRequest(ctx, c.client, c.urls[3], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIJSONClient) CreateProject(ctx context.Context, in *ProjectRequest) (*BasicResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "CreateProject")
	out := new(BasicResponse)
	err := doJSONRequest(ctx, c.client, c.urls[4], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIJSONClient) AddUserToProject(ctx context.Context, in *AddUserRequest) (*BasicResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "AddUserToProject")
	out := new(BasicResponse)
	err := doJSONRequest(ctx, c.client, c.urls[5], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIJSONClient) ListRemoteEngines(ctx context.Context, in *ProjectRequest) (*ListRemoteEnginesResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "ListRemoteEngines")
	out := new(ListRemoteEnginesResponse)
	err := doJSONRequest(ctx, c.client, c.urls[6], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIJSONClient) RegisterRemoteEngine(ctx context.Context, in *RegisterRemoteEngineRequest) (*BasicResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "RegisterRemoteEngine")
	out := new(BasicResponse)
	err := doJSONRequest(ctx, c.client, c.urls[7], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIJSONClient) GetRemoteEngine(ctx context.Context, in *RemoteEngineRequest) (*RemoteEngine, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "GetRemoteEngine")
	out := new(RemoteEngine)
	err := doJSONRequest(ctx, c.client, c.urls[8], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIJSONClient) RemoteEngineHealthCheck(ctx context.Context, in *RemoteEngineHealthRequest) (*RemoteEngineHealthResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "RemoteEngineHealthCheck")
	out := new(RemoteEngineHealthResponse)
	err := doJSONRequest(ctx, c.client, c.urls[9], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIJSONClient) GetStepPackage(ctx context.Context, in *StepPackageRequest) (*StepPackageResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "GetStepPackage")
	out := new(StepPackageResponse)
	err := doJSONRequest(ctx, c.client, c.urls[10], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIJSONClient) ViewQueue(ctx context.Context, in *ViewQueueRequest) (*QueueResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "ViewQueue")
	out := new(QueueResponse)
	err := doJSONRequest(ctx, c.client, c.urls[11], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIJSONClient) GetAllSteps(ctx context.Context, in *AllStepsRequest) (*AllStepsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "GetAllSteps")
	out := new(AllStepsResponse)
	err := doJSONRequest(ctx, c.client, c.urls[12], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAPIJSONClient) SearchSteps(ctx context.Context, in *AllStepsRequest) (*AllStepsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithMethodName(ctx, "SearchSteps")
	out := new(AllStepsResponse)
	err := doJSONRequest(ctx, c.client, c.urls[13], in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ==========================
// WorkflowAPI Server Handler
// ==========================

type workflowAPIServer struct {
	WorkflowAPI
	hooks *twirp.ServerHooks
}

func NewWorkflowAPIServer(svc WorkflowAPI, hooks *twirp.ServerHooks) TwirpServer {
	return &workflowAPIServer{
		WorkflowAPI: svc,
		hooks:       hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *workflowAPIServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// WorkflowAPIPathPrefix is used for all URL paths on a twirp WorkflowAPI server.
// Requests are always: POST WorkflowAPIPathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const WorkflowAPIPathPrefix = "/twirp/core.WorkflowAPI/"

func (s *workflowAPIServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "core")
	ctx = ctxsetters.WithServiceName(ctx, "WorkflowAPI")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/core.WorkflowAPI/RunWorkflow":
		s.serveRunWorkflow(ctx, resp, req)
		return
	case "/twirp/core.WorkflowAPI/Ping":
		s.servePing(ctx, resp, req)
		return
	case "/twirp/core.WorkflowAPI/PublishWorkflow":
		s.servePublishWorkflow(ctx, resp, req)
		return
	case "/twirp/core.WorkflowAPI/ListWorkflows":
		s.serveListWorkflows(ctx, resp, req)
		return
	case "/twirp/core.WorkflowAPI/CreateProject":
		s.serveCreateProject(ctx, resp, req)
		return
	case "/twirp/core.WorkflowAPI/AddUserToProject":
		s.serveAddUserToProject(ctx, resp, req)
		return
	case "/twirp/core.WorkflowAPI/ListRemoteEngines":
		s.serveListRemoteEngines(ctx, resp, req)
		return
	case "/twirp/core.WorkflowAPI/RegisterRemoteEngine":
		s.serveRegisterRemoteEngine(ctx, resp, req)
		return
	case "/twirp/core.WorkflowAPI/GetRemoteEngine":
		s.serveGetRemoteEngine(ctx, resp, req)
		return
	case "/twirp/core.WorkflowAPI/RemoteEngineHealthCheck":
		s.serveRemoteEngineHealthCheck(ctx, resp, req)
		return
	case "/twirp/core.WorkflowAPI/GetStepPackage":
		s.serveGetStepPackage(ctx, resp, req)
		return
	case "/twirp/core.WorkflowAPI/ViewQueue":
		s.serveViewQueue(ctx, resp, req)
		return
	case "/twirp/core.WorkflowAPI/GetAllSteps":
		s.serveGetAllSteps(ctx, resp, req)
		return
	case "/twirp/core.WorkflowAPI/SearchSteps":
		s.serveSearchSteps(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *workflowAPIServer) serveRunWorkflow(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveRunWorkflowJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveRunWorkflowProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *workflowAPIServer) serveRunWorkflowJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RunWorkflow")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(RunWorkflowRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *BasicResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.RunWorkflow(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *BasicResponse and nil error while calling RunWorkflow. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveRunWorkflowProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RunWorkflow")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(RunWorkflowRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *BasicResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.RunWorkflow(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *BasicResponse and nil error while calling RunWorkflow. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) servePing(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.servePingJSON(ctx, resp, req)
	case "application/protobuf":
		s.servePingProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *workflowAPIServer) servePingJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Ping")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(EmptyMessage)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *BasicResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.Ping(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *BasicResponse and nil error while calling Ping. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) servePingProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Ping")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(EmptyMessage)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *BasicResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.Ping(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *BasicResponse and nil error while calling Ping. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) servePublishWorkflow(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.servePublishWorkflowJSON(ctx, resp, req)
	case "application/protobuf":
		s.servePublishWorkflowProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *workflowAPIServer) servePublishWorkflowJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PublishWorkflow")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(PublishWorkflowRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *BasicResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.PublishWorkflow(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *BasicResponse and nil error while calling PublishWorkflow. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) servePublishWorkflowProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PublishWorkflow")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(PublishWorkflowRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *BasicResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.PublishWorkflow(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *BasicResponse and nil error while calling PublishWorkflow. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveListWorkflows(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListWorkflowsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListWorkflowsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *workflowAPIServer) serveListWorkflowsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListWorkflows")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(ProjectRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ListWorkflowResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.ListWorkflows(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListWorkflowResponse and nil error while calling ListWorkflows. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveListWorkflowsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListWorkflows")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(ProjectRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ListWorkflowResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.ListWorkflows(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListWorkflowResponse and nil error while calling ListWorkflows. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveCreateProject(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCreateProjectJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCreateProjectProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *workflowAPIServer) serveCreateProjectJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateProject")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(ProjectRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *BasicResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.CreateProject(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *BasicResponse and nil error while calling CreateProject. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveCreateProjectProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateProject")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(ProjectRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *BasicResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.CreateProject(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *BasicResponse and nil error while calling CreateProject. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveAddUserToProject(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveAddUserToProjectJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveAddUserToProjectProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *workflowAPIServer) serveAddUserToProjectJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "AddUserToProject")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(AddUserRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *BasicResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.AddUserToProject(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *BasicResponse and nil error while calling AddUserToProject. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveAddUserToProjectProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "AddUserToProject")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(AddUserRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *BasicResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.AddUserToProject(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *BasicResponse and nil error while calling AddUserToProject. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveListRemoteEngines(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListRemoteEnginesJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListRemoteEnginesProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *workflowAPIServer) serveListRemoteEnginesJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListRemoteEngines")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(ProjectRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ListRemoteEnginesResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.ListRemoteEngines(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListRemoteEnginesResponse and nil error while calling ListRemoteEngines. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveListRemoteEnginesProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListRemoteEngines")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(ProjectRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ListRemoteEnginesResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.ListRemoteEngines(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListRemoteEnginesResponse and nil error while calling ListRemoteEngines. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveRegisterRemoteEngine(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveRegisterRemoteEngineJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveRegisterRemoteEngineProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *workflowAPIServer) serveRegisterRemoteEngineJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RegisterRemoteEngine")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(RegisterRemoteEngineRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *BasicResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.RegisterRemoteEngine(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *BasicResponse and nil error while calling RegisterRemoteEngine. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveRegisterRemoteEngineProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RegisterRemoteEngine")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(RegisterRemoteEngineRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *BasicResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.RegisterRemoteEngine(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *BasicResponse and nil error while calling RegisterRemoteEngine. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveGetRemoteEngine(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetRemoteEngineJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetRemoteEngineProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *workflowAPIServer) serveGetRemoteEngineJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetRemoteEngine")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(RemoteEngineRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *RemoteEngine
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.GetRemoteEngine(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *RemoteEngine and nil error while calling GetRemoteEngine. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveGetRemoteEngineProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetRemoteEngine")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(RemoteEngineRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *RemoteEngine
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.GetRemoteEngine(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *RemoteEngine and nil error while calling GetRemoteEngine. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveRemoteEngineHealthCheck(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveRemoteEngineHealthCheckJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveRemoteEngineHealthCheckProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *workflowAPIServer) serveRemoteEngineHealthCheckJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RemoteEngineHealthCheck")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(RemoteEngineHealthRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *RemoteEngineHealthResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.RemoteEngineHealthCheck(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *RemoteEngineHealthResponse and nil error while calling RemoteEngineHealthCheck. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveRemoteEngineHealthCheckProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RemoteEngineHealthCheck")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(RemoteEngineHealthRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *RemoteEngineHealthResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.RemoteEngineHealthCheck(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *RemoteEngineHealthResponse and nil error while calling RemoteEngineHealthCheck. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveGetStepPackage(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetStepPackageJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetStepPackageProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *workflowAPIServer) serveGetStepPackageJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetStepPackage")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(StepPackageRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *StepPackageResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.GetStepPackage(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *StepPackageResponse and nil error while calling GetStepPackage. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveGetStepPackageProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetStepPackage")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(StepPackageRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *StepPackageResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.GetStepPackage(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *StepPackageResponse and nil error while calling GetStepPackage. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveViewQueue(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveViewQueueJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveViewQueueProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *workflowAPIServer) serveViewQueueJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ViewQueue")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(ViewQueueRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *QueueResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.ViewQueue(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *QueueResponse and nil error while calling ViewQueue. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveViewQueueProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ViewQueue")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(ViewQueueRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *QueueResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.ViewQueue(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *QueueResponse and nil error while calling ViewQueue. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveGetAllSteps(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetAllStepsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetAllStepsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *workflowAPIServer) serveGetAllStepsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetAllSteps")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(AllStepsRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *AllStepsResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.GetAllSteps(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AllStepsResponse and nil error while calling GetAllSteps. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveGetAllStepsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetAllSteps")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(AllStepsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *AllStepsResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.GetAllSteps(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AllStepsResponse and nil error while calling GetAllSteps. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveSearchSteps(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveSearchStepsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveSearchStepsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *workflowAPIServer) serveSearchStepsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SearchSteps")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(AllStepsRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *AllStepsResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.SearchSteps(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AllStepsResponse and nil error while calling SearchSteps. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) serveSearchStepsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SearchSteps")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(AllStepsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *AllStepsResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.WorkflowAPI.SearchSteps(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AllStepsResponse and nil error while calling SearchSteps. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *workflowAPIServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *workflowAPIServer) ProtocGenTwirpVersion() string {
	return "v5.5.0"
}

var twirpFileDescriptor1 = []byte{
	// 951 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x56, 0x7e, 0xda, 0x26, 0x27, 0xe9, 0x0f, 0xb3, 0xa5, 0xa4, 0x66, 0x45, 0x83, 0x25, 0xa4,
	0x0a, 0x41, 0x22, 0x96, 0xbd, 0x58, 0xad, 0x76, 0x05, 0x6d, 0xa8, 0x4a, 0xca, 0xc2, 0x06, 0xef,
	0x02, 0x12, 0xe2, 0xc6, 0xb5, 0xcf, 0x3a, 0xde, 0xc4, 0x1e, 0x33, 0x33, 0x6e, 0x88, 0xc4, 0x23,
	0x70, 0xcf, 0x05, 0x4f, 0xc2, 0xdb, 0xa1, 0xf1, 0xcc, 0x38, 0x76, 0xea, 0x6c, 0x81, 0xbd, 0x9b,
	0x73, 0xe6, 0x9c, 0x6f, 0xbe, 0xf3, 0x37, 0x33, 0xd0, 0x76, 0x93, 0x70, 0x90, 0x30, 0x2a, 0x28,
	0x69, 0x7a, 0x94, 0xa1, 0xd5, 0xf5, 0x68, 0x14, 0xd1, 0x58, 0xe9, 0xec, 0x31, 0x1c, 0x3b, 0x18,
	0x51, 0x81, 0x17, 0x71, 0x10, 0xc6, 0xf8, 0x35, 0xba, 0x73, 0x31, 0x75, 0xf0, 0xd7, 0x14, 0xb9,
	0x20, 0x04, 0x9a, 0xb1, 0x1b, 0x61, 0xaf, 0xd6, 0xaf, 0x9d, 0xb6, 0x9d, 0x6c, 0x4d, 0x7a, 0xb0,
	0x93, 0x30, 0xfa, 0x1a, 0x3d, 0xd1, 0xab, 0x67, 0x6a, 0x23, 0xda, 0x0f, 0xc1, 0xaa, 0x82, 0xe2,
	0x09, 0x8d, 0x39, 0x92, 0x23, 0xd8, 0xe6, 0xc2, 0x15, 0x29, 0xd7, 0x68, 0x5a, 0x92, 0x04, 0x9e,
	0x85, 0x5c, 0x14, 0x3d, 0x79, 0xee, 0xf4, 0x09, 0xec, 0xa0, 0x52, 0xf5, 0x6a, 0xfd, 0xc6, 0x69,
	0xe7, 0x01, 0x19, 0xc8, 0x18, 0x06, 0x45, 0x6b, 0xc7, 0x98, 0xd8, 0xd7, 0xd0, 0x2d, 0x6e, 0x54,
	0xd2, 0x27, 0xd0, 0x9c, 0x52, 0x6e, 0xb8, 0x67, 0x6b, 0x49, 0xcd, 0x4d, 0xc2, 0x6f, 0x70, 0xd9,
	0x6b, 0x28, 0x6a, 0x4a, 0x92, 0xb6, 0x1e, 0x32, 0xd1, 0x6b, 0xf6, 0x6b, 0xa7, 0x5d, 0x27, 0x5b,
	0xdb, 0x97, 0x70, 0xaf, 0x74, 0xb8, 0xce, 0x54, 0x21, 0x2b, 0xb5, 0x52, 0x56, 0x24, 0xb8, 0xe2,
	0xa7, 0x8f, 0xd4, 0x92, 0xfd, 0x67, 0x0d, 0xde, 0x77, 0x30, 0x08, 0xb9, 0x40, 0x56, 0x85, 0xf8,
	0x6f, 0xc9, 0x7f, 0x00, 0xe0, 0xcd, 0x43, 0x8c, 0xc5, 0x48, 0x52, 0x6d, 0x64, 0x54, 0x0b, 0x9a,
	0x42, 0x70, 0xcd, 0x52, 0x70, 0x05, 0xc6, 0x5b, 0xe5, 0x3a, 0x7e, 0x0c, 0x7b, 0x13, 0xb5, 0xbc,
	0x33, 0x3a, 0xfb, 0x19, 0x1c, 0xca, 0xea, 0xfd, 0x44, 0xd9, 0xec, 0xd5, 0x9c, 0x2e, 0xf2, 0xc2,
	0x3d, 0x84, 0xf6, 0x42, 0xeb, 0x4c, 0xe9, 0x8e, 0x54, 0xe9, 0x8c, 0xe9, 0xf3, 0x1b, 0x64, 0x37,
	0x21, 0x2e, 0x9c, 0x95, 0xa1, 0xfd, 0x3b, 0x1c, 0xac, 0x6f, 0x93, 0x3d, 0xa8, 0x87, 0xbe, 0x3e,
	0xb6, 0x1e, 0xfa, 0x9b, 0xfb, 0x8f, 0xd8, 0xd0, 0xf5, 0x31, 0xc1, 0xd8, 0xc7, 0xd8, 0x0b, 0x91,
	0xeb, 0x62, 0x96, 0x74, 0xc4, 0x82, 0x96, 0x60, 0x61, 0x10, 0x20, 0xe3, 0x3a, 0x1f, 0xb9, 0x6c,
	0x8f, 0x60, 0xf7, 0xdc, 0xe5, 0xa1, 0x97, 0x07, 0xd1, 0x83, 0x1d, 0x9e, 0x7a, 0x1e, 0x72, 0xd5,
	0xb3, 0x2d, 0xc7, 0x88, 0x72, 0x27, 0x42, 0xce, 0xdd, 0xc0, 0x54, 0xd5, 0x88, 0xb6, 0x03, 0xc4,
	0x49, 0xe3, 0x55, 0x3e, 0x54, 0x02, 0xef, 0x43, 0x5b, 0xb3, 0x1c, 0x9b, 0x58, 0x56, 0x0a, 0x59,
	0x42, 0x93, 0x83, 0xb1, 0xaf, 0x01, 0x0b, 0x1a, 0xfb, 0x0a, 0x8e, 0x26, 0xe9, 0xf5, 0x3c, 0xe4,
	0xd3, 0xff, 0x86, 0x4b, 0xa0, 0xe9, 0xbb, 0xc2, 0xcd, 0x10, 0xbb, 0x4e, 0xb6, 0xb6, 0xaf, 0x60,
	0xef, 0xcc, 0xf7, 0x7f, 0xe0, 0xb2, 0xe9, 0x14, 0x86, 0x05, 0xad, 0x94, 0x23, 0x2b, 0x34, 0x5b,
	0x2e, 0x97, 0xf1, 0xeb, 0x6b, 0xf8, 0xf6, 0x5f, 0x75, 0x68, 0x7f, 0x9f, 0x62, 0x8a, 0x63, 0x81,
	0xd1, 0x1b, 0x46, 0xc0, 0x82, 0x96, 0x89, 0x46, 0x83, 0xe4, 0x32, 0xf9, 0x02, 0x80, 0xa5, 0xf1,
	0x88, 0xc6, 0x02, 0x7f, 0x93, 0xed, 0x2b, 0x3b, 0xe5, 0x44, 0x75, 0x4a, 0x0e, 0x3d, 0x70, 0x72,
	0x8b, 0x8b, 0x58, 0xb0, 0xa5, 0x53, 0x70, 0x91, 0xc7, 0xb2, 0x34, 0x8e, 0xc3, 0x38, 0xc8, 0x0a,
	0xda, 0x72, 0x8c, 0x28, 0xc9, 0x7b, 0x0c, 0x5d, 0x81, 0xfe, 0xf3, 0x58, 0xf7, 0xf8, 0x4a, 0x41,
	0xfa, 0xd0, 0xd1, 0x95, 0x47, 0xff, 0x7c, 0xd9, 0xdb, 0xce, 0xf6, 0x8b, 0x2a, 0xeb, 0x29, 0xec,
	0xaf, 0x1d, 0x4c, 0x0e, 0xa0, 0x31, 0xc3, 0xa5, 0x8e, 0x4f, 0x2e, 0xc9, 0x21, 0x6c, 0xdd, 0xb8,
	0xf3, 0xd4, 0xf4, 0x81, 0x12, 0x1e, 0xd7, 0x1f, 0xd5, 0xec, 0x3f, 0x6a, 0xb0, 0x9b, 0x85, 0xf0,
	0x36, 0xfd, 0x24, 0x69, 0x32, 0xf4, 0x28, 0xf3, 0x47, 0x34, 0x8d, 0xd5, 0x7c, 0x37, 0x9c, 0xa2,
	0x8a, 0x7c, 0x04, 0x5b, 0xa1, 0xc0, 0x48, 0xf6, 0xb3, 0x4c, 0xde, 0xfe, 0x5a, 0xf2, 0x1c, 0xb5,
	0x6b, 0xbf, 0x86, 0x83, 0x1f, 0x43, 0x5c, 0x68, 0x46, 0x77, 0xdd, 0x5a, 0x6f, 0x2a, 0xd9, 0x2a,
	0x73, 0x2f, 0x97, 0x09, 0xea, 0x31, 0x2b, 0xaa, 0x1e, 0xfc, 0xbd, 0x03, 0x1d, 0xd3, 0xaa, 0x67,
	0x93, 0x31, 0x79, 0x02, 0x9d, 0xc2, 0x50, 0x90, 0x9e, 0xbe, 0xc4, 0x6f, 0xcd, 0x89, 0x75, 0x4f,
	0xed, 0x94, 0xc7, 0x70, 0x08, 0xcd, 0x89, 0xac, 0xa7, 0xbe, 0xfb, 0x2f, 0xa2, 0x44, 0x2c, 0xbf,
	0x55, 0xe9, 0xa9, 0x76, 0xf8, 0x0a, 0xf6, 0xd7, 0xe6, 0x85, 0xdc, 0x57, 0x76, 0xd5, 0x63, 0x54,
	0x8d, 0x72, 0x06, 0xbb, 0xc5, 0xab, 0x8d, 0x93, 0x43, 0x8d, 0x51, 0xba, 0x1b, 0x2d, 0x4b, 0x69,
	0x2b, 0x6f, 0xc1, 0xc7, 0xb0, 0x3b, 0xca, 0x1a, 0x4e, 0xfb, 0x6c, 0x80, 0xa8, 0x3c, 0xfe, 0x29,
	0x1c, 0xe8, 0x41, 0x7d, 0x49, 0xd7, 0xdc, 0xcb, 0x03, 0x5c, 0xed, 0x7e, 0x05, 0xef, 0xdc, 0x7a,
	0x56, 0x37, 0x1c, 0x7f, 0xb2, 0x8a, 0xa0, 0xfa, 0x15, 0xfe, 0x0e, 0x0e, 0xab, 0x5e, 0x2a, 0xf2,
	0xa1, 0x79, 0x8c, 0x37, 0xbe, 0x62, 0xd5, 0xdc, 0xbe, 0x84, 0xfd, 0x4b, 0x2c, 0x9d, 0x45, 0x8e,
	0x2b, 0xde, 0x75, 0x0d, 0x51, 0xf1, 0xe4, 0x93, 0x5f, 0xe0, 0xbd, 0xdb, 0x5f, 0x8d, 0xd1, 0x14,
	0xbd, 0x19, 0x39, 0xb9, 0x6d, 0x5e, 0xfa, 0xd4, 0x58, 0xfd, 0xcd, 0x06, 0x9a, 0xdf, 0x05, 0xec,
	0x5d, 0xa2, 0x78, 0x21, 0x30, 0x99, 0xb8, 0xde, 0x4c, 0x4e, 0xa1, 0xee, 0xd8, 0x82, 0xca, 0xa0,
	0x1d, 0x57, 0xec, 0x68, 0x98, 0x47, 0xd0, 0xce, 0x27, 0x8e, 0xe8, 0xd7, 0x6f, 0x7d, 0x04, 0x4d,
	0x82, 0xca, 0x17, 0xc5, 0x13, 0xe8, 0x5c, 0xa2, 0x38, 0x9b, 0xcf, 0x25, 0x2c, 0x27, 0xef, 0xea,
	0xb2, 0x6b, 0xd9, 0xb8, 0x1e, 0xad, 0xab, 0x57, 0xde, 0x2f, 0xd0, 0x65, 0xde, 0xf4, 0xff, 0x78,
	0x9f, 0x7f, 0xf6, 0xf3, 0x30, 0x08, 0xc5, 0x34, 0xbd, 0x1e, 0x78, 0x34, 0x1a, 0xba, 0x49, 0x22,
	0x18, 0x22, 0xa7, 0xaf, 0xc4, 0xc2, 0x65, 0x38, 0x0c, 0xe8, 0xa7, 0xe6, 0x1e, 0x18, 0x26, 0xb3,
	0x60, 0x28, 0x31, 0xae, 0xb7, 0xb3, 0xaf, 0xe4, 0xe7, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xfa,
	0x97, 0x99, 0x28, 0x6b, 0x0a, 0x00, 0x00,
}
