// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package core // import "github.com/apptreesoftware/go-workflow/pkg/core"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RemoteEngineHealthRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RemoteEngineHealthRequest) Reset()         { *m = RemoteEngineHealthRequest{} }
func (m *RemoteEngineHealthRequest) String() string { return proto.CompactTextString(m) }
func (*RemoteEngineHealthRequest) ProtoMessage()    {}
func (*RemoteEngineHealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{0}
}
func (m *RemoteEngineHealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteEngineHealthRequest.Unmarshal(m, b)
}
func (m *RemoteEngineHealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteEngineHealthRequest.Marshal(b, m, deterministic)
}
func (dst *RemoteEngineHealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteEngineHealthRequest.Merge(dst, src)
}
func (m *RemoteEngineHealthRequest) XXX_Size() int {
	return xxx_messageInfo_RemoteEngineHealthRequest.Size(m)
}
func (m *RemoteEngineHealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteEngineHealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteEngineHealthRequest proto.InternalMessageInfo

func (m *RemoteEngineHealthRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoteEngineHealthRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type RemoteEngineHealthResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RemoteEngineHealthResponse) Reset()         { *m = RemoteEngineHealthResponse{} }
func (m *RemoteEngineHealthResponse) String() string { return proto.CompactTextString(m) }
func (*RemoteEngineHealthResponse) ProtoMessage()    {}
func (*RemoteEngineHealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{1}
}
func (m *RemoteEngineHealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteEngineHealthResponse.Unmarshal(m, b)
}
func (m *RemoteEngineHealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteEngineHealthResponse.Marshal(b, m, deterministic)
}
func (dst *RemoteEngineHealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteEngineHealthResponse.Merge(dst, src)
}
func (m *RemoteEngineHealthResponse) XXX_Size() int {
	return xxx_messageInfo_RemoteEngineHealthResponse.Size(m)
}
func (m *RemoteEngineHealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteEngineHealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteEngineHealthResponse proto.InternalMessageInfo

func (m *RemoteEngineHealthResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ListRemoteEnginesResponse struct {
	Engines              []*RemoteEngine `protobuf:"bytes,1,rep,name=engines,proto3" json:"engines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte          `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32           `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ListRemoteEnginesResponse) Reset()         { *m = ListRemoteEnginesResponse{} }
func (m *ListRemoteEnginesResponse) String() string { return proto.CompactTextString(m) }
func (*ListRemoteEnginesResponse) ProtoMessage()    {}
func (*ListRemoteEnginesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{2}
}
func (m *ListRemoteEnginesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRemoteEnginesResponse.Unmarshal(m, b)
}
func (m *ListRemoteEnginesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRemoteEnginesResponse.Marshal(b, m, deterministic)
}
func (dst *ListRemoteEnginesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRemoteEnginesResponse.Merge(dst, src)
}
func (m *ListRemoteEnginesResponse) XXX_Size() int {
	return xxx_messageInfo_ListRemoteEnginesResponse.Size(m)
}
func (m *ListRemoteEnginesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRemoteEnginesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRemoteEnginesResponse proto.InternalMessageInfo

func (m *ListRemoteEnginesResponse) GetEngines() []*RemoteEngine {
	if m != nil {
		return m.Engines
	}
	return nil
}

type RemoteEngine struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Cert                 []byte   `protobuf:"bytes,4,opt,name=cert,proto3" json:"cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RemoteEngine) Reset()         { *m = RemoteEngine{} }
func (m *RemoteEngine) String() string { return proto.CompactTextString(m) }
func (*RemoteEngine) ProtoMessage()    {}
func (*RemoteEngine) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{3}
}
func (m *RemoteEngine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteEngine.Unmarshal(m, b)
}
func (m *RemoteEngine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteEngine.Marshal(b, m, deterministic)
}
func (dst *RemoteEngine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteEngine.Merge(dst, src)
}
func (m *RemoteEngine) XXX_Size() int {
	return xxx_messageInfo_RemoteEngine.Size(m)
}
func (m *RemoteEngine) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteEngine.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteEngine proto.InternalMessageInfo

func (m *RemoteEngine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoteEngine) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *RemoteEngine) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *RemoteEngine) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

type RemoteEngineRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Engine               string   `protobuf:"bytes,2,opt,name=engine,proto3" json:"engine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RemoteEngineRequest) Reset()         { *m = RemoteEngineRequest{} }
func (m *RemoteEngineRequest) String() string { return proto.CompactTextString(m) }
func (*RemoteEngineRequest) ProtoMessage()    {}
func (*RemoteEngineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{4}
}
func (m *RemoteEngineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteEngineRequest.Unmarshal(m, b)
}
func (m *RemoteEngineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteEngineRequest.Marshal(b, m, deterministic)
}
func (dst *RemoteEngineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteEngineRequest.Merge(dst, src)
}
func (m *RemoteEngineRequest) XXX_Size() int {
	return xxx_messageInfo_RemoteEngineRequest.Size(m)
}
func (m *RemoteEngineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteEngineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteEngineRequest proto.InternalMessageInfo

func (m *RemoteEngineRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *RemoteEngineRequest) GetEngine() string {
	if m != nil {
		return m.Engine
	}
	return ""
}

type RegisterRemoteEngineRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	ClientCert           []byte   `protobuf:"bytes,3,opt,name=clientCert,proto3" json:"clientCert,omitempty"`
	ApiKey               string   `protobuf:"bytes,4,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Project              string   `protobuf:"bytes,5,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RegisterRemoteEngineRequest) Reset()         { *m = RegisterRemoteEngineRequest{} }
func (m *RegisterRemoteEngineRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRemoteEngineRequest) ProtoMessage()    {}
func (*RegisterRemoteEngineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{5}
}
func (m *RegisterRemoteEngineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRemoteEngineRequest.Unmarshal(m, b)
}
func (m *RegisterRemoteEngineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRemoteEngineRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRemoteEngineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRemoteEngineRequest.Merge(dst, src)
}
func (m *RegisterRemoteEngineRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRemoteEngineRequest.Size(m)
}
func (m *RegisterRemoteEngineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRemoteEngineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRemoteEngineRequest proto.InternalMessageInfo

func (m *RegisterRemoteEngineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRemoteEngineRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *RegisterRemoteEngineRequest) GetClientCert() []byte {
	if m != nil {
		return m.ClientCert
	}
	return nil
}

func (m *RegisterRemoteEngineRequest) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *RegisterRemoteEngineRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type ProjectRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ProjectRequest) Reset()         { *m = ProjectRequest{} }
func (m *ProjectRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectRequest) ProtoMessage()    {}
func (*ProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{6}
}
func (m *ProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectRequest.Unmarshal(m, b)
}
func (m *ProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectRequest.Marshal(b, m, deterministic)
}
func (dst *ProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectRequest.Merge(dst, src)
}
func (m *ProjectRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectRequest.Size(m)
}
func (m *ProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectRequest proto.InternalMessageInfo

func (m *ProjectRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type ListWorkflowResponse struct {
	Workflows            []*WorkflowOverview `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte              `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32               `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ListWorkflowResponse) Reset()         { *m = ListWorkflowResponse{} }
func (m *ListWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*ListWorkflowResponse) ProtoMessage()    {}
func (*ListWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{7}
}
func (m *ListWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWorkflowResponse.Unmarshal(m, b)
}
func (m *ListWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *ListWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWorkflowResponse.Merge(dst, src)
}
func (m *ListWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_ListWorkflowResponse.Size(m)
}
func (m *ListWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListWorkflowResponse proto.InternalMessageInfo

func (m *ListWorkflowResponse) GetWorkflows() []*WorkflowOverview {
	if m != nil {
		return m.Workflows
	}
	return nil
}

type WorkflowOverview struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Dependencies         string   `protobuf:"bytes,3,opt,name=dependencies,proto3" json:"dependencies,omitempty"`
	Triggers             string   `protobuf:"bytes,4,opt,name=triggers,proto3" json:"triggers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *WorkflowOverview) Reset()         { *m = WorkflowOverview{} }
func (m *WorkflowOverview) String() string { return proto.CompactTextString(m) }
func (*WorkflowOverview) ProtoMessage()    {}
func (*WorkflowOverview) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{8}
}
func (m *WorkflowOverview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowOverview.Unmarshal(m, b)
}
func (m *WorkflowOverview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowOverview.Marshal(b, m, deterministic)
}
func (dst *WorkflowOverview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowOverview.Merge(dst, src)
}
func (m *WorkflowOverview) XXX_Size() int {
	return xxx_messageInfo_WorkflowOverview.Size(m)
}
func (m *WorkflowOverview) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowOverview.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowOverview proto.InternalMessageInfo

func (m *WorkflowOverview) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkflowOverview) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *WorkflowOverview) GetDependencies() string {
	if m != nil {
		return m.Dependencies
	}
	return ""
}

func (m *WorkflowOverview) GetTriggers() string {
	if m != nil {
		return m.Triggers
	}
	return ""
}

type BasicResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *BasicResponse) Reset()         { *m = BasicResponse{} }
func (m *BasicResponse) String() string { return proto.CompactTextString(m) }
func (*BasicResponse) ProtoMessage()    {}
func (*BasicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{9}
}
func (m *BasicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicResponse.Unmarshal(m, b)
}
func (m *BasicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicResponse.Marshal(b, m, deterministic)
}
func (dst *BasicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicResponse.Merge(dst, src)
}
func (m *BasicResponse) XXX_Size() int {
	return xxx_messageInfo_BasicResponse.Size(m)
}
func (m *BasicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BasicResponse proto.InternalMessageInfo

func (m *BasicResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *BasicResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RunWorkflowRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	WorkflowId           string   `protobuf:"bytes,2,opt,name=workflowId,proto3" json:"workflowId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RunWorkflowRequest) Reset()         { *m = RunWorkflowRequest{} }
func (m *RunWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*RunWorkflowRequest) ProtoMessage()    {}
func (*RunWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{10}
}
func (m *RunWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunWorkflowRequest.Unmarshal(m, b)
}
func (m *RunWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *RunWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunWorkflowRequest.Merge(dst, src)
}
func (m *RunWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_RunWorkflowRequest.Size(m)
}
func (m *RunWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunWorkflowRequest proto.InternalMessageInfo

func (m *RunWorkflowRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *RunWorkflowRequest) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

type PublishWorkflowRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *PublishWorkflowRequest) Reset()         { *m = PublishWorkflowRequest{} }
func (m *PublishWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*PublishWorkflowRequest) ProtoMessage()    {}
func (*PublishWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{11}
}
func (m *PublishWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishWorkflowRequest.Unmarshal(m, b)
}
func (m *PublishWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *PublishWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishWorkflowRequest.Merge(dst, src)
}
func (m *PublishWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_PublishWorkflowRequest.Size(m)
}
func (m *PublishWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishWorkflowRequest proto.InternalMessageInfo

func (m *PublishWorkflowRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *PublishWorkflowRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=projectId,proto3" json:"projectId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{12}
}
func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (dst *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(dst, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddUserRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type QueueItem struct {
	Project              string            `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workflow             string            `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	RunContext           map[string]string `protobuf:"bytes,3,rep,name=runContext,proto3" json:"runContext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Running              bool              `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	CreatedOn            string            `protobuf:"bytes,5,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	TriggeredBy          string            `protobuf:"bytes,6,opt,name=triggeredBy,proto3" json:"triggeredBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *QueueItem) Reset()         { *m = QueueItem{} }
func (m *QueueItem) String() string { return proto.CompactTextString(m) }
func (*QueueItem) ProtoMessage()    {}
func (*QueueItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{13}
}
func (m *QueueItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueItem.Unmarshal(m, b)
}
func (m *QueueItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueItem.Marshal(b, m, deterministic)
}
func (dst *QueueItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueItem.Merge(dst, src)
}
func (m *QueueItem) XXX_Size() int {
	return xxx_messageInfo_QueueItem.Size(m)
}
func (m *QueueItem) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueItem.DiscardUnknown(m)
}

var xxx_messageInfo_QueueItem proto.InternalMessageInfo

func (m *QueueItem) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *QueueItem) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func (m *QueueItem) GetRunContext() map[string]string {
	if m != nil {
		return m.RunContext
	}
	return nil
}

func (m *QueueItem) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

func (m *QueueItem) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *QueueItem) GetTriggeredBy() string {
	if m != nil {
		return m.TriggeredBy
	}
	return ""
}

type QueueResponse struct {
	Success              bool         `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RecordCount          int64        `protobuf:"varint,3,opt,name=recordCount,proto3" json:"recordCount,omitempty"`
	Items                []*QueueItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte       `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32        `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *QueueResponse) Reset()         { *m = QueueResponse{} }
func (m *QueueResponse) String() string { return proto.CompactTextString(m) }
func (*QueueResponse) ProtoMessage()    {}
func (*QueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{14}
}
func (m *QueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueResponse.Unmarshal(m, b)
}
func (m *QueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueResponse.Marshal(b, m, deterministic)
}
func (dst *QueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueResponse.Merge(dst, src)
}
func (m *QueueResponse) XXX_Size() int {
	return xxx_messageInfo_QueueResponse.Size(m)
}
func (m *QueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueueResponse proto.InternalMessageInfo

func (m *QueueResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *QueueResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueueResponse) GetRecordCount() int64 {
	if m != nil {
		return m.RecordCount
	}
	return 0
}

func (m *QueueResponse) GetItems() []*QueueItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type ViewQueueRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workflow             string   `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	TriggerType          string   `protobuf:"bytes,3,opt,name=triggerType,proto3" json:"triggerType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ViewQueueRequest) Reset()         { *m = ViewQueueRequest{} }
func (m *ViewQueueRequest) String() string { return proto.CompactTextString(m) }
func (*ViewQueueRequest) ProtoMessage()    {}
func (*ViewQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{15}
}
func (m *ViewQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewQueueRequest.Unmarshal(m, b)
}
func (m *ViewQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewQueueRequest.Marshal(b, m, deterministic)
}
func (dst *ViewQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewQueueRequest.Merge(dst, src)
}
func (m *ViewQueueRequest) XXX_Size() int {
	return xxx_messageInfo_ViewQueueRequest.Size(m)
}
func (m *ViewQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewQueueRequest proto.InternalMessageInfo

func (m *ViewQueueRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ViewQueueRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func (m *ViewQueueRequest) GetTriggerType() string {
	if m != nil {
		return m.TriggerType
	}
	return ""
}

type ViewLogRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	JobId                string   `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	LogLevel             string   `protobuf:"bytes,3,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ViewLogRequest) Reset()         { *m = ViewLogRequest{} }
func (m *ViewLogRequest) String() string { return proto.CompactTextString(m) }
func (*ViewLogRequest) ProtoMessage()    {}
func (*ViewLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{16}
}
func (m *ViewLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewLogRequest.Unmarshal(m, b)
}
func (m *ViewLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewLogRequest.Marshal(b, m, deterministic)
}
func (dst *ViewLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewLogRequest.Merge(dst, src)
}
func (m *ViewLogRequest) XXX_Size() int {
	return xxx_messageInfo_ViewLogRequest.Size(m)
}
func (m *ViewLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewLogRequest proto.InternalMessageInfo

func (m *ViewLogRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ViewLogRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ViewLogRequest) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

type Log struct {
	LogLevel             string   `protobuf:"bytes,1,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{17}
}
func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (dst *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(dst, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

func (m *Log) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Log) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type ViewLogResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ViewLogResponse) Reset()         { *m = ViewLogResponse{} }
func (m *ViewLogResponse) String() string { return proto.CompactTextString(m) }
func (*ViewLogResponse) ProtoMessage()    {}
func (*ViewLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{18}
}
func (m *ViewLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewLogResponse.Unmarshal(m, b)
}
func (m *ViewLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewLogResponse.Marshal(b, m, deterministic)
}
func (dst *ViewLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewLogResponse.Merge(dst, src)
}
func (m *ViewLogResponse) XXX_Size() int {
	return xxx_messageInfo_ViewLogResponse.Size(m)
}
func (m *ViewLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ViewLogResponse proto.InternalMessageInfo

func (m *ViewLogResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ViewLogResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ViewLogResponse) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type TriggerResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Project              string   `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	JobId                string   `protobuf:"bytes,4,opt,name=jobId,proto3" json:"jobId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *TriggerResponse) Reset()         { *m = TriggerResponse{} }
func (m *TriggerResponse) String() string { return proto.CompactTextString(m) }
func (*TriggerResponse) ProtoMessage()    {}
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_54f191401eed9e97, []int{19}
}
func (m *TriggerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerResponse.Unmarshal(m, b)
}
func (m *TriggerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerResponse.Marshal(b, m, deterministic)
}
func (dst *TriggerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerResponse.Merge(dst, src)
}
func (m *TriggerResponse) XXX_Size() int {
	return xxx_messageInfo_TriggerResponse.Size(m)
}
func (m *TriggerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerResponse proto.InternalMessageInfo

func (m *TriggerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TriggerResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TriggerResponse) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *TriggerResponse) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func init() {
	proto.RegisterType((*RemoteEngineHealthRequest)(nil), "core.RemoteEngineHealthRequest")
	proto.RegisterType((*RemoteEngineHealthResponse)(nil), "core.RemoteEngineHealthResponse")
	proto.RegisterType((*ListRemoteEnginesResponse)(nil), "core.ListRemoteEnginesResponse")
	proto.RegisterType((*RemoteEngine)(nil), "core.RemoteEngine")
	proto.RegisterType((*RemoteEngineRequest)(nil), "core.RemoteEngineRequest")
	proto.RegisterType((*RegisterRemoteEngineRequest)(nil), "core.RegisterRemoteEngineRequest")
	proto.RegisterType((*ProjectRequest)(nil), "core.ProjectRequest")
	proto.RegisterType((*ListWorkflowResponse)(nil), "core.ListWorkflowResponse")
	proto.RegisterType((*WorkflowOverview)(nil), "core.WorkflowOverview")
	proto.RegisterType((*BasicResponse)(nil), "core.BasicResponse")
	proto.RegisterType((*RunWorkflowRequest)(nil), "core.RunWorkflowRequest")
	proto.RegisterType((*PublishWorkflowRequest)(nil), "core.PublishWorkflowRequest")
	proto.RegisterType((*AddUserRequest)(nil), "core.AddUserRequest")
	proto.RegisterType((*QueueItem)(nil), "core.QueueItem")
	proto.RegisterMapType((map[string]string)(nil), "core.QueueItem.RunContextEntry")
	proto.RegisterType((*QueueResponse)(nil), "core.QueueResponse")
	proto.RegisterType((*ViewQueueRequest)(nil), "core.ViewQueueRequest")
	proto.RegisterType((*ViewLogRequest)(nil), "core.ViewLogRequest")
	proto.RegisterType((*Log)(nil), "core.Log")
	proto.RegisterType((*ViewLogResponse)(nil), "core.ViewLogResponse")
	proto.RegisterType((*TriggerResponse)(nil), "core.TriggerResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_54f191401eed9e97) }

var fileDescriptor_api_54f191401eed9e97 = []byte{
	// 1104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4b, 0x6f, 0xe4, 0x44,
	0x10, 0xd6, 0x3c, 0xf2, 0x98, 0xca, 0x63, 0x42, 0xef, 0x90, 0x9d, 0x98, 0x40, 0x82, 0x25, 0xa4,
	0x08, 0x41, 0x46, 0x2c, 0x7b, 0x58, 0x56, 0x2c, 0x90, 0x0c, 0x51, 0x48, 0x08, 0xec, 0xe0, 0xcd,
	0xb2, 0x02, 0xed, 0xc5, 0x63, 0xd7, 0x7a, 0x9c, 0xd8, 0x6e, 0xe3, 0x6e, 0x27, 0x8c, 0xc4, 0x4f,
	0xe0, 0xc6, 0x81, 0x03, 0x7f, 0x16, 0xb5, 0xbb, 0xdb, 0x63, 0x3b, 0x9e, 0x04, 0x08, 0x37, 0x57,
	0x75, 0xf5, 0x57, 0x5f, 0x3d, 0xba, 0xba, 0x0d, 0x1d, 0x3b, 0xf6, 0xf7, 0xe3, 0x84, 0x72, 0x4a,
	0xda, 0x0e, 0x4d, 0xd0, 0x58, 0x75, 0x68, 0x18, 0xd2, 0x48, 0xea, 0xcc, 0x13, 0xd8, 0xb2, 0x30,
	0xa4, 0x1c, 0x8f, 0x22, 0xcf, 0x8f, 0xf0, 0x1b, 0xb4, 0x03, 0x3e, 0xb1, 0xf0, 0x97, 0x14, 0x19,
	0x27, 0x04, 0xda, 0x91, 0x1d, 0x62, 0xbf, 0xb1, 0xdb, 0xd8, 0xeb, 0x58, 0xd9, 0x37, 0xe9, 0xc3,
	0x52, 0x9c, 0xd0, 0x0b, 0x74, 0x78, 0xbf, 0x99, 0xa9, 0xb5, 0x68, 0x3e, 0x06, 0xa3, 0x0e, 0x8a,
	0xc5, 0x34, 0x62, 0x48, 0x36, 0x61, 0x91, 0x71, 0x9b, 0xa7, 0x4c, 0xa1, 0x29, 0x49, 0x10, 0x38,
	0xf3, 0x19, 0x2f, 0xee, 0x64, 0xf9, 0xa6, 0x8f, 0x60, 0x09, 0xa5, 0xaa, 0xdf, 0xd8, 0x6d, 0xed,
	0xad, 0x3c, 0x22, 0xfb, 0x22, 0x86, 0xfd, 0xa2, 0xb5, 0xa5, 0x4d, 0xcc, 0x31, 0xac, 0x16, 0x17,
	0x6a, 0xe9, 0x13, 0x68, 0x4f, 0x28, 0xd3, 0xdc, 0xb3, 0x6f, 0x41, 0xcd, 0x8e, 0xfd, 0x6f, 0x71,
	0xda, 0x6f, 0x49, 0x6a, 0x52, 0x12, 0xb6, 0x0e, 0x26, 0xbc, 0xdf, 0xde, 0x6d, 0xec, 0xad, 0x5a,
	0xd9, 0xb7, 0x79, 0x0c, 0x0f, 0x4a, 0xce, 0x55, 0xa6, 0x0a, 0x59, 0x69, 0x94, 0xb2, 0x22, 0xc0,
	0x25, 0x3f, 0xe5, 0x52, 0x49, 0xe6, 0x9f, 0x0d, 0x78, 0xc7, 0x42, 0xcf, 0x67, 0x1c, 0x93, 0x3a,
	0xc4, 0x7f, 0x4a, 0xfe, 0x3d, 0x00, 0x27, 0xf0, 0x31, 0xe2, 0x43, 0x41, 0xb5, 0x95, 0x51, 0x2d,
	0x68, 0x0a, 0xc1, 0xb5, 0x4b, 0xc1, 0x15, 0x18, 0x2f, 0x94, 0xeb, 0xf8, 0x21, 0xac, 0x8f, 0xe4,
	0xe7, 0x9d, 0xd1, 0x99, 0x67, 0xd0, 0x13, 0xd5, 0x7b, 0x45, 0x93, 0xcb, 0x37, 0x01, 0xbd, 0xce,
	0x0b, 0xf7, 0x18, 0x3a, 0xd7, 0x4a, 0xa7, 0x4b, 0xb7, 0x29, 0x4b, 0xa7, 0x4d, 0x9f, 0x5f, 0x61,
	0x72, 0xe5, 0xe3, 0xb5, 0x35, 0x33, 0x34, 0x7f, 0x83, 0x8d, 0xea, 0x32, 0x59, 0x87, 0xa6, 0xef,
	0x2a, 0xb7, 0x4d, 0xdf, 0x9d, 0xdf, 0x7f, 0xc4, 0x84, 0x55, 0x17, 0x63, 0x8c, 0x5c, 0x8c, 0x1c,
	0x1f, 0x99, 0x2a, 0x66, 0x49, 0x47, 0x0c, 0x58, 0xe6, 0x89, 0xef, 0x79, 0x98, 0x30, 0x95, 0x8f,
	0x5c, 0x36, 0x87, 0xb0, 0x76, 0x68, 0x33, 0xdf, 0xc9, 0x83, 0xe8, 0xc3, 0x12, 0x4b, 0x1d, 0x07,
	0x99, 0xec, 0xd9, 0x65, 0x4b, 0x8b, 0x62, 0x25, 0x44, 0xc6, 0x6c, 0x4f, 0x57, 0x55, 0x8b, 0xa6,
	0x05, 0xc4, 0x4a, 0xa3, 0x59, 0x3e, 0x64, 0x02, 0xb7, 0xa1, 0xa3, 0x58, 0x9e, 0xe8, 0x58, 0x66,
	0x0a, 0x51, 0x42, 0x9d, 0x83, 0x13, 0x57, 0x01, 0x16, 0x34, 0xe6, 0x29, 0x6c, 0x8e, 0xd2, 0x71,
	0xe0, 0xb3, 0xc9, 0xbf, 0xc3, 0x25, 0xd0, 0x76, 0x6d, 0x6e, 0x67, 0x88, 0xab, 0x56, 0xf6, 0x6d,
	0x9e, 0xc2, 0xfa, 0x81, 0xeb, 0xbe, 0x64, 0xa2, 0xe9, 0x24, 0x86, 0x01, 0xcb, 0x29, 0xc3, 0xa4,
	0xd0, 0x6c, 0xb9, 0x5c, 0xc6, 0x6f, 0x56, 0xf0, 0xcd, 0xbf, 0x9a, 0xd0, 0xf9, 0x21, 0xc5, 0x14,
	0x4f, 0x38, 0x86, 0xb7, 0x1c, 0x01, 0x03, 0x96, 0x75, 0x34, 0x0a, 0x24, 0x97, 0xc9, 0x97, 0x00,
	0x49, 0x1a, 0x0d, 0x69, 0xc4, 0xf1, 0x57, 0xd1, 0xbe, 0xa2, 0x53, 0x76, 0x64, 0xa7, 0xe4, 0xd0,
	0xfb, 0x56, 0x6e, 0x71, 0x14, 0xf1, 0x64, 0x6a, 0x15, 0xb6, 0x08, 0xb7, 0x49, 0x1a, 0x45, 0x7e,
	0xe4, 0x65, 0x05, 0x5d, 0xb6, 0xb4, 0x28, 0xc8, 0x3b, 0x09, 0xda, 0x1c, 0xdd, 0xe7, 0x91, 0xea,
	0xf1, 0x99, 0x82, 0xec, 0xc2, 0x8a, 0xaa, 0x3c, 0xba, 0x87, 0xd3, 0xfe, 0x62, 0xb6, 0x5e, 0x54,
	0x19, 0xcf, 0xa0, 0x5b, 0x71, 0x4c, 0x36, 0xa0, 0x75, 0x89, 0x53, 0x15, 0x9f, 0xf8, 0x24, 0x3d,
	0x58, 0xb8, 0xb2, 0x83, 0x54, 0xf7, 0x81, 0x14, 0x9e, 0x36, 0x9f, 0x34, 0xcc, 0xdf, 0x1b, 0xb0,
	0x96, 0x85, 0x70, 0x9f, 0x7e, 0x12, 0x34, 0x13, 0x74, 0x68, 0xe2, 0x0e, 0x69, 0x1a, 0xc9, 0xf3,
	0xdd, 0xb2, 0x8a, 0x2a, 0xf2, 0x01, 0x2c, 0xf8, 0x1c, 0x43, 0xd1, 0xcf, 0x22, 0x79, 0xdd, 0x4a,
	0xf2, 0x2c, 0xb9, 0x6a, 0x5e, 0xc0, 0xc6, 0x8f, 0x3e, 0x5e, 0x2b, 0x46, 0x77, 0x4d, 0xad, 0xdb,
	0x4a, 0x36, 0xcb, 0xdc, 0xf9, 0x34, 0x46, 0x75, 0xcc, 0x8a, 0x2a, 0xf3, 0x35, 0xac, 0x0b, 0x5f,
	0x67, 0xd4, 0xbb, 0xdb, 0x53, 0x0f, 0x16, 0x2e, 0xe8, 0x38, 0x6f, 0x2f, 0x29, 0x08, 0xff, 0x01,
	0xf5, 0xce, 0xf0, 0x0a, 0x03, 0xe5, 0x20, 0x97, 0xcd, 0x9f, 0xa0, 0x75, 0x46, 0xbd, 0x92, 0x49,
	0xa3, 0x6c, 0x72, 0x4b, 0x3e, 0xb7, 0xa1, 0xc3, 0xfd, 0x10, 0x19, 0xb7, 0xc3, 0x58, 0x21, 0xcf,
	0x14, 0xa6, 0x0b, 0xdd, 0x9c, 0xf8, 0x3d, 0x8a, 0xf6, 0x2e, 0xb4, 0x03, 0xea, 0x31, 0xd5, 0xce,
	0x1d, 0x59, 0x11, 0x01, 0x9a, 0xa9, 0xcd, 0x14, 0xba, 0xe7, 0x32, 0x5b, 0xf7, 0xf2, 0x52, 0xc8,
	0x69, 0x6b, 0x4e, 0x4e, 0xdb, 0x85, 0x9c, 0x3e, 0xfa, 0xa3, 0x03, 0x2b, 0x7a, 0x80, 0x1c, 0x8c,
	0x4e, 0xc8, 0x17, 0xb0, 0x52, 0x18, 0x55, 0xa4, 0xaf, 0xae, 0xd6, 0x1b, 0xd3, 0xcb, 0x78, 0x5b,
	0xae, 0x54, 0x39, 0x0f, 0xa0, 0x3d, 0x12, 0xe7, 0x4c, 0xdd, 0xc9, 0x47, 0x61, 0xcc, 0xa7, 0xdf,
	0x49, 0x6e, 0xc6, 0x03, 0xa9, 0x2b, 0xcf, 0xd3, 0xaf, 0xa1, 0x5b, 0x99, 0x63, 0x64, 0x5b, 0xda,
	0xd5, 0x8f, 0xb7, 0x7a, 0x94, 0x03, 0x58, 0x2b, 0x5e, 0x39, 0x8c, 0xf4, 0x14, 0x46, 0xe9, 0xce,
	0x32, 0x0c, 0x95, 0xf5, 0xba, 0xdb, 0xe9, 0x29, 0xac, 0x0d, 0xb3, 0x41, 0x30, 0xd2, 0x09, 0xab,
	0x85, 0xa8, 0x75, 0xff, 0x0c, 0x36, 0xd4, 0x00, 0x3d, 0xa7, 0x95, 0xed, 0xe5, 0xc1, 0x5a, 0xbf,
	0xfd, 0x14, 0xde, 0xba, 0xf1, 0xdc, 0x99, 0xe3, 0x7e, 0x67, 0x16, 0x41, 0xfd, 0xeb, 0xe8, 0x7b,
	0xe8, 0xd5, 0xbd, 0x20, 0xc8, 0xfb, 0xfa, 0x91, 0x34, 0xf7, 0x75, 0x51, 0xcf, 0xed, 0x2b, 0xe8,
	0x1e, 0x63, 0xc9, 0x17, 0xd9, 0xaa, 0x79, 0x6f, 0x29, 0x88, 0x9a, 0xa7, 0x18, 0x79, 0x0d, 0x0f,
	0x6f, 0x3e, 0x01, 0x87, 0x13, 0x74, 0x2e, 0xc9, 0xce, 0x4d, 0xf3, 0xd2, 0x63, 0xd3, 0xd8, 0x9d,
	0x6f, 0xa0, 0xf8, 0xbd, 0x02, 0xf2, 0x32, 0x76, 0x6d, 0x8e, 0x25, 0x9f, 0xff, 0x03, 0xf0, 0x11,
	0xac, 0x1f, 0x23, 0x7f, 0xc1, 0x31, 0x1e, 0xd9, 0xce, 0x65, 0x76, 0xb6, 0xe4, 0x9e, 0x82, 0x4a,
	0xa3, 0x6d, 0xd5, 0xac, 0x28, 0x98, 0x27, 0xd0, 0xc9, 0x47, 0x2c, 0x51, 0xcf, 0x9d, 0xea, 0xcc,
	0xd5, 0x99, 0x2f, 0xdf, 0x0c, 0x9f, 0xc3, 0xca, 0x31, 0xf2, 0x83, 0x20, 0x10, 0xb0, 0x8c, 0xa8,
	0x03, 0xa7, 0x65, 0xbd, 0x75, 0xb3, 0xaa, 0x9e, 0xed, 0x7e, 0x81, 0x76, 0xe2, 0x4c, 0xfe, 0xd3,
	0xee, 0x43, 0x58, 0x13, 0xc1, 0xfb, 0x91, 0x17, 0xa0, 0x58, 0x21, 0x0f, 0x55, 0x84, 0xb9, 0x46,
	0x23, 0xf4, 0x6f, 0x2e, 0x28, 0x8c, 0xcf, 0x00, 0x44, 0xa0, 0xa7, 0x74, 0x2c, 0x26, 0x73, 0x6f,
	0x16, 0xfa, 0xec, 0x0a, 0xd0, 0x53, 0xa4, 0x32, 0x5f, 0x0f, 0x3f, 0xf9, 0x79, 0xe0, 0xf9, 0x7c,
	0x92, 0x8e, 0xf7, 0x1d, 0x1a, 0x0e, 0xec, 0x38, 0xe6, 0x09, 0x22, 0xa3, 0x6f, 0xf8, 0xb5, 0x9d,
	0xe0, 0xc0, 0xa3, 0x1f, 0xeb, 0x7b, 0x67, 0x10, 0x5f, 0x7a, 0x03, 0x01, 0x31, 0x5e, 0xcc, 0x7e,
	0x5d, 0x3e, 0xfd, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xe2, 0x84, 0x56, 0xdb, 0x0c, 0x00, 0x00,
}
