// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Package struct {
	Name                 string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lang                 string                  `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Version              string                  `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Executables          *Exec                   `protobuf:"bytes,4,opt,name=executables,proto3" json:"executables,omitempty"`
	Steps                map[string]*PackageStep `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte                  `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32                   `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *Package) Reset()         { *m = Package{} }
func (m *Package) String() string { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()    {}
func (*Package) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Package) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Package.Unmarshal(m, b)
}
func (m *Package) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Package.Marshal(b, m, deterministic)
}
func (m *Package) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Package.Merge(m, src)
}
func (m *Package) XXX_Size() int {
	return xxx_messageInfo_Package.Size(m)
}
func (m *Package) XXX_DiscardUnknown() {
	xxx_messageInfo_Package.DiscardUnknown(m)
}

var xxx_messageInfo_Package proto.InternalMessageInfo

func (m *Package) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Package) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *Package) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Package) GetExecutables() *Exec {
	if m != nil {
		return m.Executables
	}
	return nil
}

func (m *Package) GetSteps() map[string]*PackageStep {
	if m != nil {
		return m.Steps
	}
	return nil
}

type Exec struct {
	Darwin               *Binary  `protobuf:"bytes,1,opt,name=darwin,proto3" json:"darwin,omitempty"`
	Linux                *Binary  `protobuf:"bytes,2,opt,name=linux,proto3" json:"linux,omitempty"`
	Windows              *Binary  `protobuf:"bytes,3,opt,name=windows,proto3" json:"windows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *Exec) Reset()         { *m = Exec{} }
func (m *Exec) String() string { return proto.CompactTextString(m) }
func (*Exec) ProtoMessage()    {}
func (*Exec) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Exec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exec.Unmarshal(m, b)
}
func (m *Exec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exec.Marshal(b, m, deterministic)
}
func (m *Exec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exec.Merge(m, src)
}
func (m *Exec) XXX_Size() int {
	return xxx_messageInfo_Exec.Size(m)
}
func (m *Exec) XXX_DiscardUnknown() {
	xxx_messageInfo_Exec.DiscardUnknown(m)
}

var xxx_messageInfo_Exec proto.InternalMessageInfo

func (m *Exec) GetDarwin() *Binary {
	if m != nil {
		return m.Darwin
	}
	return nil
}

func (m *Exec) GetLinux() *Binary {
	if m != nil {
		return m.Linux
	}
	return nil
}

func (m *Exec) GetWindows() *Binary {
	if m != nil {
		return m.Windows
	}
	return nil
}

type Binary struct {
	Amd64                string   `protobuf:"bytes,1,opt,name=amd64,proto3" json:"amd64,omitempty"`
	I386                 string   `protobuf:"bytes,2,opt,name=i386,proto3" json:"i386,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *Binary) Reset()         { *m = Binary{} }
func (m *Binary) String() string { return proto.CompactTextString(m) }
func (*Binary) ProtoMessage()    {}
func (*Binary) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *Binary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Binary.Unmarshal(m, b)
}
func (m *Binary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Binary.Marshal(b, m, deterministic)
}
func (m *Binary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Binary.Merge(m, src)
}
func (m *Binary) XXX_Size() int {
	return xxx_messageInfo_Binary.Size(m)
}
func (m *Binary) XXX_DiscardUnknown() {
	xxx_messageInfo_Binary.DiscardUnknown(m)
}

var xxx_messageInfo_Binary proto.InternalMessageInfo

func (m *Binary) GetAmd64() string {
	if m != nil {
		return m.Amd64
	}
	return ""
}

func (m *Binary) GetI386() string {
	if m != nil {
		return m.I386
	}
	return ""
}

type PackageStep struct {
	Description          string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Inputs               map[string]*InputInfo  `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Outputs              map[string]*OutputInfo `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Sample               string                 `protobuf:"bytes,4,opt,name=sample,proto3" json:"sample,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte                 `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32                  `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *PackageStep) Reset()         { *m = PackageStep{} }
func (m *PackageStep) String() string { return proto.CompactTextString(m) }
func (*PackageStep) ProtoMessage()    {}
func (*PackageStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *PackageStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageStep.Unmarshal(m, b)
}
func (m *PackageStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageStep.Marshal(b, m, deterministic)
}
func (m *PackageStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageStep.Merge(m, src)
}
func (m *PackageStep) XXX_Size() int {
	return xxx_messageInfo_PackageStep.Size(m)
}
func (m *PackageStep) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageStep.DiscardUnknown(m)
}

var xxx_messageInfo_PackageStep proto.InternalMessageInfo

func (m *PackageStep) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PackageStep) GetInputs() map[string]*InputInfo {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *PackageStep) GetOutputs() map[string]*OutputInfo {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *PackageStep) GetSample() string {
	if m != nil {
		return m.Sample
	}
	return ""
}

type InputInfo struct {
	Required             bool     `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *InputInfo) Reset()         { *m = InputInfo{} }
func (m *InputInfo) String() string { return proto.CompactTextString(m) }
func (*InputInfo) ProtoMessage()    {}
func (*InputInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *InputInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputInfo.Unmarshal(m, b)
}
func (m *InputInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputInfo.Marshal(b, m, deterministic)
}
func (m *InputInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputInfo.Merge(m, src)
}
func (m *InputInfo) XXX_Size() int {
	return xxx_messageInfo_InputInfo.Size(m)
}
func (m *InputInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_InputInfo.DiscardUnknown(m)
}

var xxx_messageInfo_InputInfo proto.InternalMessageInfo

func (m *InputInfo) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *InputInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type OutputInfo struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *OutputInfo) Reset()         { *m = OutputInfo{} }
func (m *OutputInfo) String() string { return proto.CompactTextString(m) }
func (*OutputInfo) ProtoMessage()    {}
func (*OutputInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *OutputInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputInfo.Unmarshal(m, b)
}
func (m *OutputInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputInfo.Marshal(b, m, deterministic)
}
func (m *OutputInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputInfo.Merge(m, src)
}
func (m *OutputInfo) XXX_Size() int {
	return xxx_messageInfo_OutputInfo.Size(m)
}
func (m *OutputInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OutputInfo proto.InternalMessageInfo

func (m *OutputInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Environment struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workflow             string   `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	RunId                string   `protobuf:"bytes,3,opt,name=runId,proto3" json:"runId,omitempty"`
	StepName             string   `protobuf:"bytes,4,opt,name=stepName,proto3" json:"stepName,omitempty"`
	StepVersion          string   `protobuf:"bytes,5,opt,name=stepVersion,proto3" json:"stepVersion,omitempty"`
	InputFile            string   `protobuf:"bytes,6,opt,name=inputFile,proto3" json:"inputFile,omitempty"`
	TriggerType          string   `protobuf:"bytes,7,opt,name=triggerType,proto3" json:"triggerType,omitempty"`
	StepInstanceId       string   `protobuf:"bytes,8,opt,name=stepInstanceId,proto3" json:"stepInstanceId,omitempty"`
	Package              string   `protobuf:"bytes,9,opt,name=package,proto3" json:"package,omitempty"`
	CacheHost            string   `protobuf:"bytes,10,opt,name=cacheHost,proto3" json:"cacheHost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *Environment) Reset()         { *m = Environment{} }
func (m *Environment) String() string { return proto.CompactTextString(m) }
func (*Environment) ProtoMessage()    {}
func (*Environment) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

func (m *Environment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Environment.Unmarshal(m, b)
}
func (m *Environment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Environment.Marshal(b, m, deterministic)
}
func (m *Environment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environment.Merge(m, src)
}
func (m *Environment) XXX_Size() int {
	return xxx_messageInfo_Environment.Size(m)
}
func (m *Environment) XXX_DiscardUnknown() {
	xxx_messageInfo_Environment.DiscardUnknown(m)
}

var xxx_messageInfo_Environment proto.InternalMessageInfo

func (m *Environment) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Environment) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func (m *Environment) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}

func (m *Environment) GetStepName() string {
	if m != nil {
		return m.StepName
	}
	return ""
}

func (m *Environment) GetStepVersion() string {
	if m != nil {
		return m.StepVersion
	}
	return ""
}

func (m *Environment) GetInputFile() string {
	if m != nil {
		return m.InputFile
	}
	return ""
}

func (m *Environment) GetTriggerType() string {
	if m != nil {
		return m.TriggerType
	}
	return ""
}

func (m *Environment) GetStepInstanceId() string {
	if m != nil {
		return m.StepInstanceId
	}
	return ""
}

func (m *Environment) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *Environment) GetCacheHost() string {
	if m != nil {
		return m.CacheHost
	}
	return ""
}

type EmptyMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *EmptyMessage) Reset()         { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()    {}
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{7}
}

func (m *EmptyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMessage.Unmarshal(m, b)
}
func (m *EmptyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMessage.Marshal(b, m, deterministic)
}
func (m *EmptyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMessage.Merge(m, src)
}
func (m *EmptyMessage) XXX_Size() int {
	return xxx_messageInfo_EmptyMessage.Size(m)
}
func (m *EmptyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMessage proto.InternalMessageInfo

type StepPackageRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Os                   string   `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch                 string   `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *StepPackageRequest) Reset()         { *m = StepPackageRequest{} }
func (m *StepPackageRequest) String() string { return proto.CompactTextString(m) }
func (*StepPackageRequest) ProtoMessage()    {}
func (*StepPackageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{8}
}

func (m *StepPackageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepPackageRequest.Unmarshal(m, b)
}
func (m *StepPackageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepPackageRequest.Marshal(b, m, deterministic)
}
func (m *StepPackageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepPackageRequest.Merge(m, src)
}
func (m *StepPackageRequest) XXX_Size() int {
	return xxx_messageInfo_StepPackageRequest.Size(m)
}
func (m *StepPackageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StepPackageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StepPackageRequest proto.InternalMessageInfo

func (m *StepPackageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StepPackageRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *StepPackageRequest) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *StepPackageRequest) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

type StepPackageResponse struct {
	PackageUrl           string   `protobuf:"bytes,1,opt,name=packageUrl,proto3" json:"packageUrl,omitempty"`
	PublishId            string   `protobuf:"bytes,2,opt,name=publishId,proto3" json:"publishId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *StepPackageResponse) Reset()         { *m = StepPackageResponse{} }
func (m *StepPackageResponse) String() string { return proto.CompactTextString(m) }
func (*StepPackageResponse) ProtoMessage()    {}
func (*StepPackageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{9}
}

func (m *StepPackageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepPackageResponse.Unmarshal(m, b)
}
func (m *StepPackageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepPackageResponse.Marshal(b, m, deterministic)
}
func (m *StepPackageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepPackageResponse.Merge(m, src)
}
func (m *StepPackageResponse) XXX_Size() int {
	return xxx_messageInfo_StepPackageResponse.Size(m)
}
func (m *StepPackageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StepPackageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StepPackageResponse proto.InternalMessageInfo

func (m *StepPackageResponse) GetPackageUrl() string {
	if m != nil {
		return m.PackageUrl
	}
	return ""
}

func (m *StepPackageResponse) GetPublishId() string {
	if m != nil {
		return m.PublishId
	}
	return ""
}

type CachePushRequest struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata             []byte       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Record               []byte       `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	CacheName            string       `protobuf:"bytes,4,opt,name=cacheName,proto3" json:"cacheName,omitempty"`
	Environment          *Environment `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte       `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32        `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *CachePushRequest) Reset()         { *m = CachePushRequest{} }
func (m *CachePushRequest) String() string { return proto.CompactTextString(m) }
func (*CachePushRequest) ProtoMessage()    {}
func (*CachePushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{10}
}

func (m *CachePushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CachePushRequest.Unmarshal(m, b)
}
func (m *CachePushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CachePushRequest.Marshal(b, m, deterministic)
}
func (m *CachePushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CachePushRequest.Merge(m, src)
}
func (m *CachePushRequest) XXX_Size() int {
	return xxx_messageInfo_CachePushRequest.Size(m)
}
func (m *CachePushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CachePushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CachePushRequest proto.InternalMessageInfo

func (m *CachePushRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CachePushRequest) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CachePushRequest) GetRecord() []byte {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *CachePushRequest) GetCacheName() string {
	if m != nil {
		return m.CacheName
	}
	return ""
}

func (m *CachePushRequest) GetEnvironment() *Environment {
	if m != nil {
		return m.Environment
	}
	return nil
}

type CachePushResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *CachePushResponse) Reset()         { *m = CachePushResponse{} }
func (m *CachePushResponse) String() string { return proto.CompactTextString(m) }
func (*CachePushResponse) ProtoMessage()    {}
func (*CachePushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{11}
}

func (m *CachePushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CachePushResponse.Unmarshal(m, b)
}
func (m *CachePushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CachePushResponse.Marshal(b, m, deterministic)
}
func (m *CachePushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CachePushResponse.Merge(m, src)
}
func (m *CachePushResponse) XXX_Size() int {
	return xxx_messageInfo_CachePushResponse.Size(m)
}
func (m *CachePushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CachePushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CachePushResponse proto.InternalMessageInfo

type CachePullRequest struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CacheName            string       `protobuf:"bytes,2,opt,name=cacheName,proto3" json:"cacheName,omitempty"`
	Environment          *Environment `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte       `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32        `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *CachePullRequest) Reset()         { *m = CachePullRequest{} }
func (m *CachePullRequest) String() string { return proto.CompactTextString(m) }
func (*CachePullRequest) ProtoMessage()    {}
func (*CachePullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{12}
}

func (m *CachePullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CachePullRequest.Unmarshal(m, b)
}
func (m *CachePullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CachePullRequest.Marshal(b, m, deterministic)
}
func (m *CachePullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CachePullRequest.Merge(m, src)
}
func (m *CachePullRequest) XXX_Size() int {
	return xxx_messageInfo_CachePullRequest.Size(m)
}
func (m *CachePullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CachePullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CachePullRequest proto.InternalMessageInfo

func (m *CachePullRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CachePullRequest) GetCacheName() string {
	if m != nil {
		return m.CacheName
	}
	return ""
}

func (m *CachePullRequest) GetEnvironment() *Environment {
	if m != nil {
		return m.Environment
	}
	return nil
}

type CachePullResponse struct {
	Record               []byte   `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Metadata             []byte   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	NotFound             bool     `protobuf:"varint,3,opt,name=notFound,proto3" json:"notFound,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *CachePullResponse) Reset()         { *m = CachePullResponse{} }
func (m *CachePullResponse) String() string { return proto.CompactTextString(m) }
func (*CachePullResponse) ProtoMessage()    {}
func (*CachePullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{13}
}

func (m *CachePullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CachePullResponse.Unmarshal(m, b)
}
func (m *CachePullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CachePullResponse.Marshal(b, m, deterministic)
}
func (m *CachePullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CachePullResponse.Merge(m, src)
}
func (m *CachePullResponse) XXX_Size() int {
	return xxx_messageInfo_CachePullResponse.Size(m)
}
func (m *CachePullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CachePullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CachePullResponse proto.InternalMessageInfo

func (m *CachePullResponse) GetRecord() []byte {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *CachePullResponse) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CachePullResponse) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

type AllStepsRequest struct {
	SearchTerm           string   `protobuf:"bytes,1,opt,name=searchTerm,proto3" json:"searchTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *AllStepsRequest) Reset()         { *m = AllStepsRequest{} }
func (m *AllStepsRequest) String() string { return proto.CompactTextString(m) }
func (*AllStepsRequest) ProtoMessage()    {}
func (*AllStepsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{14}
}

func (m *AllStepsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllStepsRequest.Unmarshal(m, b)
}
func (m *AllStepsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllStepsRequest.Marshal(b, m, deterministic)
}
func (m *AllStepsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllStepsRequest.Merge(m, src)
}
func (m *AllStepsRequest) XXX_Size() int {
	return xxx_messageInfo_AllStepsRequest.Size(m)
}
func (m *AllStepsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllStepsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllStepsRequest proto.InternalMessageInfo

func (m *AllStepsRequest) GetSearchTerm() string {
	if m != nil {
		return m.SearchTerm
	}
	return ""
}

type AllStepsResponse struct {
	Success              bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RecordCount          int64             `protobuf:"varint,3,opt,name=recordCount,proto3" json:"recordCount,omitempty"`
	Items                []*RegisteredStep `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *AllStepsResponse) Reset()         { *m = AllStepsResponse{} }
func (m *AllStepsResponse) String() string { return proto.CompactTextString(m) }
func (*AllStepsResponse) ProtoMessage()    {}
func (*AllStepsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{15}
}

func (m *AllStepsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllStepsResponse.Unmarshal(m, b)
}
func (m *AllStepsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllStepsResponse.Marshal(b, m, deterministic)
}
func (m *AllStepsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllStepsResponse.Merge(m, src)
}
func (m *AllStepsResponse) XXX_Size() int {
	return xxx_messageInfo_AllStepsResponse.Size(m)
}
func (m *AllStepsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllStepsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllStepsResponse proto.InternalMessageInfo

func (m *AllStepsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AllStepsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AllStepsResponse) GetRecordCount() int64 {
	if m != nil {
		return m.RecordCount
	}
	return 0
}

func (m *AllStepsResponse) GetItems() []*RegisteredStep {
	if m != nil {
		return m.Items
	}
	return nil
}

type RegisteredStep struct {
	Step                 *PackageStep `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Location             string       `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	LocationType         string       `protobuf:"bytes,3,opt,name=locationType,proto3" json:"locationType,omitempty"`
	PublishId            string       `protobuf:"bytes,4,opt,name=publishId,proto3" json:"publishId,omitempty"`
	Author               string       `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	PackageName          string       `protobuf:"bytes,6,opt,name=packageName,proto3" json:"packageName,omitempty"`
	StepName             string       `protobuf:"bytes,7,opt,name=StepName,proto3" json:"StepName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte       `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32        `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RegisteredStep) Reset()         { *m = RegisteredStep{} }
func (m *RegisteredStep) String() string { return proto.CompactTextString(m) }
func (*RegisteredStep) ProtoMessage()    {}
func (*RegisteredStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{16}
}

func (m *RegisteredStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredStep.Unmarshal(m, b)
}
func (m *RegisteredStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredStep.Marshal(b, m, deterministic)
}
func (m *RegisteredStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredStep.Merge(m, src)
}
func (m *RegisteredStep) XXX_Size() int {
	return xxx_messageInfo_RegisteredStep.Size(m)
}
func (m *RegisteredStep) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredStep.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredStep proto.InternalMessageInfo

func (m *RegisteredStep) GetStep() *PackageStep {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *RegisteredStep) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *RegisteredStep) GetLocationType() string {
	if m != nil {
		return m.LocationType
	}
	return ""
}

func (m *RegisteredStep) GetPublishId() string {
	if m != nil {
		return m.PublishId
	}
	return ""
}

func (m *RegisteredStep) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *RegisteredStep) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *RegisteredStep) GetStepName() string {
	if m != nil {
		return m.StepName
	}
	return ""
}

type SingleStepRequest struct {
	PackageName          string   `protobuf:"bytes,1,opt,name=packageName,proto3" json:"packageName,omitempty"`
	StepName             string   `protobuf:"bytes,2,opt,name=stepName,proto3" json:"stepName,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *SingleStepRequest) Reset()         { *m = SingleStepRequest{} }
func (m *SingleStepRequest) String() string { return proto.CompactTextString(m) }
func (*SingleStepRequest) ProtoMessage()    {}
func (*SingleStepRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{17}
}

func (m *SingleStepRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleStepRequest.Unmarshal(m, b)
}
func (m *SingleStepRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleStepRequest.Marshal(b, m, deterministic)
}
func (m *SingleStepRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleStepRequest.Merge(m, src)
}
func (m *SingleStepRequest) XXX_Size() int {
	return xxx_messageInfo_SingleStepRequest.Size(m)
}
func (m *SingleStepRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleStepRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SingleStepRequest proto.InternalMessageInfo

func (m *SingleStepRequest) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *SingleStepRequest) GetStepName() string {
	if m != nil {
		return m.StepName
	}
	return ""
}

func (m *SingleStepRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type SingleStepResponse struct {
	Step                 *RegisteredStep `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte          `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32           `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *SingleStepResponse) Reset()         { *m = SingleStepResponse{} }
func (m *SingleStepResponse) String() string { return proto.CompactTextString(m) }
func (*SingleStepResponse) ProtoMessage()    {}
func (*SingleStepResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{18}
}

func (m *SingleStepResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleStepResponse.Unmarshal(m, b)
}
func (m *SingleStepResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleStepResponse.Marshal(b, m, deterministic)
}
func (m *SingleStepResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleStepResponse.Merge(m, src)
}
func (m *SingleStepResponse) XXX_Size() int {
	return xxx_messageInfo_SingleStepResponse.Size(m)
}
func (m *SingleStepResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleStepResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SingleStepResponse proto.InternalMessageInfo

func (m *SingleStepResponse) GetStep() *RegisteredStep {
	if m != nil {
		return m.Step
	}
	return nil
}

func init() {
	proto.RegisterType((*Package)(nil), "core.Package")
	proto.RegisterMapType((map[string]*PackageStep)(nil), "core.Package.StepsEntry")
	proto.RegisterType((*Exec)(nil), "core.Exec")
	proto.RegisterType((*Binary)(nil), "core.Binary")
	proto.RegisterType((*PackageStep)(nil), "core.PackageStep")
	proto.RegisterMapType((map[string]*InputInfo)(nil), "core.PackageStep.InputsEntry")
	proto.RegisterMapType((map[string]*OutputInfo)(nil), "core.PackageStep.OutputsEntry")
	proto.RegisterType((*InputInfo)(nil), "core.InputInfo")
	proto.RegisterType((*OutputInfo)(nil), "core.OutputInfo")
	proto.RegisterType((*Environment)(nil), "core.Environment")
	proto.RegisterType((*EmptyMessage)(nil), "core.EmptyMessage")
	proto.RegisterType((*StepPackageRequest)(nil), "core.StepPackageRequest")
	proto.RegisterType((*StepPackageResponse)(nil), "core.StepPackageResponse")
	proto.RegisterType((*CachePushRequest)(nil), "core.CachePushRequest")
	proto.RegisterType((*CachePushResponse)(nil), "core.CachePushResponse")
	proto.RegisterType((*CachePullRequest)(nil), "core.CachePullRequest")
	proto.RegisterType((*CachePullResponse)(nil), "core.CachePullResponse")
	proto.RegisterType((*AllStepsRequest)(nil), "core.AllStepsRequest")
	proto.RegisterType((*AllStepsResponse)(nil), "core.AllStepsResponse")
	proto.RegisterType((*RegisteredStep)(nil), "core.RegisteredStep")
	proto.RegisterType((*SingleStepRequest)(nil), "core.SingleStepRequest")
	proto.RegisterType((*SingleStepResponse)(nil), "core.SingleStepResponse")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 1027 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0xd6, 0x7a, 0xff, 0xcf, 0xae, 0xd2, 0x64, 0x5a, 0x21, 0x6b, 0x55, 0xa2, 0xc8, 0xa2, 0x21,
	0x42, 0xb0, 0x51, 0x13, 0xa8, 0x22, 0x2e, 0x90, 0x68, 0x95, 0x8a, 0xe5, 0xb7, 0x72, 0x0a, 0x17,
	0xdc, 0x4d, 0xec, 0x13, 0xaf, 0x89, 0x3d, 0xe3, 0xce, 0x8c, 0xb3, 0xc9, 0x7b, 0xf0, 0x12, 0x3c,
	0x01, 0xef, 0xc1, 0x6b, 0x70, 0xcf, 0x35, 0x9a, 0x1f, 0x7b, 0xed, 0xcd, 0x86, 0x72, 0x37, 0xe7,
	0xff, 0x9c, 0xef, 0xfc, 0xd8, 0x30, 0x8d, 0x78, 0x9e, 0x73, 0x36, 0x2f, 0x04, 0x57, 0x9c, 0xf4,
	0x22, 0x2e, 0x30, 0xf8, 0xa7, 0x03, 0xc3, 0x37, 0x34, 0xba, 0xa6, 0x09, 0x12, 0x02, 0x3d, 0x46,
	0x73, 0xf4, 0x3b, 0x07, 0x9d, 0xa3, 0x71, 0x68, 0xde, 0x9a, 0x97, 0x51, 0x96, 0xf8, 0x9e, 0xe5,
	0xe9, 0x37, 0xf1, 0x61, 0x78, 0x83, 0x42, 0xa6, 0x9c, 0xf9, 0x5d, 0xc3, 0xae, 0x48, 0xf2, 0x29,
	0x4c, 0xf0, 0x16, 0xa3, 0x52, 0xd1, 0xcb, 0x0c, 0xa5, 0xdf, 0x3b, 0xe8, 0x1c, 0x4d, 0x4e, 0x60,
	0xae, 0x23, 0xcd, 0xcf, 0x6f, 0x31, 0x0a, 0x9b, 0x62, 0x32, 0x87, 0xbe, 0x54, 0x58, 0x48, 0xbf,
	0x7f, 0xd0, 0x3d, 0x9a, 0x9c, 0xf8, 0x56, 0xcf, 0x65, 0x33, 0xbf, 0xd0, 0xa2, 0x73, 0xa6, 0xc4,
	0x5d, 0x68, 0xd5, 0x66, 0xdf, 0x01, 0xac, 0x99, 0x64, 0x17, 0xba, 0xd7, 0x78, 0xe7, 0x92, 0xd5,
	0x4f, 0xf2, 0x31, 0xf4, 0x6f, 0x68, 0x56, 0xa2, 0x49, 0x76, 0x72, 0xb2, 0xd7, 0xf2, 0xa7, 0x2d,
	0x43, 0x2b, 0xff, 0xd2, 0x3b, 0xeb, 0x04, 0xb7, 0xd0, 0xd3, 0x19, 0x91, 0x8f, 0x60, 0x10, 0x53,
	0xb1, 0x4a, 0x99, 0xf1, 0x34, 0x39, 0x99, 0x5a, 0xab, 0x97, 0x29, 0xa3, 0xe2, 0x2e, 0x74, 0x32,
	0x12, 0x40, 0x3f, 0x4b, 0x59, 0x79, 0xeb, 0x5c, 0xb7, 0x95, 0xac, 0x88, 0x1c, 0xc2, 0x70, 0x95,
	0xb2, 0x98, 0xaf, 0xa4, 0x81, 0x65, 0x53, 0xab, 0x12, 0x06, 0x27, 0x30, 0xb0, 0x2c, 0xf2, 0x04,
	0xfa, 0x34, 0x8f, 0x5f, 0x7c, 0xee, 0x8a, 0xb0, 0x84, 0x86, 0x3c, 0x3d, 0x3d, 0x7b, 0x51, 0x41,
	0xae, 0xdf, 0xc1, 0x5f, 0x1e, 0x4c, 0x1a, 0x85, 0x90, 0x03, 0x98, 0xc4, 0x28, 0x23, 0x91, 0x16,
	0x4a, 0xb7, 0xc1, 0xda, 0x37, 0x59, 0xe4, 0x0b, 0x18, 0xa4, 0xac, 0x28, 0x95, 0xf4, 0x3d, 0x83,
	0xee, 0x87, 0xf7, 0xd0, 0x98, 0x2f, 0x8c, 0xdc, 0x42, 0xec, 0x94, 0xc9, 0x19, 0x0c, 0x79, 0xa9,
	0x8c, 0x5d, 0xd7, 0xd8, 0xed, 0xdf, 0xb7, 0xfb, 0xc9, 0x2a, 0x58, 0xc3, 0x4a, 0x9d, 0x7c, 0x00,
	0x03, 0x49, 0xf3, 0x22, 0x43, 0xd3, 0xf6, 0x71, 0xe8, 0xa8, 0xd9, 0xb7, 0x30, 0x69, 0x04, 0xda,
	0xd2, 0xb6, 0x67, 0xed, 0xb6, 0x3d, 0xb2, 0x01, 0x8d, 0xcd, 0x82, 0x5d, 0xf1, 0x46, 0xd3, 0x66,
	0xdf, 0xc3, 0xb4, 0x19, 0x7c, 0x8b, 0xb3, 0xc3, 0xb6, 0xb3, 0x5d, 0xeb, 0xcc, 0x1a, 0x6d, 0x78,
	0x0b, 0x16, 0x30, 0xae, 0xa3, 0x90, 0x19, 0x8c, 0x04, 0xbe, 0x2b, 0x53, 0x81, 0xb1, 0xf1, 0x37,
	0x0a, 0x6b, 0x7a, 0x13, 0x6d, 0xef, 0x1e, 0xda, 0xc1, 0x1c, 0x60, 0x1d, 0xe3, 0xfd, 0xdd, 0x09,
	0xfe, 0xf4, 0x60, 0x72, 0xce, 0x6e, 0x52, 0xc1, 0x59, 0x8e, 0x4c, 0xe9, 0x95, 0x2a, 0x04, 0xff,
	0x0d, 0x23, 0xe5, 0xb4, 0x2b, 0x52, 0xe7, 0xb5, 0xe2, 0xe2, 0xfa, 0x2a, 0xe3, 0x2b, 0x17, 0xb8,
	0xa6, 0xf5, 0xfc, 0x88, 0x92, 0x2d, 0x62, 0xb7, 0x86, 0x96, 0xd0, 0x16, 0x7a, 0x5f, 0x7e, 0xd4,
	0xab, 0x6c, 0x5b, 0x51, 0xd3, 0x3a, 0x33, 0xfd, 0xfe, 0xc5, 0xad, 0x6f, 0xdf, 0x66, 0xd6, 0x60,
	0x91, 0xa7, 0x30, 0x36, 0xa3, 0xf0, 0x3a, 0xcd, 0xd0, 0x1f, 0x18, 0xf9, 0x9a, 0xa1, 0xed, 0x95,
	0x48, 0x93, 0x04, 0xc5, 0xdb, 0xbb, 0x02, 0xfd, 0xa1, 0xb5, 0x6f, 0xb0, 0xc8, 0x21, 0xec, 0x68,
	0x77, 0x0b, 0x26, 0x15, 0x65, 0x11, 0x2e, 0x62, 0x7f, 0x64, 0x94, 0x36, 0xb8, 0xa6, 0x62, 0x3b,
	0x53, 0xfe, 0xd8, 0x55, 0xec, 0xce, 0xd0, 0x53, 0x18, 0x47, 0x34, 0x5a, 0xe2, 0x37, 0x5c, 0x2a,
	0x1f, 0x6c, 0x06, 0x35, 0x23, 0xd8, 0x81, 0xe9, 0x79, 0x5e, 0xa8, 0xbb, 0x1f, 0x50, 0x4a, 0x9a,
	0x60, 0x70, 0x09, 0x44, 0x0f, 0xa5, 0x9b, 0xcf, 0x10, 0xdf, 0x95, 0x28, 0x15, 0xd9, 0x01, 0x2f,
	0x8d, 0x1d, 0x94, 0x5e, 0x1a, 0x37, 0x4f, 0x96, 0xd7, 0x3e, 0x59, 0x3b, 0xe0, 0x71, 0xe9, 0x00,
	0xf4, 0xb8, 0xd4, 0xdb, 0x47, 0x45, 0xb4, 0x74, 0xc8, 0x99, 0x77, 0x70, 0x01, 0x8f, 0x5b, 0x31,
	0x64, 0xc1, 0x99, 0x44, 0xb2, 0x0f, 0xe0, 0x72, 0xfe, 0x59, 0x64, 0x2e, 0x58, 0x83, 0xa3, 0x0b,
	0x29, 0xca, 0xcb, 0x2c, 0x95, 0xcb, 0x45, 0xec, 0xc2, 0xae, 0x19, 0xc1, 0x1f, 0x1d, 0xd8, 0x7d,
	0xa5, 0xcb, 0x7a, 0x53, 0xca, 0xe5, 0x43, 0x79, 0xcf, 0x60, 0x94, 0xa3, 0xa2, 0x31, 0x55, 0xd4,
	0x78, 0x98, 0x86, 0x35, 0xad, 0x17, 0x4e, 0x60, 0xc4, 0x85, 0x6d, 0xff, 0x34, 0x74, 0x54, 0x8d,
	0x5f, 0x63, 0x00, 0xd6, 0x0c, 0x72, 0x0a, 0x13, 0x5c, 0x0f, 0x9e, 0x99, 0x80, 0xfa, 0x54, 0x36,
	0x26, 0x32, 0x6c, 0x6a, 0x05, 0x8f, 0x61, 0xaf, 0x91, 0xaa, 0x2d, 0x3f, 0x28, 0xeb, 0xfc, 0xb3,
	0xec, 0xa1, 0xfc, 0x5b, 0xb9, 0x78, 0xef, 0xc9, 0xa5, 0xfb, 0xbf, 0x72, 0x89, 0xea, 0x5c, 0x74,
	0x58, 0xd7, 0x8a, 0x35, 0x16, 0x9d, 0x16, 0x16, 0xff, 0x85, 0xdf, 0x0c, 0x46, 0x8c, 0xab, 0xd7,
	0xbc, 0x64, 0x16, 0xc1, 0x51, 0x58, 0xd3, 0xc1, 0x73, 0x78, 0xf4, 0x75, 0x96, 0x99, 0xaf, 0x4d,
	0x55, 0xda, 0x3e, 0x80, 0x44, 0x3d, 0x0e, 0x6f, 0x51, 0xe4, 0x55, 0xb7, 0xd7, 0x9c, 0xe0, 0xf7,
	0x0e, 0xec, 0xae, 0x6d, 0x5c, 0x5e, 0x3e, 0x0c, 0x65, 0x19, 0x45, 0x28, 0xa5, 0x3b, 0x2a, 0x15,
	0xa9, 0x25, 0xb9, 0x1d, 0xe1, 0x6a, 0x22, 0x1d, 0xa9, 0x77, 0xcc, 0x66, 0xff, 0x8a, 0x97, 0x0e,
	0x95, 0x6e, 0xd8, 0x64, 0x91, 0x4f, 0xa0, 0x9f, 0x2a, 0xcc, 0xf5, 0x07, 0x56, 0x9f, 0xe8, 0x27,
	0x16, 0xb1, 0x10, 0x93, 0x54, 0x2a, 0x14, 0x18, 0xdb, 0x6f, 0x9d, 0x51, 0x09, 0xfe, 0xee, 0xc0,
	0x4e, 0x5b, 0x42, 0x9e, 0x41, 0x4f, 0x2f, 0xa3, 0xfb, 0xe0, 0x6d, 0xf9, 0x4c, 0x1a, 0xb1, 0xc6,
	0x27, 0xe3, 0x11, 0x6d, 0x9c, 0xbc, 0x9a, 0x26, 0x01, 0x4c, 0xab, 0xb7, 0x39, 0x04, 0x76, 0x7f,
	0x5a, 0xbc, 0xf6, 0xf8, 0xf7, 0x36, 0xc6, 0x5f, 0x77, 0x8c, 0x96, 0x6a, 0xc9, 0x85, 0x3b, 0x42,
	0x8e, 0xd2, 0xd5, 0xbb, 0x15, 0x32, 0x33, 0x63, 0x2f, 0x50, 0x93, 0xa5, 0xf3, 0xba, 0xa8, 0xee,
	0x9b, 0x3d, 0x40, 0x35, 0x1d, 0x5c, 0xc3, 0xde, 0x45, 0xca, 0x92, 0xcc, 0xd6, 0xe1, 0x3a, 0xb7,
	0xe1, 0xb2, 0xb3, 0xd5, 0x65, 0x7d, 0x32, 0xbd, 0x8d, 0x93, 0xf9, 0xe0, 0xdf, 0x4e, 0xf0, 0x15,
	0x90, 0x66, 0x30, 0xd7, 0xf2, 0xa3, 0x16, 0xba, 0xdb, 0x7b, 0x63, 0x34, 0x5e, 0x3e, 0xff, 0xf5,
	0x38, 0x49, 0xd5, 0xb2, 0xbc, 0x9c, 0x47, 0x3c, 0x3f, 0xa6, 0x45, 0xa1, 0x04, 0xa2, 0xe4, 0x57,
	0x6a, 0x45, 0x05, 0x1e, 0x27, 0xfc, 0xb3, 0xea, 0xd0, 0x1f, 0x17, 0xd7, 0xc9, 0xb1, 0xf6, 0x73,
	0x39, 0x30, 0xff, 0x6e, 0xa7, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x1a, 0xc6, 0xf2, 0xcb,
	0x09, 0x00, 0x00,
}
