// Code generated by protoc-gen-go. DO NOT EDIT.
// source: engine_api.proto

package core // import "github.com/apptreesoftware/go-workflow/pkg/core"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SpawnWorkflowRequest struct {
	Environment          *Environment `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	Workflow             string       `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Input                []byte       `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte       `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32        `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *SpawnWorkflowRequest) Reset()         { *m = SpawnWorkflowRequest{} }
func (m *SpawnWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*SpawnWorkflowRequest) ProtoMessage()    {}
func (*SpawnWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_engine_api_12862403ee3a8564, []int{0}
}
func (m *SpawnWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpawnWorkflowRequest.Unmarshal(m, b)
}
func (m *SpawnWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpawnWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *SpawnWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpawnWorkflowRequest.Merge(dst, src)
}
func (m *SpawnWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_SpawnWorkflowRequest.Size(m)
}
func (m *SpawnWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SpawnWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SpawnWorkflowRequest proto.InternalMessageInfo

func (m *SpawnWorkflowRequest) GetEnvironment() *Environment {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *SpawnWorkflowRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func (m *SpawnWorkflowRequest) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

type SpawnWorkflowResponse struct {
	QueueId              string   `protobuf:"bytes,1,opt,name=queueId,proto3" json:"queueId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *SpawnWorkflowResponse) Reset()         { *m = SpawnWorkflowResponse{} }
func (m *SpawnWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*SpawnWorkflowResponse) ProtoMessage()    {}
func (*SpawnWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_engine_api_12862403ee3a8564, []int{1}
}
func (m *SpawnWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpawnWorkflowResponse.Unmarshal(m, b)
}
func (m *SpawnWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpawnWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *SpawnWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpawnWorkflowResponse.Merge(dst, src)
}
func (m *SpawnWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_SpawnWorkflowResponse.Size(m)
}
func (m *SpawnWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SpawnWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SpawnWorkflowResponse proto.InternalMessageInfo

func (m *SpawnWorkflowResponse) GetQueueId() string {
	if m != nil {
		return m.QueueId
	}
	return ""
}

type StepCompleteRequest struct {
	Environment          *Environment `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	Output               []byte       `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode             int64        `protobuf:"varint,3,opt,name=exitCode,proto3" json:"exitCode,omitempty"`
	Error                string       `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte       `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32        `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *StepCompleteRequest) Reset()         { *m = StepCompleteRequest{} }
func (m *StepCompleteRequest) String() string { return proto.CompactTextString(m) }
func (*StepCompleteRequest) ProtoMessage()    {}
func (*StepCompleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_engine_api_12862403ee3a8564, []int{2}
}
func (m *StepCompleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepCompleteRequest.Unmarshal(m, b)
}
func (m *StepCompleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepCompleteRequest.Marshal(b, m, deterministic)
}
func (dst *StepCompleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepCompleteRequest.Merge(dst, src)
}
func (m *StepCompleteRequest) XXX_Size() int {
	return xxx_messageInfo_StepCompleteRequest.Size(m)
}
func (m *StepCompleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StepCompleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StepCompleteRequest proto.InternalMessageInfo

func (m *StepCompleteRequest) GetEnvironment() *Environment {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *StepCompleteRequest) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *StepCompleteRequest) GetExitCode() int64 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *StepCompleteRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type StepCompleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *StepCompleteResponse) Reset()         { *m = StepCompleteResponse{} }
func (m *StepCompleteResponse) String() string { return proto.CompactTextString(m) }
func (*StepCompleteResponse) ProtoMessage()    {}
func (*StepCompleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_engine_api_12862403ee3a8564, []int{3}
}
func (m *StepCompleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepCompleteResponse.Unmarshal(m, b)
}
func (m *StepCompleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepCompleteResponse.Marshal(b, m, deterministic)
}
func (dst *StepCompleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepCompleteResponse.Merge(dst, src)
}
func (m *StepCompleteResponse) XXX_Size() int {
	return xxx_messageInfo_StepCompleteResponse.Size(m)
}
func (m *StepCompleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StepCompleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StepCompleteResponse proto.InternalMessageInfo

type LogRequest struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LogLevel             string   `protobuf:"bytes,3,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	Project              string   `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	Workflow             string   `protobuf:"bytes,5,opt,name=workflow,proto3" json:"workflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_engine_api_12862403ee3a8564, []int{4}
}
func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (dst *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(dst, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *LogRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LogRequest) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

func (m *LogRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *LogRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

type LogResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *LogResponse) Reset()         { *m = LogResponse{} }
func (m *LogResponse) String() string { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()    {}
func (*LogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_engine_api_12862403ee3a8564, []int{5}
}
func (m *LogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogResponse.Unmarshal(m, b)
}
func (m *LogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogResponse.Marshal(b, m, deterministic)
}
func (dst *LogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogResponse.Merge(dst, src)
}
func (m *LogResponse) XXX_Size() int {
	return xxx_messageInfo_LogResponse.Size(m)
}
func (m *LogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogResponse proto.InternalMessageInfo

func (m *LogResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LogResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SpawnWorkflowRequest)(nil), "core.SpawnWorkflowRequest")
	proto.RegisterType((*SpawnWorkflowResponse)(nil), "core.SpawnWorkflowResponse")
	proto.RegisterType((*StepCompleteRequest)(nil), "core.StepCompleteRequest")
	proto.RegisterType((*StepCompleteResponse)(nil), "core.StepCompleteResponse")
	proto.RegisterType((*LogRequest)(nil), "core.LogRequest")
	proto.RegisterType((*LogResponse)(nil), "core.LogResponse")
}

func init() { proto.RegisterFile("engine_api.proto", fileDescriptor_engine_api_12862403ee3a8564) }

var fileDescriptor_engine_api_12862403ee3a8564 = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xfb, 0x45, 0x33, 0x69, 0xab, 0x76, 0x09, 0xc1, 0x98, 0x4b, 0xe4, 0x53, 0x2e, 0x24,
	0x4a, 0x7b, 0xe1, 0xc0, 0x25, 0x8d, 0x02, 0x54, 0x2a, 0x52, 0xe4, 0x1c, 0x90, 0xb8, 0x20, 0xc7,
	0x99, 0x3a, 0x6e, 0x6c, 0xcf, 0x76, 0xbd, 0x6e, 0x00, 0x89, 0xbf, 0x80, 0x84, 0xc4, 0x0f, 0x46,
	0xbb, 0x5e, 0x27, 0x4e, 0x6a, 0x4e, 0x1c, 0xdf, 0x9b, 0x79, 0xe3, 0x37, 0x6f, 0x27, 0x81, 0x73,
	0x4c, 0xc3, 0x28, 0xc5, 0xaf, 0x3e, 0x8f, 0x7a, 0x5c, 0x90, 0x24, 0x76, 0x10, 0x90, 0x40, 0xe7,
	0x24, 0xa0, 0x24, 0xa1, 0xb4, 0xe0, 0xdc, 0x9f, 0xd0, 0x9a, 0x72, 0x7f, 0x95, 0x7e, 0x26, 0xb1,
	0xbc, 0x8b, 0x69, 0xe5, 0xe1, 0x43, 0x8e, 0x99, 0x64, 0x57, 0xd0, 0xc4, 0xf4, 0x31, 0x12, 0x94,
	0x26, 0x98, 0x4a, 0xdb, 0xea, 0x58, 0xdd, 0xe6, 0xe5, 0x45, 0x4f, 0x4d, 0xe8, 0x8d, 0x37, 0x05,
	0xaf, 0xda, 0xc5, 0x1c, 0x38, 0x5e, 0x99, 0x39, 0xf6, 0x5e, 0xc7, 0xea, 0x36, 0xbc, 0x35, 0x66,
	0x2d, 0x38, 0x8c, 0x52, 0x9e, 0x4b, 0x7b, 0xbf, 0x63, 0x75, 0x4f, 0xbc, 0x02, 0xb8, 0x03, 0x78,
	0xb1, 0xf3, 0xf9, 0x8c, 0x53, 0x9a, 0x21, 0xb3, 0xe1, 0xd9, 0x43, 0x8e, 0x39, 0xde, 0xcc, 0xf5,
	0xb7, 0x1b, 0x5e, 0x09, 0xdd, 0x3f, 0x16, 0x3c, 0x9f, 0x4a, 0xe4, 0x23, 0x4a, 0x78, 0x8c, 0x12,
	0xff, 0xcb, 0x71, 0x1b, 0x8e, 0x28, 0x97, 0xca, 0xd6, 0x9e, 0xb6, 0x65, 0x90, 0xda, 0x04, 0xbf,
	0x45, 0x72, 0x44, 0x73, 0xd4, 0x86, 0xf7, 0xbd, 0x35, 0x56, 0x9b, 0xa0, 0x10, 0x24, 0xec, 0x03,
	0x6d, 0xac, 0x00, 0x6e, 0x1b, 0x5a, 0xdb, 0xae, 0x8a, 0x45, 0xdc, 0x5f, 0x16, 0xc0, 0x2d, 0x85,
	0xa5, 0xcb, 0x16, 0x1c, 0xde, 0xd3, 0x6c, 0xbd, 0x55, 0x01, 0xd4, 0xb6, 0x09, 0x66, 0x99, 0x1f,
	0xa2, 0xc9, 0xad, 0x84, 0xca, 0x48, 0x4c, 0xe1, 0x2d, 0x3e, 0x62, 0xac, 0x8d, 0x34, 0xbc, 0x35,
	0x56, 0x2a, 0x2e, 0xe8, 0x1e, 0x03, 0x69, 0xac, 0x94, 0x70, 0xeb, 0x21, 0x0e, 0xb7, 0x1f, 0xc2,
	0x1d, 0x42, 0x53, 0xfb, 0xd9, 0x04, 0x9d, 0xe5, 0x41, 0x80, 0x59, 0xa6, 0x2d, 0x1d, 0x7b, 0x25,
	0xfc, 0xb7, 0xa9, 0xcb, 0xdf, 0x07, 0xd0, 0x18, 0xeb, 0xeb, 0x1a, 0x4e, 0x6e, 0xd8, 0x5b, 0x38,
	0x1b, 0xe6, 0x72, 0x41, 0x22, 0xfa, 0x81, 0xf3, 0x49, 0x94, 0x86, 0x8c, 0x99, 0xd4, 0x13, 0x2e,
	0xbf, 0x7f, 0x2a, 0x34, 0x4e, 0x0d, 0xc7, 0xc6, 0x70, 0xf6, 0x01, 0xa5, 0x8a, 0x6d, 0xe2, 0x07,
	0x4b, 0xc5, 0xd8, 0x45, 0x57, 0x85, 0x32, 0xc1, 0x39, 0xaf, 0x6a, 0x2a, 0x66, 0x85, 0x8f, 0x70,
	0xba, 0x75, 0x44, 0xcc, 0x31, 0xbd, 0x35, 0x87, 0xed, 0xbc, 0xae, 0xad, 0x99, 0x49, 0xef, 0xa0,
	0x31, 0xf2, 0x83, 0x05, 0x4e, 0xf2, 0x6c, 0xc1, 0xda, 0x45, 0xe7, 0x9a, 0x28, 0x27, 0xbc, 0x7c,
	0xc2, 0x3f, 0x51, 0xc7, 0xf1, 0x8e, 0x3a, 0x8e, 0xeb, 0xd5, 0x8a, 0x37, 0xea, 0x6b, 0x68, 0x6a,
	0x72, 0x8a, 0xbe, 0x08, 0x16, 0x65, 0x12, 0x15, 0x6a, 0x27, 0x89, 0xad, 0x8a, 0x99, 0xf1, 0x1e,
	0x4e, 0xab, 0x47, 0x38, 0x67, 0x95, 0xd4, 0x76, 0x7e, 0x2f, 0x8e, 0x53, 0x57, 0x32, 0x73, 0x06,
	0xfa, 0x66, 0xcb, 0x67, 0x3a, 0x2f, 0x3a, 0x37, 0x57, 0xec, 0x5c, 0x54, 0x98, 0x42, 0x72, 0x3d,
	0xf8, 0xd2, 0x0f, 0x23, 0xb9, 0xc8, 0x67, 0xbd, 0x80, 0x92, 0xbe, 0xcf, 0xb9, 0x14, 0x88, 0x19,
	0xdd, 0xc9, 0x95, 0x2f, 0xb0, 0x1f, 0xd2, 0x9b, 0xf2, 0x00, 0xfb, 0x7c, 0x19, 0xf6, 0x95, 0x7c,
	0x76, 0xa4, 0xff, 0x82, 0xae, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xca, 0x79, 0x26, 0xa8, 0xaa,
	0x04, 0x00, 0x00,
}
