// Code generated by protoc-gen-go. DO NOT EDIT.
// source: platform_api.proto

package core // import "github.com/apptreesoftware/go-workflow/pkg/core"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnvironmentStatus int32

const (
	EnvironmentStatus_Creating  EnvironmentStatus = 0
	EnvironmentStatus_Ready     EnvironmentStatus = 1
	EnvironmentStatus_Failed    EnvironmentStatus = 2
	EnvironmentStatus_Upgrading EnvironmentStatus = 3
)

var EnvironmentStatus_name = map[int32]string{
	0: "Creating",
	1: "Ready",
	2: "Failed",
	3: "Upgrading",
}
var EnvironmentStatus_value = map[string]int32{
	"Creating":  0,
	"Ready":     1,
	"Failed":    2,
	"Upgrading": 3,
}

func (x EnvironmentStatus) String() string {
	return proto.EnumName(EnvironmentStatus_name, int32(x))
}
func (EnvironmentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{0}
}

type EnvironmentConfiguration struct {
	EnvironmentName      string            `protobuf:"bytes,1,opt,name=environmentName,proto3" json:"environmentName,omitempty"`
	ResourcePlan         string            `protobuf:"bytes,2,opt,name=resourcePlan,proto3" json:"resourcePlan,omitempty"`
	Region               string            `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Url                  string            `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Status               EnvironmentStatus `protobuf:"varint,5,opt,name=status,proto3,enum=core.EnvironmentStatus" json:"status,omitempty"`
	StatusMessage        string            `protobuf:"bytes,6,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *EnvironmentConfiguration) Reset()         { *m = EnvironmentConfiguration{} }
func (m *EnvironmentConfiguration) String() string { return proto.CompactTextString(m) }
func (*EnvironmentConfiguration) ProtoMessage()    {}
func (*EnvironmentConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{0}
}
func (m *EnvironmentConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvironmentConfiguration.Unmarshal(m, b)
}
func (m *EnvironmentConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvironmentConfiguration.Marshal(b, m, deterministic)
}
func (dst *EnvironmentConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvironmentConfiguration.Merge(dst, src)
}
func (m *EnvironmentConfiguration) XXX_Size() int {
	return xxx_messageInfo_EnvironmentConfiguration.Size(m)
}
func (m *EnvironmentConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvironmentConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_EnvironmentConfiguration proto.InternalMessageInfo

func (m *EnvironmentConfiguration) GetEnvironmentName() string {
	if m != nil {
		return m.EnvironmentName
	}
	return ""
}

func (m *EnvironmentConfiguration) GetResourcePlan() string {
	if m != nil {
		return m.ResourcePlan
	}
	return ""
}

func (m *EnvironmentConfiguration) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *EnvironmentConfiguration) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EnvironmentConfiguration) GetStatus() EnvironmentStatus {
	if m != nil {
		return m.Status
	}
	return EnvironmentStatus_Creating
}

func (m *EnvironmentConfiguration) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type UpdateEnvironmentRequest struct {
	EnvironmentName      string            `protobuf:"bytes,1,opt,name=environmentName,proto3" json:"environmentName,omitempty"`
	ResourcePlan         string            `protobuf:"bytes,2,opt,name=resourcePlan,proto3" json:"resourcePlan,omitempty"`
	Status               EnvironmentStatus `protobuf:"varint,3,opt,name=status,proto3,enum=core.EnvironmentStatus" json:"status,omitempty"`
	Url                  string            `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	StatusMessage        string            `protobuf:"bytes,5,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *UpdateEnvironmentRequest) Reset()         { *m = UpdateEnvironmentRequest{} }
func (m *UpdateEnvironmentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEnvironmentRequest) ProtoMessage()    {}
func (*UpdateEnvironmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{1}
}
func (m *UpdateEnvironmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEnvironmentRequest.Unmarshal(m, b)
}
func (m *UpdateEnvironmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEnvironmentRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateEnvironmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEnvironmentRequest.Merge(dst, src)
}
func (m *UpdateEnvironmentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEnvironmentRequest.Size(m)
}
func (m *UpdateEnvironmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEnvironmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEnvironmentRequest proto.InternalMessageInfo

func (m *UpdateEnvironmentRequest) GetEnvironmentName() string {
	if m != nil {
		return m.EnvironmentName
	}
	return ""
}

func (m *UpdateEnvironmentRequest) GetResourcePlan() string {
	if m != nil {
		return m.ResourcePlan
	}
	return ""
}

func (m *UpdateEnvironmentRequest) GetStatus() EnvironmentStatus {
	if m != nil {
		return m.Status
	}
	return EnvironmentStatus_Creating
}

func (m *UpdateEnvironmentRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UpdateEnvironmentRequest) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type EnvironmentRequest struct {
	EnvironmentName      string   `protobuf:"bytes,1,opt,name=environmentName,proto3" json:"environmentName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *EnvironmentRequest) Reset()         { *m = EnvironmentRequest{} }
func (m *EnvironmentRequest) String() string { return proto.CompactTextString(m) }
func (*EnvironmentRequest) ProtoMessage()    {}
func (*EnvironmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{2}
}
func (m *EnvironmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvironmentRequest.Unmarshal(m, b)
}
func (m *EnvironmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvironmentRequest.Marshal(b, m, deterministic)
}
func (dst *EnvironmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvironmentRequest.Merge(dst, src)
}
func (m *EnvironmentRequest) XXX_Size() int {
	return xxx_messageInfo_EnvironmentRequest.Size(m)
}
func (m *EnvironmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvironmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnvironmentRequest proto.InternalMessageInfo

func (m *EnvironmentRequest) GetEnvironmentName() string {
	if m != nil {
		return m.EnvironmentName
	}
	return ""
}

type CreateEnvironmentRequest struct {
	EnvironmentName      string   `protobuf:"bytes,1,opt,name=environmentName,proto3" json:"environmentName,omitempty"`
	ResourcePlan         string   `protobuf:"bytes,2,opt,name=resourcePlan,proto3" json:"resourcePlan,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *CreateEnvironmentRequest) Reset()         { *m = CreateEnvironmentRequest{} }
func (m *CreateEnvironmentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEnvironmentRequest) ProtoMessage()    {}
func (*CreateEnvironmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{3}
}
func (m *CreateEnvironmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEnvironmentRequest.Unmarshal(m, b)
}
func (m *CreateEnvironmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEnvironmentRequest.Marshal(b, m, deterministic)
}
func (dst *CreateEnvironmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEnvironmentRequest.Merge(dst, src)
}
func (m *CreateEnvironmentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEnvironmentRequest.Size(m)
}
func (m *CreateEnvironmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEnvironmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEnvironmentRequest proto.InternalMessageInfo

func (m *CreateEnvironmentRequest) GetEnvironmentName() string {
	if m != nil {
		return m.EnvironmentName
	}
	return ""
}

func (m *CreateEnvironmentRequest) GetResourcePlan() string {
	if m != nil {
		return m.ResourcePlan
	}
	return ""
}

func (m *CreateEnvironmentRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type DeleteEnvironmentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *DeleteEnvironmentResponse) Reset()         { *m = DeleteEnvironmentResponse{} }
func (m *DeleteEnvironmentResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteEnvironmentResponse) ProtoMessage()    {}
func (*DeleteEnvironmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{4}
}
func (m *DeleteEnvironmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEnvironmentResponse.Unmarshal(m, b)
}
func (m *DeleteEnvironmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEnvironmentResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteEnvironmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEnvironmentResponse.Merge(dst, src)
}
func (m *DeleteEnvironmentResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteEnvironmentResponse.Size(m)
}
func (m *DeleteEnvironmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEnvironmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEnvironmentResponse proto.InternalMessageInfo

type UpdateAvailableRequest struct {
	Os                   string   `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch                 string   `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *UpdateAvailableRequest) Reset()         { *m = UpdateAvailableRequest{} }
func (m *UpdateAvailableRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAvailableRequest) ProtoMessage()    {}
func (*UpdateAvailableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{5}
}
func (m *UpdateAvailableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAvailableRequest.Unmarshal(m, b)
}
func (m *UpdateAvailableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAvailableRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateAvailableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAvailableRequest.Merge(dst, src)
}
func (m *UpdateAvailableRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAvailableRequest.Size(m)
}
func (m *UpdateAvailableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAvailableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAvailableRequest proto.InternalMessageInfo

func (m *UpdateAvailableRequest) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *UpdateAvailableRequest) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *UpdateAvailableRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type UpdateAvailableResponse struct {
	Available            bool     `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *UpdateAvailableResponse) Reset()         { *m = UpdateAvailableResponse{} }
func (m *UpdateAvailableResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAvailableResponse) ProtoMessage()    {}
func (*UpdateAvailableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{6}
}
func (m *UpdateAvailableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAvailableResponse.Unmarshal(m, b)
}
func (m *UpdateAvailableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAvailableResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateAvailableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAvailableResponse.Merge(dst, src)
}
func (m *UpdateAvailableResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAvailableResponse.Size(m)
}
func (m *UpdateAvailableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAvailableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAvailableResponse proto.InternalMessageInfo

func (m *UpdateAvailableResponse) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *UpdateAvailableResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *UpdateAvailableResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Project struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Environment          string   `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{7}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (dst *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(dst, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *Project) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ListProjectRequest struct {
	Environment          string   `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ListProjectRequest) Reset()         { *m = ListProjectRequest{} }
func (m *ListProjectRequest) String() string { return proto.CompactTextString(m) }
func (*ListProjectRequest) ProtoMessage()    {}
func (*ListProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{8}
}
func (m *ListProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectRequest.Unmarshal(m, b)
}
func (m *ListProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectRequest.Marshal(b, m, deterministic)
}
func (dst *ListProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectRequest.Merge(dst, src)
}
func (m *ListProjectRequest) XXX_Size() int {
	return xxx_messageInfo_ListProjectRequest.Size(m)
}
func (m *ListProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectRequest proto.InternalMessageInfo

func (m *ListProjectRequest) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

type ListProjectResponse struct {
	Success              bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Projects             []*Project `protobuf:"bytes,3,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte     `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32      `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ListProjectResponse) Reset()         { *m = ListProjectResponse{} }
func (m *ListProjectResponse) String() string { return proto.CompactTextString(m) }
func (*ListProjectResponse) ProtoMessage()    {}
func (*ListProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{9}
}
func (m *ListProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectResponse.Unmarshal(m, b)
}
func (m *ListProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectResponse.Marshal(b, m, deterministic)
}
func (dst *ListProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectResponse.Merge(dst, src)
}
func (m *ListProjectResponse) XXX_Size() int {
	return xxx_messageInfo_ListProjectResponse.Size(m)
}
func (m *ListProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectResponse proto.InternalMessageInfo

func (m *ListProjectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListProjectResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListProjectResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type AddUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=projectId,proto3" json:"projectId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{10}
}
func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (dst *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(dst, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddUserRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type UserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{11}
}
func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (dst *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(dst, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ProjectWithEnvironment struct {
	Project              *Project                  `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Environment          *EnvironmentConfiguration `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte                    `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32                     `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ProjectWithEnvironment) Reset()         { *m = ProjectWithEnvironment{} }
func (m *ProjectWithEnvironment) String() string { return proto.CompactTextString(m) }
func (*ProjectWithEnvironment) ProtoMessage()    {}
func (*ProjectWithEnvironment) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{12}
}
func (m *ProjectWithEnvironment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectWithEnvironment.Unmarshal(m, b)
}
func (m *ProjectWithEnvironment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectWithEnvironment.Marshal(b, m, deterministic)
}
func (dst *ProjectWithEnvironment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectWithEnvironment.Merge(dst, src)
}
func (m *ProjectWithEnvironment) XXX_Size() int {
	return xxx_messageInfo_ProjectWithEnvironment.Size(m)
}
func (m *ProjectWithEnvironment) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectWithEnvironment.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectWithEnvironment proto.InternalMessageInfo

func (m *ProjectWithEnvironment) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *ProjectWithEnvironment) GetEnvironment() *EnvironmentConfiguration {
	if m != nil {
		return m.Environment
	}
	return nil
}

type MoveProjectRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Environment          string   `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *MoveProjectRequest) Reset()         { *m = MoveProjectRequest{} }
func (m *MoveProjectRequest) String() string { return proto.CompactTextString(m) }
func (*MoveProjectRequest) ProtoMessage()    {}
func (*MoveProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{13}
}
func (m *MoveProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveProjectRequest.Unmarshal(m, b)
}
func (m *MoveProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveProjectRequest.Marshal(b, m, deterministic)
}
func (dst *MoveProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveProjectRequest.Merge(dst, src)
}
func (m *MoveProjectRequest) XXX_Size() int {
	return xxx_messageInfo_MoveProjectRequest.Size(m)
}
func (m *MoveProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveProjectRequest proto.InternalMessageInfo

func (m *MoveProjectRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *MoveProjectRequest) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

type ConfigRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ConfigRequest) Reset()         { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()    {}
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{14}
}
func (m *ConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest.Unmarshal(m, b)
}
func (m *ConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest.Marshal(b, m, deterministic)
}
func (dst *ConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest.Merge(dst, src)
}
func (m *ConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest.Size(m)
}
func (m *ConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest proto.InternalMessageInfo

func (m *ConfigRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SecretResponse struct {
	SecretKey            string   `protobuf:"bytes,1,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *SecretResponse) Reset()         { *m = SecretResponse{} }
func (m *SecretResponse) String() string { return proto.CompactTextString(m) }
func (*SecretResponse) ProtoMessage()    {}
func (*SecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{15}
}
func (m *SecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretResponse.Unmarshal(m, b)
}
func (m *SecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretResponse.Marshal(b, m, deterministic)
}
func (dst *SecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretResponse.Merge(dst, src)
}
func (m *SecretResponse) XXX_Size() int {
	return xxx_messageInfo_SecretResponse.Size(m)
}
func (m *SecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SecretResponse proto.InternalMessageInfo

func (m *SecretResponse) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

type AssistantRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	IntentDiscoveryUrl   string   `protobuf:"bytes,5,opt,name=intentDiscoveryUrl,proto3" json:"intentDiscoveryUrl,omitempty"`
	DebugDiscoveryUrl    string   `protobuf:"bytes,6,opt,name=debugDiscoveryUrl,proto3" json:"debugDiscoveryUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *AssistantRequest) Reset()         { *m = AssistantRequest{} }
func (m *AssistantRequest) String() string { return proto.CompactTextString(m) }
func (*AssistantRequest) ProtoMessage()    {}
func (*AssistantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_api_38da360bbe72c067, []int{16}
}
func (m *AssistantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssistantRequest.Unmarshal(m, b)
}
func (m *AssistantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssistantRequest.Marshal(b, m, deterministic)
}
func (dst *AssistantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssistantRequest.Merge(dst, src)
}
func (m *AssistantRequest) XXX_Size() int {
	return xxx_messageInfo_AssistantRequest.Size(m)
}
func (m *AssistantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssistantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssistantRequest proto.InternalMessageInfo

func (m *AssistantRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AssistantRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AssistantRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AssistantRequest) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *AssistantRequest) GetIntentDiscoveryUrl() string {
	if m != nil {
		return m.IntentDiscoveryUrl
	}
	return ""
}

func (m *AssistantRequest) GetDebugDiscoveryUrl() string {
	if m != nil {
		return m.DebugDiscoveryUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*EnvironmentConfiguration)(nil), "core.EnvironmentConfiguration")
	proto.RegisterType((*UpdateEnvironmentRequest)(nil), "core.UpdateEnvironmentRequest")
	proto.RegisterType((*EnvironmentRequest)(nil), "core.EnvironmentRequest")
	proto.RegisterType((*CreateEnvironmentRequest)(nil), "core.CreateEnvironmentRequest")
	proto.RegisterType((*DeleteEnvironmentResponse)(nil), "core.DeleteEnvironmentResponse")
	proto.RegisterType((*UpdateAvailableRequest)(nil), "core.UpdateAvailableRequest")
	proto.RegisterType((*UpdateAvailableResponse)(nil), "core.UpdateAvailableResponse")
	proto.RegisterType((*Project)(nil), "core.Project")
	proto.RegisterType((*ListProjectRequest)(nil), "core.ListProjectRequest")
	proto.RegisterType((*ListProjectResponse)(nil), "core.ListProjectResponse")
	proto.RegisterType((*AddUserRequest)(nil), "core.AddUserRequest")
	proto.RegisterType((*UserRequest)(nil), "core.UserRequest")
	proto.RegisterType((*ProjectWithEnvironment)(nil), "core.ProjectWithEnvironment")
	proto.RegisterType((*MoveProjectRequest)(nil), "core.MoveProjectRequest")
	proto.RegisterType((*ConfigRequest)(nil), "core.ConfigRequest")
	proto.RegisterType((*SecretResponse)(nil), "core.SecretResponse")
	proto.RegisterType((*AssistantRequest)(nil), "core.AssistantRequest")
	proto.RegisterEnum("core.EnvironmentStatus", EnvironmentStatus_name, EnvironmentStatus_value)
}

func init() { proto.RegisterFile("platform_api.proto", fileDescriptor_platform_api_38da360bbe72c067) }

var fileDescriptor_platform_api_38da360bbe72c067 = []byte{
	// 1015 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x5f, 0x6f, 0xe3, 0xc4,
	0x17, 0xfd, 0xb9, 0x69, 0xd3, 0xe6, 0x36, 0xc9, 0x26, 0xd3, 0x5f, 0xbb, 0x6e, 0x28, 0x6c, 0x65,
	0x21, 0xd1, 0x45, 0x90, 0x68, 0xbb, 0xd2, 0xbe, 0xb1, 0x22, 0xed, 0x42, 0x44, 0xa1, 0x4b, 0x95,
	0xd2, 0x45, 0x42, 0x42, 0xab, 0x89, 0x7d, 0xeb, 0x0e, 0xeb, 0x78, 0xcc, 0xcc, 0x38, 0x55, 0xde,
	0x90, 0xf8, 0x84, 0x48, 0x7c, 0x09, 0x5e, 0xf9, 0x04, 0xc8, 0xf6, 0x38, 0xfe, 0x97, 0x28, 0x95,
	0x16, 0xf1, 0x16, 0xdf, 0x3b, 0x73, 0xe6, 0xdc, 0x7b, 0xcf, 0x9c, 0x51, 0x80, 0x04, 0x1e, 0x55,
	0xb7, 0x5c, 0x4c, 0xdf, 0xd2, 0x80, 0xf5, 0x03, 0xc1, 0x15, 0x27, 0x9b, 0x36, 0x17, 0xd8, 0x6b,
	0xda, 0x7c, 0x3a, 0xe5, 0x7e, 0x12, 0xeb, 0x11, 0xa9, 0x30, 0x78, 0xeb, 0xb1, 0x89, 0xa0, 0x62,
	0x9e, 0xc4, 0xac, 0xbf, 0x0c, 0x30, 0xbf, 0xf2, 0x67, 0x4c, 0x70, 0x7f, 0x8a, 0xbe, 0x3a, 0xe7,
	0xfe, 0x2d, 0x73, 0x43, 0x41, 0x15, 0xe3, 0x3e, 0x39, 0x81, 0x47, 0x98, 0xe5, 0x5e, 0xd3, 0x29,
	0x9a, 0xc6, 0xb1, 0x71, 0xd2, 0x18, 0x97, 0xc3, 0xc4, 0x82, 0xa6, 0x40, 0xc9, 0x43, 0x61, 0xe3,
	0x95, 0x47, 0x7d, 0x73, 0x23, 0x5e, 0x56, 0x88, 0x91, 0x03, 0xa8, 0x0b, 0x74, 0x19, 0xf7, 0xcd,
	0x5a, 0x9c, 0xd5, 0x5f, 0xa4, 0x03, 0xb5, 0x50, 0x78, 0xe6, 0x66, 0x1c, 0x8c, 0x7e, 0x92, 0x01,
	0xd4, 0xa5, 0xa2, 0x2a, 0x94, 0xe6, 0xd6, 0xb1, 0x71, 0xd2, 0x3e, 0x7d, 0xdc, 0x8f, 0xaa, 0xe9,
	0xe7, 0x78, 0x5e, 0xc7, 0xe9, 0xb1, 0x5e, 0x46, 0x3e, 0x86, 0x56, 0xf2, 0xeb, 0x12, 0xa5, 0xa4,
	0x2e, 0x9a, 0xf5, 0x18, 0xac, 0x18, 0xb4, 0xfe, 0x30, 0xc0, 0xbc, 0x09, 0x1c, 0xaa, 0x30, 0x87,
	0x34, 0xc6, 0x5f, 0x43, 0x94, 0xea, 0x5f, 0xae, 0x35, 0xab, 0xa0, 0xf6, 0xb0, 0x0a, 0xaa, 0x4d,
	0xa8, 0xd4, 0xb4, 0xb5, 0xac, 0xa6, 0x97, 0x40, 0xde, 0xa7, 0x18, 0xeb, 0x37, 0x03, 0xcc, 0x73,
	0x81, 0xff, 0x45, 0x4f, 0x56, 0xcc, 0xdf, 0xfa, 0x00, 0x0e, 0x5f, 0xa1, 0x87, 0x25, 0x06, 0x32,
	0xe0, 0xbe, 0x44, 0xeb, 0x0d, 0x1c, 0x24, 0x23, 0x1b, 0xce, 0x28, 0xf3, 0xe8, 0xc4, 0xc3, 0x94,
	0x5c, 0x1b, 0x36, 0xb8, 0xd4, 0x7c, 0x36, 0xb8, 0x24, 0x04, 0x36, 0xa9, 0xb0, 0xef, 0xf4, 0xd1,
	0xf1, 0x6f, 0x62, 0xc2, 0xf6, 0x0c, 0x85, 0xcc, 0xce, 0x4c, 0x3f, 0x2d, 0x1b, 0x1e, 0x57, 0x70,
	0x93, 0x23, 0xc9, 0x11, 0x34, 0x68, 0x1a, 0x8c, 0xf1, 0x77, 0xc6, 0x59, 0x20, 0x0f, 0xb9, 0x51,
	0x80, 0x4c, 0x47, 0x58, 0x5b, 0x8c, 0xd0, 0xfa, 0x19, 0xb6, 0xaf, 0x04, 0xff, 0x05, 0xed, 0x98,
	0x2d, 0x73, 0x52, 0xb6, 0xcc, 0x21, 0xc7, 0xb0, 0x9b, 0xeb, 0xa1, 0x86, 0xca, 0x87, 0xa2, 0x15,
	0x0e, 0x4a, 0x5b, 0xb0, 0x40, 0x65, 0xfc, 0xf3, 0x21, 0xeb, 0x05, 0x90, 0xef, 0x98, 0x54, 0xfa,
	0x88, 0xb4, 0x2f, 0x25, 0x64, 0xa3, 0x82, 0x6c, 0x29, 0xd8, 0x2b, 0xec, 0xd3, 0x75, 0x9b, 0xb0,
	0x2d, 0x43, 0xdb, 0x46, 0x29, 0x75, 0xd5, 0xe9, 0x67, 0x94, 0x99, 0x6a, 0x11, 0xea, 0x9a, 0xf5,
	0x27, 0x79, 0x0a, 0x3b, 0x41, 0x02, 0x13, 0x29, 0xbd, 0x76, 0xb2, 0x7b, 0xda, 0x4a, 0x94, 0x9e,
	0x82, 0x2f, 0xd2, 0xd6, 0x05, 0xb4, 0x87, 0x8e, 0x73, 0x23, 0x51, 0xa4, 0x4c, 0x7b, 0xb0, 0x13,
	0x4a, 0x14, 0x7e, 0xa6, 0xab, 0xc5, 0x77, 0x34, 0x04, 0xbd, 0xf3, 0x1b, 0x47, 0x1f, 0x9a, 0x05,
	0xac, 0xa7, 0xb0, 0xfb, 0x40, 0x20, 0xeb, 0x77, 0x03, 0x0e, 0x34, 0x99, 0x1f, 0x99, 0xba, 0xcb,
	0x69, 0x8c, 0x7c, 0x02, 0xdb, 0x1a, 0x32, 0xde, 0x55, 0xe1, 0x9e, 0x66, 0xc9, 0x97, 0xd5, 0x61,
	0xed, 0x9e, 0x7e, 0x54, 0xb9, 0xd2, 0x05, 0xf3, 0x2c, 0xb6, 0xfc, 0x0a, 0xc8, 0x25, 0x9f, 0x61,
	0x69, 0x54, 0x66, 0x91, 0x40, 0x23, 0x3b, 0x71, 0xad, 0x3c, 0xac, 0x27, 0xd0, 0x4a, 0xce, 0xcb,
	0xdd, 0x87, 0xbc, 0xc2, 0xac, 0x3e, 0xb4, 0xaf, 0xd1, 0x16, 0xa8, 0xf2, 0xc2, 0x96, 0x71, 0xe4,
	0x5b, 0x9c, 0xeb, 0x85, 0x59, 0xc0, 0xfa, 0xd3, 0x80, 0xce, 0x50, 0x4a, 0x26, 0x15, 0xcd, 0x1c,
	0xa0, 0x2c, 0x5b, 0x02, 0x9b, 0x71, 0x97, 0xf5, 0x25, 0x8b, 0x47, 0xb5, 0x56, 0xa8, 0xfa, 0x46,
	0x29, 0x2a, 0x6e, 0x16, 0x16, 0x97, 0x05, 0x48, 0x1f, 0x08, 0xf3, 0x15, 0xfa, 0xea, 0x15, 0x93,
	0x36, 0x9f, 0xa1, 0x98, 0x47, 0xcb, 0x12, 0xb7, 0x5b, 0x92, 0x21, 0x9f, 0x41, 0xd7, 0xc1, 0x49,
	0xe8, 0x16, 0x96, 0x27, 0x86, 0x5f, 0x4d, 0x7c, 0x3a, 0x82, 0x6e, 0xc5, 0x75, 0x49, 0x13, 0x76,
	0x62, 0xd3, 0x63, 0xbe, 0xdb, 0xf9, 0x1f, 0x69, 0xc0, 0xd6, 0x18, 0xa9, 0x33, 0xef, 0x18, 0x04,
	0xa0, 0xfe, 0x35, 0x65, 0x1e, 0x3a, 0x9d, 0x0d, 0xd2, 0x82, 0xc6, 0x4d, 0xe0, 0x0a, 0xea, 0x44,
	0xab, 0x6a, 0xa7, 0x7f, 0x37, 0x60, 0x3f, 0x87, 0x74, 0x49, 0x7d, 0xea, 0x62, 0xac, 0xa3, 0x01,
	0x6c, 0x5e, 0x31, 0xdf, 0x25, 0x44, 0x2b, 0x62, 0x1a, 0xa8, 0xb9, 0xf6, 0xe7, 0xde, 0x5e, 0x12,
	0x3b, 0xa3, 0x92, 0xd9, 0x8b, 0x41, 0x5c, 0x43, 0xb7, 0xe2, 0xb9, 0x44, 0xeb, 0x69, 0x95, 0x19,
	0xf7, 0xd6, 0xe8, 0x8d, 0xbc, 0x86, 0x6e, 0xc5, 0x46, 0x89, 0x59, 0xd9, 0x94, 0xc2, 0x3d, 0x49,
	0x32, 0x2b, 0x9d, 0x37, 0x22, 0x59, 0x79, 0x2c, 0x53, 0x92, 0xab, 0x5e, 0xd1, 0xb5, 0x24, 0x2f,
	0xa0, 0x3d, 0x42, 0xf5, 0x30, 0x86, 0xeb, 0x0b, 0x7e, 0x54, 0xb2, 0x70, 0x72, 0x94, 0xa7, 0x57,
	0x7e, 0x31, 0x7a, 0x1f, 0xae, 0xc8, 0xea, 0x82, 0x9f, 0x43, 0x2b, 0x69, 0x7e, 0xea, 0xd9, 0x45,
	0x3b, 0x58, 0x3e, 0xca, 0x67, 0x00, 0x23, 0x4c, 0xad, 0x94, 0xfc, 0xbf, 0x68, 0x20, 0xfa, 0xdc,
	0x22, 0x0e, 0xf9, 0x1e, 0x0e, 0xb3, 0x2d, 0x65, 0x4f, 0x5a, 0x8e, 0x70, 0x54, 0x88, 0x96, 0xf7,
	0x7c, 0x01, 0x1d, 0xed, 0xac, 0x3f, 0xf0, 0x12, 0x93, 0xa2, 0xe3, 0x2e, 0x2f, 0xe1, 0x05, 0x34,
	0x87, 0x8e, 0x73, 0x1d, 0x06, 0x28, 0xa2, 0xb5, 0xa4, 0xab, 0xdb, 0xb4, 0x6e, 0xdf, 0x39, 0x34,
	0x73, 0xcf, 0x88, 0x4c, 0x27, 0x59, 0x7d, 0x92, 0x7a, 0x87, 0x4b, 0x32, 0x1a, 0xe4, 0x25, 0x74,
	0xb2, 0x66, 0x24, 0x7e, 0xb5, 0xa2, 0x07, 0x3a, 0x5a, 0xf2, 0xb4, 0x21, 0xec, 0x25, 0xf3, 0x7c,
	0x1f, 0x08, 0x32, 0x42, 0xb5, 0xb0, 0xbe, 0x44, 0x64, 0x44, 0x97, 0x5c, 0xf0, 0xd8, 0xde, 0x81,
	0xee, 0x6a, 0xd9, 0x26, 0x47, 0xb0, 0xaf, 0x55, 0x55, 0x42, 0x59, 0xb1, 0x61, 0x25, 0xd0, 0x19,
	0xec, 0xbf, 0xa1, 0x1e, 0xcb, 0x15, 0x34, 0x4c, 0x9e, 0xe0, 0xe5, 0x05, 0x2d, 0x9d, 0xcb, 0x05,
	0x1c, 0xa6, 0x18, 0x39, 0x95, 0x68, 0x9c, 0xd5, 0xd7, 0x6d, 0x19, 0xd6, 0xd9, 0xb3, 0x9f, 0x06,
	0x2e, 0x53, 0x77, 0xe1, 0xa4, 0x6f, 0xf3, 0xe9, 0x80, 0x06, 0x81, 0x12, 0x88, 0x92, 0xdf, 0xaa,
	0x7b, 0x2a, 0x70, 0xe0, 0xf2, 0xcf, 0xef, 0xb9, 0x78, 0x77, 0xeb, 0xf1, 0xfb, 0x41, 0xf0, 0xce,
	0x1d, 0x44, 0x00, 0x93, 0x7a, 0xfc, 0xc7, 0xe2, 0xf9, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d,
	0xa0, 0x2c, 0xc6, 0x96, 0x0c, 0x00, 0x00,
}
