// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workflow_api.proto

package core // import "github.com/apptreesoftware/go-workflow/pkg/core"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProjectWorkflowRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workflow             string   `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ProjectWorkflowRequest) Reset()         { *m = ProjectWorkflowRequest{} }
func (m *ProjectWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectWorkflowRequest) ProtoMessage()    {}
func (*ProjectWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{0}
}
func (m *ProjectWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectWorkflowRequest.Unmarshal(m, b)
}
func (m *ProjectWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *ProjectWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectWorkflowRequest.Merge(dst, src)
}
func (m *ProjectWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectWorkflowRequest.Size(m)
}
func (m *ProjectWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectWorkflowRequest proto.InternalMessageInfo

func (m *ProjectWorkflowRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ProjectWorkflowRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

type StoreValueRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Project              string   `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	IsSecret             bool     `protobuf:"varint,4,opt,name=isSecret,proto3" json:"isSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *StoreValueRequest) Reset()         { *m = StoreValueRequest{} }
func (m *StoreValueRequest) String() string { return proto.CompactTextString(m) }
func (*StoreValueRequest) ProtoMessage()    {}
func (*StoreValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{1}
}
func (m *StoreValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreValueRequest.Unmarshal(m, b)
}
func (m *StoreValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreValueRequest.Marshal(b, m, deterministic)
}
func (dst *StoreValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreValueRequest.Merge(dst, src)
}
func (m *StoreValueRequest) XXX_Size() int {
	return xxx_messageInfo_StoreValueRequest.Size(m)
}
func (m *StoreValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreValueRequest proto.InternalMessageInfo

func (m *StoreValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StoreValueRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *StoreValueRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *StoreValueRequest) GetIsSecret() bool {
	if m != nil {
		return m.IsSecret
	}
	return false
}

type DeleteValueRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *DeleteValueRequest) Reset()         { *m = DeleteValueRequest{} }
func (m *DeleteValueRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteValueRequest) ProtoMessage()    {}
func (*DeleteValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{2}
}
func (m *DeleteValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteValueRequest.Unmarshal(m, b)
}
func (m *DeleteValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteValueRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteValueRequest.Merge(dst, src)
}
func (m *DeleteValueRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteValueRequest.Size(m)
}
func (m *DeleteValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteValueRequest proto.InternalMessageInfo

func (m *DeleteValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeleteValueRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type SingleValueResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *SingleValueResponse) Reset()         { *m = SingleValueResponse{} }
func (m *SingleValueResponse) String() string { return proto.CompactTextString(m) }
func (*SingleValueResponse) ProtoMessage()    {}
func (*SingleValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{3}
}
func (m *SingleValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleValueResponse.Unmarshal(m, b)
}
func (m *SingleValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleValueResponse.Marshal(b, m, deterministic)
}
func (dst *SingleValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleValueResponse.Merge(dst, src)
}
func (m *SingleValueResponse) XXX_Size() int {
	return xxx_messageInfo_SingleValueResponse.Size(m)
}
func (m *SingleValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SingleValueResponse proto.InternalMessageInfo

func (m *SingleValueResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ValueResponse struct {
	Values               map[string]string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ValueResponse) Reset()         { *m = ValueResponse{} }
func (m *ValueResponse) String() string { return proto.CompactTextString(m) }
func (*ValueResponse) ProtoMessage()    {}
func (*ValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{4}
}
func (m *ValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueResponse.Unmarshal(m, b)
}
func (m *ValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueResponse.Marshal(b, m, deterministic)
}
func (dst *ValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueResponse.Merge(dst, src)
}
func (m *ValueResponse) XXX_Size() int {
	return xxx_messageInfo_ValueResponse.Size(m)
}
func (m *ValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValueResponse proto.InternalMessageInfo

func (m *ValueResponse) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type ProjectValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Project              string   `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	IsEncrypted          bool     `protobuf:"varint,4,opt,name=isEncrypted,proto3" json:"isEncrypted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ProjectValue) Reset()         { *m = ProjectValue{} }
func (m *ProjectValue) String() string { return proto.CompactTextString(m) }
func (*ProjectValue) ProtoMessage()    {}
func (*ProjectValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{5}
}
func (m *ProjectValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectValue.Unmarshal(m, b)
}
func (m *ProjectValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectValue.Marshal(b, m, deterministic)
}
func (dst *ProjectValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectValue.Merge(dst, src)
}
func (m *ProjectValue) XXX_Size() int {
	return xxx_messageInfo_ProjectValue.Size(m)
}
func (m *ProjectValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectValue.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectValue proto.InternalMessageInfo

func (m *ProjectValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ProjectValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ProjectValue) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ProjectValue) GetIsEncrypted() bool {
	if m != nil {
		return m.IsEncrypted
	}
	return false
}

type WorkflowHistoryRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workflow             string   `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	JobId                string   `protobuf:"bytes,5,opt,name=jobId,proto3" json:"jobId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *WorkflowHistoryRequest) Reset()         { *m = WorkflowHistoryRequest{} }
func (m *WorkflowHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*WorkflowHistoryRequest) ProtoMessage()    {}
func (*WorkflowHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{6}
}
func (m *WorkflowHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowHistoryRequest.Unmarshal(m, b)
}
func (m *WorkflowHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowHistoryRequest.Marshal(b, m, deterministic)
}
func (dst *WorkflowHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowHistoryRequest.Merge(dst, src)
}
func (m *WorkflowHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_WorkflowHistoryRequest.Size(m)
}
func (m *WorkflowHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowHistoryRequest proto.InternalMessageInfo

func (m *WorkflowHistoryRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *WorkflowHistoryRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func (m *WorkflowHistoryRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *WorkflowHistoryRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *WorkflowHistoryRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type WorkflowHistoryResponse struct {
	Items                []*WorkflowHistory `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte             `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32              `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *WorkflowHistoryResponse) Reset()         { *m = WorkflowHistoryResponse{} }
func (m *WorkflowHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*WorkflowHistoryResponse) ProtoMessage()    {}
func (*WorkflowHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{7}
}
func (m *WorkflowHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowHistoryResponse.Unmarshal(m, b)
}
func (m *WorkflowHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowHistoryResponse.Marshal(b, m, deterministic)
}
func (dst *WorkflowHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowHistoryResponse.Merge(dst, src)
}
func (m *WorkflowHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_WorkflowHistoryResponse.Size(m)
}
func (m *WorkflowHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowHistoryResponse proto.InternalMessageInfo

func (m *WorkflowHistoryResponse) GetItems() []*WorkflowHistory {
	if m != nil {
		return m.Items
	}
	return nil
}

type WorkflowHistory struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Start                int64    `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	Duration             float64  `protobuf:"fixed64,5,opt,name=duration,proto3" json:"duration,omitempty"`
	FailureReason        string   `protobuf:"bytes,6,opt,name=failureReason,proto3" json:"failureReason,omitempty"`
	Project              string   `protobuf:"bytes,7,opt,name=project,proto3" json:"project,omitempty"`
	Workflow             string   `protobuf:"bytes,8,opt,name=workflow,proto3" json:"workflow,omitempty"`
	TriggerType          string   `protobuf:"bytes,9,opt,name=triggerType,proto3" json:"triggerType,omitempty"`
	ParentItem           string   `protobuf:"bytes,10,opt,name=parentItem,proto3" json:"parentItem,omitempty"`
	Input                string   `protobuf:"bytes,11,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *WorkflowHistory) Reset()         { *m = WorkflowHistory{} }
func (m *WorkflowHistory) String() string { return proto.CompactTextString(m) }
func (*WorkflowHistory) ProtoMessage()    {}
func (*WorkflowHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{8}
}
func (m *WorkflowHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowHistory.Unmarshal(m, b)
}
func (m *WorkflowHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowHistory.Marshal(b, m, deterministic)
}
func (dst *WorkflowHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowHistory.Merge(dst, src)
}
func (m *WorkflowHistory) XXX_Size() int {
	return xxx_messageInfo_WorkflowHistory.Size(m)
}
func (m *WorkflowHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowHistory.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowHistory proto.InternalMessageInfo

func (m *WorkflowHistory) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkflowHistory) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *WorkflowHistory) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *WorkflowHistory) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *WorkflowHistory) GetDuration() float64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *WorkflowHistory) GetFailureReason() string {
	if m != nil {
		return m.FailureReason
	}
	return ""
}

func (m *WorkflowHistory) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *WorkflowHistory) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func (m *WorkflowHistory) GetTriggerType() string {
	if m != nil {
		return m.TriggerType
	}
	return ""
}

func (m *WorkflowHistory) GetParentItem() string {
	if m != nil {
		return m.ParentItem
	}
	return ""
}

func (m *WorkflowHistory) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type RemoteEngineUpdateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	ForceUpdate          bool     `protobuf:"varint,3,opt,name=forceUpdate,proto3" json:"forceUpdate,omitempty"`
	WaitForVersion       bool     `protobuf:"varint,4,opt,name=waitForVersion,proto3" json:"waitForVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RemoteEngineUpdateRequest) Reset()         { *m = RemoteEngineUpdateRequest{} }
func (m *RemoteEngineUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*RemoteEngineUpdateRequest) ProtoMessage()    {}
func (*RemoteEngineUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{9}
}
func (m *RemoteEngineUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteEngineUpdateRequest.Unmarshal(m, b)
}
func (m *RemoteEngineUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteEngineUpdateRequest.Marshal(b, m, deterministic)
}
func (dst *RemoteEngineUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteEngineUpdateRequest.Merge(dst, src)
}
func (m *RemoteEngineUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_RemoteEngineUpdateRequest.Size(m)
}
func (m *RemoteEngineUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteEngineUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteEngineUpdateRequest proto.InternalMessageInfo

func (m *RemoteEngineUpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoteEngineUpdateRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *RemoteEngineUpdateRequest) GetForceUpdate() bool {
	if m != nil {
		return m.ForceUpdate
	}
	return false
}

func (m *RemoteEngineUpdateRequest) GetWaitForVersion() bool {
	if m != nil {
		return m.WaitForVersion
	}
	return false
}

type RemoteEngineUpdateResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Os                   string   `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch                 string   `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RemoteEngineUpdateResponse) Reset()         { *m = RemoteEngineUpdateResponse{} }
func (m *RemoteEngineUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*RemoteEngineUpdateResponse) ProtoMessage()    {}
func (*RemoteEngineUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{10}
}
func (m *RemoteEngineUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteEngineUpdateResponse.Unmarshal(m, b)
}
func (m *RemoteEngineUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteEngineUpdateResponse.Marshal(b, m, deterministic)
}
func (dst *RemoteEngineUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteEngineUpdateResponse.Merge(dst, src)
}
func (m *RemoteEngineUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_RemoteEngineUpdateResponse.Size(m)
}
func (m *RemoteEngineUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteEngineUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteEngineUpdateResponse proto.InternalMessageInfo

func (m *RemoteEngineUpdateResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *RemoteEngineUpdateResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RemoteEngineUpdateResponse) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *RemoteEngineUpdateResponse) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

type RemoteEngineHealthRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RemoteEngineHealthRequest) Reset()         { *m = RemoteEngineHealthRequest{} }
func (m *RemoteEngineHealthRequest) String() string { return proto.CompactTextString(m) }
func (*RemoteEngineHealthRequest) ProtoMessage()    {}
func (*RemoteEngineHealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{11}
}
func (m *RemoteEngineHealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteEngineHealthRequest.Unmarshal(m, b)
}
func (m *RemoteEngineHealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteEngineHealthRequest.Marshal(b, m, deterministic)
}
func (dst *RemoteEngineHealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteEngineHealthRequest.Merge(dst, src)
}
func (m *RemoteEngineHealthRequest) XXX_Size() int {
	return xxx_messageInfo_RemoteEngineHealthRequest.Size(m)
}
func (m *RemoteEngineHealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteEngineHealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteEngineHealthRequest proto.InternalMessageInfo

func (m *RemoteEngineHealthRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoteEngineHealthRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type RemoteEngineHealthResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Os                   string   `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch                 string   `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RemoteEngineHealthResponse) Reset()         { *m = RemoteEngineHealthResponse{} }
func (m *RemoteEngineHealthResponse) String() string { return proto.CompactTextString(m) }
func (*RemoteEngineHealthResponse) ProtoMessage()    {}
func (*RemoteEngineHealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{12}
}
func (m *RemoteEngineHealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteEngineHealthResponse.Unmarshal(m, b)
}
func (m *RemoteEngineHealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteEngineHealthResponse.Marshal(b, m, deterministic)
}
func (dst *RemoteEngineHealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteEngineHealthResponse.Merge(dst, src)
}
func (m *RemoteEngineHealthResponse) XXX_Size() int {
	return xxx_messageInfo_RemoteEngineHealthResponse.Size(m)
}
func (m *RemoteEngineHealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteEngineHealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteEngineHealthResponse proto.InternalMessageInfo

func (m *RemoteEngineHealthResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *RemoteEngineHealthResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RemoteEngineHealthResponse) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *RemoteEngineHealthResponse) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

type ListRemoteEnginesResponse struct {
	Engines              []*RemoteEngine `protobuf:"bytes,1,rep,name=engines,proto3" json:"engines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte          `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32           `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ListRemoteEnginesResponse) Reset()         { *m = ListRemoteEnginesResponse{} }
func (m *ListRemoteEnginesResponse) String() string { return proto.CompactTextString(m) }
func (*ListRemoteEnginesResponse) ProtoMessage()    {}
func (*ListRemoteEnginesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{13}
}
func (m *ListRemoteEnginesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRemoteEnginesResponse.Unmarshal(m, b)
}
func (m *ListRemoteEnginesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRemoteEnginesResponse.Marshal(b, m, deterministic)
}
func (dst *ListRemoteEnginesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRemoteEnginesResponse.Merge(dst, src)
}
func (m *ListRemoteEnginesResponse) XXX_Size() int {
	return xxx_messageInfo_ListRemoteEnginesResponse.Size(m)
}
func (m *ListRemoteEnginesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRemoteEnginesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRemoteEnginesResponse proto.InternalMessageInfo

func (m *ListRemoteEnginesResponse) GetEngines() []*RemoteEngine {
	if m != nil {
		return m.Engines
	}
	return nil
}

type RemoteEngine struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Cert                 []byte   `protobuf:"bytes,4,opt,name=cert,proto3" json:"cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RemoteEngine) Reset()         { *m = RemoteEngine{} }
func (m *RemoteEngine) String() string { return proto.CompactTextString(m) }
func (*RemoteEngine) ProtoMessage()    {}
func (*RemoteEngine) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{14}
}
func (m *RemoteEngine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteEngine.Unmarshal(m, b)
}
func (m *RemoteEngine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteEngine.Marshal(b, m, deterministic)
}
func (dst *RemoteEngine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteEngine.Merge(dst, src)
}
func (m *RemoteEngine) XXX_Size() int {
	return xxx_messageInfo_RemoteEngine.Size(m)
}
func (m *RemoteEngine) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteEngine.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteEngine proto.InternalMessageInfo

func (m *RemoteEngine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoteEngine) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *RemoteEngine) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *RemoteEngine) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

type RemoteEngineRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Engine               string   `protobuf:"bytes,2,opt,name=engine,proto3" json:"engine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RemoteEngineRequest) Reset()         { *m = RemoteEngineRequest{} }
func (m *RemoteEngineRequest) String() string { return proto.CompactTextString(m) }
func (*RemoteEngineRequest) ProtoMessage()    {}
func (*RemoteEngineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{15}
}
func (m *RemoteEngineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteEngineRequest.Unmarshal(m, b)
}
func (m *RemoteEngineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteEngineRequest.Marshal(b, m, deterministic)
}
func (dst *RemoteEngineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteEngineRequest.Merge(dst, src)
}
func (m *RemoteEngineRequest) XXX_Size() int {
	return xxx_messageInfo_RemoteEngineRequest.Size(m)
}
func (m *RemoteEngineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteEngineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteEngineRequest proto.InternalMessageInfo

func (m *RemoteEngineRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *RemoteEngineRequest) GetEngine() string {
	if m != nil {
		return m.Engine
	}
	return ""
}

type RegisterRemoteEngineRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	ClientCert           []byte   `protobuf:"bytes,3,opt,name=clientCert,proto3" json:"clientCert,omitempty"`
	ApiKey               string   `protobuf:"bytes,4,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Project              string   `protobuf:"bytes,5,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RegisterRemoteEngineRequest) Reset()         { *m = RegisterRemoteEngineRequest{} }
func (m *RegisterRemoteEngineRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRemoteEngineRequest) ProtoMessage()    {}
func (*RegisterRemoteEngineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{16}
}
func (m *RegisterRemoteEngineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRemoteEngineRequest.Unmarshal(m, b)
}
func (m *RegisterRemoteEngineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRemoteEngineRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRemoteEngineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRemoteEngineRequest.Merge(dst, src)
}
func (m *RegisterRemoteEngineRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRemoteEngineRequest.Size(m)
}
func (m *RegisterRemoteEngineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRemoteEngineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRemoteEngineRequest proto.InternalMessageInfo

func (m *RegisterRemoteEngineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRemoteEngineRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *RegisterRemoteEngineRequest) GetClientCert() []byte {
	if m != nil {
		return m.ClientCert
	}
	return nil
}

func (m *RegisterRemoteEngineRequest) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *RegisterRemoteEngineRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type ProjectValueRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ProjectValueRequest) Reset()         { *m = ProjectValueRequest{} }
func (m *ProjectValueRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectValueRequest) ProtoMessage()    {}
func (*ProjectValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{17}
}
func (m *ProjectValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectValueRequest.Unmarshal(m, b)
}
func (m *ProjectValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectValueRequest.Marshal(b, m, deterministic)
}
func (dst *ProjectValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectValueRequest.Merge(dst, src)
}
func (m *ProjectValueRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectValueRequest.Size(m)
}
func (m *ProjectValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectValueRequest proto.InternalMessageInfo

func (m *ProjectValueRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ProjectValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ProjectValuesRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Decrypt              bool     `protobuf:"varint,2,opt,name=decrypt,proto3" json:"decrypt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ProjectValuesRequest) Reset()         { *m = ProjectValuesRequest{} }
func (m *ProjectValuesRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectValuesRequest) ProtoMessage()    {}
func (*ProjectValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{18}
}
func (m *ProjectValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectValuesRequest.Unmarshal(m, b)
}
func (m *ProjectValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectValuesRequest.Marshal(b, m, deterministic)
}
func (dst *ProjectValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectValuesRequest.Merge(dst, src)
}
func (m *ProjectValuesRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectValuesRequest.Size(m)
}
func (m *ProjectValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectValuesRequest proto.InternalMessageInfo

func (m *ProjectValuesRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ProjectValuesRequest) GetDecrypt() bool {
	if m != nil {
		return m.Decrypt
	}
	return false
}

type ListWorkflowResponse struct {
	Workflows            []*WorkflowOverview `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte              `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32               `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ListWorkflowResponse) Reset()         { *m = ListWorkflowResponse{} }
func (m *ListWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*ListWorkflowResponse) ProtoMessage()    {}
func (*ListWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{19}
}
func (m *ListWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWorkflowResponse.Unmarshal(m, b)
}
func (m *ListWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *ListWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWorkflowResponse.Merge(dst, src)
}
func (m *ListWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_ListWorkflowResponse.Size(m)
}
func (m *ListWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListWorkflowResponse proto.InternalMessageInfo

func (m *ListWorkflowResponse) GetWorkflows() []*WorkflowOverview {
	if m != nil {
		return m.Workflows
	}
	return nil
}

type WorkflowOverview struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Dependencies         string   `protobuf:"bytes,3,opt,name=dependencies,proto3" json:"dependencies,omitempty"`
	Triggers             string   `protobuf:"bytes,4,opt,name=triggers,proto3" json:"triggers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *WorkflowOverview) Reset()         { *m = WorkflowOverview{} }
func (m *WorkflowOverview) String() string { return proto.CompactTextString(m) }
func (*WorkflowOverview) ProtoMessage()    {}
func (*WorkflowOverview) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{20}
}
func (m *WorkflowOverview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowOverview.Unmarshal(m, b)
}
func (m *WorkflowOverview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowOverview.Marshal(b, m, deterministic)
}
func (dst *WorkflowOverview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowOverview.Merge(dst, src)
}
func (m *WorkflowOverview) XXX_Size() int {
	return xxx_messageInfo_WorkflowOverview.Size(m)
}
func (m *WorkflowOverview) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowOverview.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowOverview proto.InternalMessageInfo

func (m *WorkflowOverview) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkflowOverview) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *WorkflowOverview) GetDependencies() string {
	if m != nil {
		return m.Dependencies
	}
	return ""
}

func (m *WorkflowOverview) GetTriggers() string {
	if m != nil {
		return m.Triggers
	}
	return ""
}

type RunWorkflowRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	WorkflowId           string   `protobuf:"bytes,2,opt,name=workflowId,proto3" json:"workflowId,omitempty"`
	TriggerBody          []byte   `protobuf:"bytes,3,opt,name=triggerBody,proto3" json:"triggerBody,omitempty"`
	Count                int64    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RunWorkflowRequest) Reset()         { *m = RunWorkflowRequest{} }
func (m *RunWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*RunWorkflowRequest) ProtoMessage()    {}
func (*RunWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{21}
}
func (m *RunWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunWorkflowRequest.Unmarshal(m, b)
}
func (m *RunWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *RunWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunWorkflowRequest.Merge(dst, src)
}
func (m *RunWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_RunWorkflowRequest.Size(m)
}
func (m *RunWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunWorkflowRequest proto.InternalMessageInfo

func (m *RunWorkflowRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *RunWorkflowRequest) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

func (m *RunWorkflowRequest) GetTriggerBody() []byte {
	if m != nil {
		return m.TriggerBody
	}
	return nil
}

func (m *RunWorkflowRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RetryWorkflowRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workflow             string   `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	FromDate             int64    `protobuf:"varint,3,opt,name=fromDate,proto3" json:"fromDate,omitempty"`
	ToDate               int64    `protobuf:"varint,4,opt,name=toDate,proto3" json:"toDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RetryWorkflowRequest) Reset()         { *m = RetryWorkflowRequest{} }
func (m *RetryWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*RetryWorkflowRequest) ProtoMessage()    {}
func (*RetryWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{22}
}
func (m *RetryWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryWorkflowRequest.Unmarshal(m, b)
}
func (m *RetryWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *RetryWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryWorkflowRequest.Merge(dst, src)
}
func (m *RetryWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_RetryWorkflowRequest.Size(m)
}
func (m *RetryWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetryWorkflowRequest proto.InternalMessageInfo

func (m *RetryWorkflowRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *RetryWorkflowRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func (m *RetryWorkflowRequest) GetFromDate() int64 {
	if m != nil {
		return m.FromDate
	}
	return 0
}

func (m *RetryWorkflowRequest) GetToDate() int64 {
	if m != nil {
		return m.ToDate
	}
	return 0
}

type RetryWorkflowResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	JobIds               []string `protobuf:"bytes,2,rep,name=jobIds,proto3" json:"jobIds,omitempty"`
	Errors               []string `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RetryWorkflowResponse) Reset()         { *m = RetryWorkflowResponse{} }
func (m *RetryWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*RetryWorkflowResponse) ProtoMessage()    {}
func (*RetryWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{23}
}
func (m *RetryWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryWorkflowResponse.Unmarshal(m, b)
}
func (m *RetryWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *RetryWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryWorkflowResponse.Merge(dst, src)
}
func (m *RetryWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_RetryWorkflowResponse.Size(m)
}
func (m *RetryWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetryWorkflowResponse proto.InternalMessageInfo

func (m *RetryWorkflowResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *RetryWorkflowResponse) GetJobIds() []string {
	if m != nil {
		return m.JobIds
	}
	return nil
}

func (m *RetryWorkflowResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type RetryJobRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	JobId                string   `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *RetryJobRequest) Reset()         { *m = RetryJobRequest{} }
func (m *RetryJobRequest) String() string { return proto.CompactTextString(m) }
func (*RetryJobRequest) ProtoMessage()    {}
func (*RetryJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{24}
}
func (m *RetryJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryJobRequest.Unmarshal(m, b)
}
func (m *RetryJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryJobRequest.Marshal(b, m, deterministic)
}
func (dst *RetryJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryJobRequest.Merge(dst, src)
}
func (m *RetryJobRequest) XXX_Size() int {
	return xxx_messageInfo_RetryJobRequest.Size(m)
}
func (m *RetryJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetryJobRequest proto.InternalMessageInfo

func (m *RetryJobRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *RetryJobRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type PublishWorkflowRequest struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *PublishWorkflowRequest) Reset()         { *m = PublishWorkflowRequest{} }
func (m *PublishWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*PublishWorkflowRequest) ProtoMessage()    {}
func (*PublishWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{25}
}
func (m *PublishWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishWorkflowRequest.Unmarshal(m, b)
}
func (m *PublishWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *PublishWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishWorkflowRequest.Merge(dst, src)
}
func (m *PublishWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_PublishWorkflowRequest.Size(m)
}
func (m *PublishWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishWorkflowRequest proto.InternalMessageInfo

func (m *PublishWorkflowRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *PublishWorkflowRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ProjectId            string   `protobuf:"bytes,2,opt,name=projectId,proto3" json:"projectId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{26}
}
func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (dst *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(dst, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddUserRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type QueueItem struct {
	Project              string            `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workflow             string            `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	RunContext           map[string]string `protobuf:"bytes,3,rep,name=runContext,proto3" json:"runContext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Running              bool              `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	CreatedOn            string            `protobuf:"bytes,5,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	TriggeredBy          string            `protobuf:"bytes,6,opt,name=triggeredBy,proto3" json:"triggeredBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *QueueItem) Reset()         { *m = QueueItem{} }
func (m *QueueItem) String() string { return proto.CompactTextString(m) }
func (*QueueItem) ProtoMessage()    {}
func (*QueueItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{27}
}
func (m *QueueItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueItem.Unmarshal(m, b)
}
func (m *QueueItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueItem.Marshal(b, m, deterministic)
}
func (dst *QueueItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueItem.Merge(dst, src)
}
func (m *QueueItem) XXX_Size() int {
	return xxx_messageInfo_QueueItem.Size(m)
}
func (m *QueueItem) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueItem.DiscardUnknown(m)
}

var xxx_messageInfo_QueueItem proto.InternalMessageInfo

func (m *QueueItem) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *QueueItem) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func (m *QueueItem) GetRunContext() map[string]string {
	if m != nil {
		return m.RunContext
	}
	return nil
}

func (m *QueueItem) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

func (m *QueueItem) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *QueueItem) GetTriggeredBy() string {
	if m != nil {
		return m.TriggeredBy
	}
	return ""
}

type QueueResponse struct {
	Success              bool         `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RecordCount          int64        `protobuf:"varint,3,opt,name=recordCount,proto3" json:"recordCount,omitempty"`
	Items                []*QueueItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte       `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32        `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *QueueResponse) Reset()         { *m = QueueResponse{} }
func (m *QueueResponse) String() string { return proto.CompactTextString(m) }
func (*QueueResponse) ProtoMessage()    {}
func (*QueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{28}
}
func (m *QueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueResponse.Unmarshal(m, b)
}
func (m *QueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueResponse.Marshal(b, m, deterministic)
}
func (dst *QueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueResponse.Merge(dst, src)
}
func (m *QueueResponse) XXX_Size() int {
	return xxx_messageInfo_QueueResponse.Size(m)
}
func (m *QueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueueResponse proto.InternalMessageInfo

func (m *QueueResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *QueueResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueueResponse) GetRecordCount() int64 {
	if m != nil {
		return m.RecordCount
	}
	return 0
}

func (m *QueueResponse) GetItems() []*QueueItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type ViewQueueRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workflow             string   `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	TriggerType          string   `protobuf:"bytes,3,opt,name=triggerType,proto3" json:"triggerType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ViewQueueRequest) Reset()         { *m = ViewQueueRequest{} }
func (m *ViewQueueRequest) String() string { return proto.CompactTextString(m) }
func (*ViewQueueRequest) ProtoMessage()    {}
func (*ViewQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{29}
}
func (m *ViewQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewQueueRequest.Unmarshal(m, b)
}
func (m *ViewQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewQueueRequest.Marshal(b, m, deterministic)
}
func (dst *ViewQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewQueueRequest.Merge(dst, src)
}
func (m *ViewQueueRequest) XXX_Size() int {
	return xxx_messageInfo_ViewQueueRequest.Size(m)
}
func (m *ViewQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewQueueRequest proto.InternalMessageInfo

func (m *ViewQueueRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ViewQueueRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func (m *ViewQueueRequest) GetTriggerType() string {
	if m != nil {
		return m.TriggerType
	}
	return ""
}

type ViewLogRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	JobId                string   `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	LogLevel             string   `protobuf:"bytes,3,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ViewLogRequest) Reset()         { *m = ViewLogRequest{} }
func (m *ViewLogRequest) String() string { return proto.CompactTextString(m) }
func (*ViewLogRequest) ProtoMessage()    {}
func (*ViewLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{30}
}
func (m *ViewLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewLogRequest.Unmarshal(m, b)
}
func (m *ViewLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewLogRequest.Marshal(b, m, deterministic)
}
func (dst *ViewLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewLogRequest.Merge(dst, src)
}
func (m *ViewLogRequest) XXX_Size() int {
	return xxx_messageInfo_ViewLogRequest.Size(m)
}
func (m *ViewLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewLogRequest proto.InternalMessageInfo

func (m *ViewLogRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ViewLogRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ViewLogRequest) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

type Log struct {
	LogLevel             string   `protobuf:"bytes,1,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{31}
}
func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (dst *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(dst, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

func (m *Log) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Log) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type ViewLogResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ViewLogResponse) Reset()         { *m = ViewLogResponse{} }
func (m *ViewLogResponse) String() string { return proto.CompactTextString(m) }
func (*ViewLogResponse) ProtoMessage()    {}
func (*ViewLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{32}
}
func (m *ViewLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewLogResponse.Unmarshal(m, b)
}
func (m *ViewLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewLogResponse.Marshal(b, m, deterministic)
}
func (dst *ViewLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewLogResponse.Merge(dst, src)
}
func (m *ViewLogResponse) XXX_Size() int {
	return xxx_messageInfo_ViewLogResponse.Size(m)
}
func (m *ViewLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ViewLogResponse proto.InternalMessageInfo

func (m *ViewLogResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ViewLogResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ViewLogResponse) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type ViewJobDetailRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Job                  string   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ViewJobDetailRequest) Reset()         { *m = ViewJobDetailRequest{} }
func (m *ViewJobDetailRequest) String() string { return proto.CompactTextString(m) }
func (*ViewJobDetailRequest) ProtoMessage()    {}
func (*ViewJobDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{33}
}
func (m *ViewJobDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewJobDetailRequest.Unmarshal(m, b)
}
func (m *ViewJobDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewJobDetailRequest.Marshal(b, m, deterministic)
}
func (dst *ViewJobDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewJobDetailRequest.Merge(dst, src)
}
func (m *ViewJobDetailRequest) XXX_Size() int {
	return xxx_messageInfo_ViewJobDetailRequest.Size(m)
}
func (m *ViewJobDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewJobDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewJobDetailRequest proto.InternalMessageInfo

func (m *ViewJobDetailRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ViewJobDetailRequest) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

type ViewJobDetailResponse struct {
	Success              bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	JobDetail            *JobDetail `protobuf:"bytes,3,opt,name=jobDetail,proto3" json:"jobDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte     `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32      `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *ViewJobDetailResponse) Reset()         { *m = ViewJobDetailResponse{} }
func (m *ViewJobDetailResponse) String() string { return proto.CompactTextString(m) }
func (*ViewJobDetailResponse) ProtoMessage()    {}
func (*ViewJobDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{34}
}
func (m *ViewJobDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewJobDetailResponse.Unmarshal(m, b)
}
func (m *ViewJobDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewJobDetailResponse.Marshal(b, m, deterministic)
}
func (dst *ViewJobDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewJobDetailResponse.Merge(dst, src)
}
func (m *ViewJobDetailResponse) XXX_Size() int {
	return xxx_messageInfo_ViewJobDetailResponse.Size(m)
}
func (m *ViewJobDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewJobDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ViewJobDetailResponse proto.InternalMessageInfo

func (m *ViewJobDetailResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ViewJobDetailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ViewJobDetailResponse) GetJobDetail() *JobDetail {
	if m != nil {
		return m.JobDetail
	}
	return nil
}

type JobDetail struct {
	StartTime            string            `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string            `protobuf:"bytes,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Duration             float64           `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Storage              map[string]string `protobuf:"bytes,4,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StepResults          []*StepResult     `protobuf:"bytes,5,rep,name=stepResults,proto3" json:"stepResults,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *JobDetail) Reset()         { *m = JobDetail{} }
func (m *JobDetail) String() string { return proto.CompactTextString(m) }
func (*JobDetail) ProtoMessage()    {}
func (*JobDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{35}
}
func (m *JobDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobDetail.Unmarshal(m, b)
}
func (m *JobDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobDetail.Marshal(b, m, deterministic)
}
func (dst *JobDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobDetail.Merge(dst, src)
}
func (m *JobDetail) XXX_Size() int {
	return xxx_messageInfo_JobDetail.Size(m)
}
func (m *JobDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_JobDetail.DiscardUnknown(m)
}

var xxx_messageInfo_JobDetail proto.InternalMessageInfo

func (m *JobDetail) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *JobDetail) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *JobDetail) GetDuration() float64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *JobDetail) GetStorage() map[string]string {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *JobDetail) GetStepResults() []*StepResult {
	if m != nil {
		return m.StepResults
	}
	return nil
}

type StepResult struct {
	StepId               string            `protobuf:"bytes,1,opt,name=stepId,proto3" json:"stepId,omitempty"`
	Duration             int64             `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Status               string            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message              string            `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Inputs               map[string]string `protobuf:"bytes,5,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Outputs              map[string]string `protobuf:"bytes,6,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *StepResult) Reset()         { *m = StepResult{} }
func (m *StepResult) String() string { return proto.CompactTextString(m) }
func (*StepResult) ProtoMessage()    {}
func (*StepResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{36}
}
func (m *StepResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepResult.Unmarshal(m, b)
}
func (m *StepResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepResult.Marshal(b, m, deterministic)
}
func (dst *StepResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepResult.Merge(dst, src)
}
func (m *StepResult) XXX_Size() int {
	return xxx_messageInfo_StepResult.Size(m)
}
func (m *StepResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StepResult.DiscardUnknown(m)
}

var xxx_messageInfo_StepResult proto.InternalMessageInfo

func (m *StepResult) GetStepId() string {
	if m != nil {
		return m.StepId
	}
	return ""
}

func (m *StepResult) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *StepResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StepResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *StepResult) GetInputs() map[string]string {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *StepResult) GetOutputs() map[string]string {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type TriggerResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Project              string   `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	JobId                string   `protobuf:"bytes,4,opt,name=jobId,proto3" json:"jobId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *TriggerResponse) Reset()         { *m = TriggerResponse{} }
func (m *TriggerResponse) String() string { return proto.CompactTextString(m) }
func (*TriggerResponse) ProtoMessage()    {}
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{37}
}
func (m *TriggerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerResponse.Unmarshal(m, b)
}
func (m *TriggerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerResponse.Marshal(b, m, deterministic)
}
func (dst *TriggerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerResponse.Merge(dst, src)
}
func (m *TriggerResponse) XXX_Size() int {
	return xxx_messageInfo_TriggerResponse.Size(m)
}
func (m *TriggerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerResponse proto.InternalMessageInfo

func (m *TriggerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TriggerResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TriggerResponse) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *TriggerResponse) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type CancelJobRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workflow             string   `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	JobId                string   `protobuf:"bytes,3,opt,name=jobId,proto3" json:"jobId,omitempty"`
	AllPending           bool     `protobuf:"varint,4,opt,name=allPending,proto3" json:"allPending,omitempty"`
	AllRunning           bool     `protobuf:"varint,5,opt,name=allRunning,proto3" json:"allRunning,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *CancelJobRequest) Reset()         { *m = CancelJobRequest{} }
func (m *CancelJobRequest) String() string { return proto.CompactTextString(m) }
func (*CancelJobRequest) ProtoMessage()    {}
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{38}
}
func (m *CancelJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelJobRequest.Unmarshal(m, b)
}
func (m *CancelJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelJobRequest.Marshal(b, m, deterministic)
}
func (dst *CancelJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelJobRequest.Merge(dst, src)
}
func (m *CancelJobRequest) XXX_Size() int {
	return xxx_messageInfo_CancelJobRequest.Size(m)
}
func (m *CancelJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelJobRequest proto.InternalMessageInfo

func (m *CancelJobRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *CancelJobRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func (m *CancelJobRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *CancelJobRequest) GetAllPending() bool {
	if m != nil {
		return m.AllPending
	}
	return false
}

func (m *CancelJobRequest) GetAllRunning() bool {
	if m != nil {
		return m.AllRunning
	}
	return false
}

type CancelJobResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CanceledCount        int64    `protobuf:"varint,3,opt,name=canceledCount,proto3" json:"canceledCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-" xml:"-" bson:"-"`
}

func (m *CancelJobResponse) Reset()         { *m = CancelJobResponse{} }
func (m *CancelJobResponse) String() string { return proto.CompactTextString(m) }
func (*CancelJobResponse) ProtoMessage()    {}
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_api_940b2dd08f4dd567, []int{39}
}
func (m *CancelJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelJobResponse.Unmarshal(m, b)
}
func (m *CancelJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelJobResponse.Marshal(b, m, deterministic)
}
func (dst *CancelJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelJobResponse.Merge(dst, src)
}
func (m *CancelJobResponse) XXX_Size() int {
	return xxx_messageInfo_CancelJobResponse.Size(m)
}
func (m *CancelJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelJobResponse proto.InternalMessageInfo

func (m *CancelJobResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CancelJobResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CancelJobResponse) GetCanceledCount() int64 {
	if m != nil {
		return m.CanceledCount
	}
	return 0
}

func init() {
	proto.RegisterType((*ProjectWorkflowRequest)(nil), "core.ProjectWorkflowRequest")
	proto.RegisterType((*StoreValueRequest)(nil), "core.StoreValueRequest")
	proto.RegisterType((*DeleteValueRequest)(nil), "core.DeleteValueRequest")
	proto.RegisterType((*SingleValueResponse)(nil), "core.SingleValueResponse")
	proto.RegisterType((*ValueResponse)(nil), "core.ValueResponse")
	proto.RegisterMapType((map[string]string)(nil), "core.ValueResponse.ValuesEntry")
	proto.RegisterType((*ProjectValue)(nil), "core.ProjectValue")
	proto.RegisterType((*WorkflowHistoryRequest)(nil), "core.WorkflowHistoryRequest")
	proto.RegisterType((*WorkflowHistoryResponse)(nil), "core.WorkflowHistoryResponse")
	proto.RegisterType((*WorkflowHistory)(nil), "core.WorkflowHistory")
	proto.RegisterType((*RemoteEngineUpdateRequest)(nil), "core.RemoteEngineUpdateRequest")
	proto.RegisterType((*RemoteEngineUpdateResponse)(nil), "core.RemoteEngineUpdateResponse")
	proto.RegisterType((*RemoteEngineHealthRequest)(nil), "core.RemoteEngineHealthRequest")
	proto.RegisterType((*RemoteEngineHealthResponse)(nil), "core.RemoteEngineHealthResponse")
	proto.RegisterType((*ListRemoteEnginesResponse)(nil), "core.ListRemoteEnginesResponse")
	proto.RegisterType((*RemoteEngine)(nil), "core.RemoteEngine")
	proto.RegisterType((*RemoteEngineRequest)(nil), "core.RemoteEngineRequest")
	proto.RegisterType((*RegisterRemoteEngineRequest)(nil), "core.RegisterRemoteEngineRequest")
	proto.RegisterType((*ProjectValueRequest)(nil), "core.ProjectValueRequest")
	proto.RegisterType((*ProjectValuesRequest)(nil), "core.ProjectValuesRequest")
	proto.RegisterType((*ListWorkflowResponse)(nil), "core.ListWorkflowResponse")
	proto.RegisterType((*WorkflowOverview)(nil), "core.WorkflowOverview")
	proto.RegisterType((*RunWorkflowRequest)(nil), "core.RunWorkflowRequest")
	proto.RegisterType((*RetryWorkflowRequest)(nil), "core.RetryWorkflowRequest")
	proto.RegisterType((*RetryWorkflowResponse)(nil), "core.RetryWorkflowResponse")
	proto.RegisterType((*RetryJobRequest)(nil), "core.RetryJobRequest")
	proto.RegisterType((*PublishWorkflowRequest)(nil), "core.PublishWorkflowRequest")
	proto.RegisterType((*AddUserRequest)(nil), "core.AddUserRequest")
	proto.RegisterType((*QueueItem)(nil), "core.QueueItem")
	proto.RegisterMapType((map[string]string)(nil), "core.QueueItem.RunContextEntry")
	proto.RegisterType((*QueueResponse)(nil), "core.QueueResponse")
	proto.RegisterType((*ViewQueueRequest)(nil), "core.ViewQueueRequest")
	proto.RegisterType((*ViewLogRequest)(nil), "core.ViewLogRequest")
	proto.RegisterType((*Log)(nil), "core.Log")
	proto.RegisterType((*ViewLogResponse)(nil), "core.ViewLogResponse")
	proto.RegisterType((*ViewJobDetailRequest)(nil), "core.ViewJobDetailRequest")
	proto.RegisterType((*ViewJobDetailResponse)(nil), "core.ViewJobDetailResponse")
	proto.RegisterType((*JobDetail)(nil), "core.JobDetail")
	proto.RegisterMapType((map[string]string)(nil), "core.JobDetail.StorageEntry")
	proto.RegisterType((*StepResult)(nil), "core.StepResult")
	proto.RegisterMapType((map[string]string)(nil), "core.StepResult.InputsEntry")
	proto.RegisterMapType((map[string]string)(nil), "core.StepResult.OutputsEntry")
	proto.RegisterType((*TriggerResponse)(nil), "core.TriggerResponse")
	proto.RegisterType((*CancelJobRequest)(nil), "core.CancelJobRequest")
	proto.RegisterType((*CancelJobResponse)(nil), "core.CancelJobResponse")
}

func init() { proto.RegisterFile("workflow_api.proto", fileDescriptor_workflow_api_940b2dd08f4dd567) }

var fileDescriptor_workflow_api_940b2dd08f4dd567 = []byte{
	// 2033 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0xeb, 0x6f, 0x1c, 0x49,
	0x11, 0xd7, 0x3e, 0xfc, 0xd8, 0xda, 0xf5, 0x23, 0x13, 0xc7, 0xd9, 0xec, 0xe5, 0x61, 0x46, 0x07,
	0x8a, 0x74, 0x9c, 0x0d, 0xe1, 0x74, 0x97, 0x8b, 0x08, 0xc4, 0xb1, 0x7d, 0x89, 0x8d, 0xb9, 0xf8,
	0xc6, 0x49, 0x4e, 0xa0, 0x43, 0x68, 0x76, 0xa6, 0xbc, 0x1e, 0x7b, 0x77, 0x7a, 0xae, 0xbb, 0xc7,
	0x66, 0x11, 0x1f, 0x90, 0xf8, 0x80, 0x84, 0xf8, 0x04, 0x1f, 0x10, 0x42, 0xe2, 0x9f, 0xe0, 0x9f,
	0xe1, 0xcf, 0x41, 0xfd, 0x9a, 0xe9, 0x99, 0x9d, 0x3d, 0xdb, 0x71, 0xf8, 0x36, 0x55, 0x5d, 0xfd,
	0xab, 0x47, 0x57, 0x57, 0x57, 0xf7, 0x80, 0x73, 0x4e, 0xe8, 0xe9, 0xd1, 0x90, 0x9c, 0xff, 0xd6,
	0x4f, 0xa2, 0xf5, 0x84, 0x12, 0x4e, 0x9c, 0x66, 0x40, 0x28, 0xf6, 0x3a, 0x01, 0x19, 0x8d, 0x48,
	0xac, 0x78, 0xee, 0x97, 0xb0, 0x7a, 0x40, 0xc9, 0x09, 0x06, 0xfc, 0x6b, 0x3d, 0xc1, 0xc3, 0x6f,
	0x53, 0x64, 0xdc, 0xe9, 0xc2, 0x5c, 0xa2, 0x46, 0xba, 0xb5, 0xb5, 0xda, 0xc3, 0x96, 0x67, 0x48,
	0xa7, 0x07, 0xf3, 0x06, 0xbd, 0x5b, 0x97, 0x43, 0x19, 0xed, 0x7e, 0x0b, 0x37, 0x0e, 0x39, 0xa1,
	0xf8, 0xd6, 0x1f, 0xa6, 0x68, 0xa0, 0x96, 0xa1, 0x71, 0x8a, 0x63, 0x0d, 0x23, 0x3e, 0x9d, 0x15,
	0x98, 0x39, 0x13, 0x12, 0x7a, 0xbe, 0x22, 0x6c, 0x95, 0x8d, 0x09, 0x95, 0x11, 0x3b, 0xc4, 0x80,
	0x22, 0xef, 0x36, 0xd7, 0x6a, 0x0f, 0xe7, 0xbd, 0x8c, 0x76, 0x9f, 0x81, 0xb3, 0x8d, 0x43, 0xe4,
	0x17, 0xe9, 0xb4, 0xd0, 0xeb, 0x05, 0x74, 0xf7, 0x23, 0xb8, 0x79, 0x18, 0xc5, 0x83, 0xa1, 0x41,
	0x60, 0x09, 0x89, 0x19, 0xe6, 0x46, 0xd6, 0x2c, 0x23, 0xdd, 0x3f, 0xd5, 0x60, 0xa1, 0x28, 0xf7,
	0x19, 0xcc, 0xca, 0x21, 0xd6, 0xad, 0xad, 0x35, 0x1e, 0xb6, 0x1f, 0x3d, 0x58, 0x17, 0x81, 0x5e,
	0x2f, 0x08, 0x29, 0x8a, 0xed, 0xc4, 0x9c, 0x8e, 0x3d, 0x2d, 0xde, 0xfb, 0x1c, 0xda, 0x16, 0xfb,
	0xb2, 0x61, 0x7a, 0x52, 0x7f, 0x5c, 0x73, 0x29, 0x74, 0xf4, 0xba, 0x49, 0x84, 0xf7, 0x10, 0xe2,
	0x35, 0x68, 0x47, 0x6c, 0x27, 0x0e, 0xe8, 0x38, 0xe1, 0x18, 0xea, 0x28, 0xdb, 0x2c, 0xf7, 0x6f,
	0x35, 0x58, 0x35, 0x59, 0xf2, 0x32, 0x62, 0x9c, 0xd0, 0xf1, 0xb5, 0x92, 0xc5, 0x59, 0x85, 0x59,
	0x72, 0x74, 0xc4, 0x50, 0xd9, 0xd2, 0xf0, 0x34, 0x25, 0x4c, 0x0f, 0x48, 0x1a, 0xab, 0xa5, 0x6e,
	0x78, 0x8a, 0x10, 0xdc, 0x13, 0xd2, 0xdf, 0x0d, 0xbb, 0x33, 0xca, 0x21, 0x49, 0xb8, 0x5f, 0xc0,
	0xed, 0x09, 0x9b, 0xf4, 0xba, 0x7c, 0x04, 0x33, 0x11, 0xc7, 0x91, 0x59, 0x96, 0x5b, 0x6a, 0x59,
	0xca, 0xd2, 0x4a, 0xc6, 0xfd, 0x4f, 0x1d, 0x96, 0x4a, 0x43, 0xce, 0x22, 0xd4, 0xa3, 0x50, 0x3b,
	0x54, 0x8f, 0x42, 0xe1, 0x25, 0x4b, 0x83, 0x00, 0x19, 0x93, 0xae, 0xcc, 0x7b, 0x86, 0x14, 0xb6,
	0x31, 0xee, 0x53, 0xe3, 0x88, 0x22, 0xc4, 0xa2, 0x60, 0x1c, 0x6a, 0x2f, 0xc4, 0xa7, 0x88, 0x46,
	0x98, 0x52, 0x9f, 0x47, 0x24, 0x96, 0x6e, 0xd4, 0xbc, 0x8c, 0x76, 0x3e, 0x84, 0x85, 0x23, 0x3f,
	0x1a, 0xa6, 0x14, 0x3d, 0xf4, 0x19, 0x89, 0xbb, 0xb3, 0x52, 0x71, 0x91, 0x69, 0x47, 0x7a, 0x6e,
	0x7a, 0xa4, 0xe7, 0x4b, 0x91, 0x5e, 0x83, 0x36, 0xa7, 0xd1, 0x60, 0x80, 0xf4, 0xf5, 0x38, 0xc1,
	0x6e, 0x4b, 0x0e, 0xdb, 0x2c, 0xe7, 0x3e, 0x40, 0xe2, 0x53, 0x8c, 0xf9, 0x2e, 0xc7, 0x51, 0x17,
	0xa4, 0x80, 0xc5, 0x11, 0x1e, 0x46, 0x71, 0x92, 0xf2, 0x6e, 0x5b, 0x45, 0x5f, 0x12, 0xee, 0xdf,
	0x6b, 0x70, 0xc7, 0xc3, 0x11, 0xe1, 0xb8, 0x13, 0x0f, 0xa2, 0x18, 0xdf, 0x24, 0xa1, 0xcf, 0xb3,
	0x3d, 0xe8, 0x40, 0x33, 0xf6, 0x47, 0x66, 0xff, 0xc8, 0xef, 0xe9, 0xbb, 0x50, 0xd8, 0x78, 0x44,
	0x68, 0xa0, 0x31, 0x64, 0x24, 0xe7, 0x3d, 0x9b, 0xe5, 0xfc, 0x00, 0x16, 0xcf, 0xfd, 0x88, 0x7f,
	0x41, 0xe8, 0x5b, 0xa4, 0x4c, 0xc4, 0x50, 0x65, 0x69, 0x89, 0xeb, 0x52, 0xe8, 0x55, 0x19, 0xa5,
	0xd3, 0x62, 0x15, 0x66, 0x19, 0xf7, 0x79, 0xca, 0xb4, 0x5d, 0x9a, 0x12, 0x96, 0x9d, 0x69, 0x58,
	0x6d, 0x99, 0x26, 0x45, 0x1e, 0x10, 0xa6, 0xf7, 0x4b, 0x9d, 0x30, 0xe1, 0x97, 0x4f, 0x83, 0x63,
	0xa9, 0xbd, 0xe5, 0xc9, 0x6f, 0x77, 0xb7, 0x18, 0x88, 0x97, 0xe8, 0x0f, 0xf9, 0xf1, 0x3b, 0x05,
	0xa2, 0x6c, 0xbe, 0x81, 0xfa, 0x7f, 0x9b, 0xbf, 0x1f, 0x31, 0x6e, 0xeb, 0x65, 0x99, 0xca, 0x1f,
	0xc2, 0x1c, 0x2a, 0x96, 0xde, 0x4a, 0x8e, 0xda, 0x4a, 0xb6, 0xb4, 0x67, 0x44, 0xdc, 0x3e, 0x74,
	0xec, 0x81, 0x4a, 0xe7, 0x1d, 0x68, 0x1e, 0x13, 0x66, 0x3c, 0x97, 0xdf, 0xc2, 0x31, 0x3f, 0x89,
	0x7e, 0x81, 0x63, 0x6d, 0xaa, 0xa6, 0x84, 0x6c, 0x80, 0x54, 0x15, 0x83, 0x8e, 0x27, 0xbf, 0xdd,
	0x17, 0x70, 0xb3, 0xa0, 0xfc, 0xc2, 0x32, 0xb4, 0x0a, 0xb3, 0xca, 0x3e, 0xad, 0x52, 0x53, 0xee,
	0x3f, 0x6a, 0xf0, 0x81, 0x87, 0x83, 0x88, 0x71, 0xa4, 0x55, 0x88, 0x97, 0x35, 0xfe, 0x3e, 0x40,
	0x30, 0x8c, 0x30, 0xe6, 0x5b, 0xa8, 0xab, 0x40, 0xc7, 0xb3, 0x38, 0x96, 0x73, 0xcd, 0x82, 0x73,
	0x96, 0xc5, 0x33, 0xc5, 0x2c, 0xd8, 0x84, 0x9b, 0x76, 0x85, 0xbf, 0xd8, 0x45, 0x7d, 0x04, 0xd4,
	0xb3, 0x23, 0xc0, 0xdd, 0x83, 0x15, 0x1b, 0x82, 0x5d, 0x8c, 0xd1, 0x85, 0xb9, 0x10, 0x65, 0xbd,
	0x37, 0x15, 0x4e, 0x93, 0xee, 0x3e, 0xac, 0x88, 0x04, 0xc9, 0xbb, 0x04, 0x9d, 0x1b, 0x9f, 0x40,
	0xcb, 0x54, 0x19, 0x93, 0x1d, 0xab, 0xc5, 0x42, 0xfb, 0xea, 0x0c, 0xe9, 0x59, 0x84, 0xe7, 0x5e,
	0x2e, 0xe8, 0xfe, 0x01, 0x96, 0xcb, 0xc3, 0x55, 0xd5, 0x76, 0x4a, 0xa5, 0x70, 0xa1, 0x13, 0x62,
	0x82, 0x71, 0x88, 0x71, 0x10, 0xa1, 0x49, 0xed, 0x02, 0x4f, 0x54, 0x43, 0x5d, 0xde, 0x98, 0x0e,
	0x79, 0x46, 0xbb, 0x7f, 0xa9, 0x81, 0xe3, 0xa5, 0x71, 0xb9, 0xe3, 0xb9, 0x0b, 0x2d, 0xad, 0x61,
	0xd7, 0xd8, 0x91, 0x33, 0xc4, 0x0a, 0x1b, 0xfb, 0x77, 0x43, 0x6d, 0x91, 0xc5, 0xb1, 0x4a, 0xec,
	0x73, 0x12, 0x8e, 0x75, 0x0a, 0xd8, 0xac, 0xea, 0x63, 0xcd, 0xfd, 0x63, 0x0d, 0x56, 0x3c, 0xe4,
	0x74, 0xfc, 0x5e, 0x1a, 0x30, 0x31, 0x76, 0x44, 0xc9, 0x68, 0xdb, 0x94, 0xd0, 0x86, 0x97, 0xd1,
	0x22, 0x09, 0x39, 0x91, 0x23, 0xca, 0x02, 0x4d, 0xb9, 0xbf, 0x81, 0x5b, 0x25, 0x0b, 0xf2, 0x0e,
	0x48, 0x59, 0x5c, 0xb3, 0x0f, 0xe2, 0x55, 0x98, 0x95, 0x67, 0xaf, 0x38, 0x05, 0x1b, 0x22, 0x97,
	0x15, 0x25, 0xf7, 0x18, 0xa5, 0x84, 0x8a, 0x05, 0x91, 0x7c, 0x45, 0xb9, 0x9b, 0xb0, 0x24, 0xe1,
	0xf7, 0x48, 0xff, 0x62, 0xdf, 0xb2, 0x53, 0xbe, 0x6e, 0x9f, 0xf2, 0x7b, 0xb0, 0x7a, 0x90, 0xf6,
	0x87, 0x11, 0x3b, 0xbe, 0xda, 0xa2, 0x39, 0xd0, 0x0c, 0x7d, 0xee, 0x4b, 0xb0, 0x8e, 0x27, 0xbf,
	0xdd, 0x3d, 0x58, 0xdc, 0x0c, 0xc3, 0x37, 0x4c, 0x6c, 0x78, 0x85, 0xd1, 0x83, 0xf9, 0x94, 0x21,
	0xb5, 0x36, 0x7a, 0x46, 0x17, 0xf1, 0xeb, 0x25, 0x7c, 0xf7, 0x5f, 0x75, 0x68, 0x7d, 0x95, 0x62,
	0x8a, 0xf2, 0x8c, 0x7c, 0xb7, 0x15, 0xfb, 0x39, 0x00, 0x4d, 0xe3, 0x2d, 0x12, 0x73, 0xfc, 0x1d,
	0x97, 0xa1, 0xcb, 0x5a, 0xc8, 0x0c, 0x7a, 0xdd, 0xcb, 0x24, 0x54, 0x0b, 0x69, 0x4d, 0x11, 0x6a,
	0x69, 0x1a, 0xc7, 0x51, 0x3c, 0xd0, 0xe7, 0xa1, 0x21, 0x85, 0xf1, 0x01, 0x45, 0x9f, 0x63, 0xf8,
	0x2a, 0xd6, 0xf5, 0x25, 0x67, 0x58, 0x19, 0x8b, 0xe1, 0xf3, 0xb1, 0x6e, 0x37, 0x6c, 0x56, 0xef,
	0x29, 0x2c, 0x95, 0x14, 0x5f, 0xa9, 0x49, 0xfd, 0x6b, 0x0d, 0x16, 0xa4, 0x0b, 0x59, 0x42, 0x59,
	0x1d, 0x54, 0xad, 0xd8, 0x41, 0x75, 0x61, 0x6e, 0x84, 0x8c, 0xf9, 0x03, 0x83, 0x63, 0x48, 0x61,
	0x26, 0xc5, 0x80, 0xd0, 0x70, 0x4b, 0xa6, 0xa2, 0x4a, 0x6a, 0x9b, 0xe5, 0x7c, 0xdf, 0x34, 0x7a,
	0x4d, 0x19, 0xbc, 0xa5, 0x52, 0xf0, 0x4c, 0x8b, 0x77, 0x02, 0xcb, 0x6f, 0x23, 0x3c, 0xd7, 0x16,
	0x5d, 0x67, 0x93, 0x95, 0xda, 0xa9, 0xc6, 0x44, 0x3b, 0xe5, 0x7e, 0x03, 0x8b, 0x42, 0xd7, 0x3e,
	0x19, 0xbc, 0x63, 0xca, 0x0b, 0xfd, 0x43, 0x32, 0xd8, 0xc7, 0x33, 0x1c, 0x6a, 0x05, 0x19, 0xed,
	0xfe, 0x0a, 0x1a, 0xfb, 0x64, 0x50, 0x10, 0xa9, 0x15, 0x45, 0xbe, 0x23, 0x9e, 0x77, 0xa1, 0xc5,
	0xa3, 0x11, 0x32, 0xee, 0x8f, 0x12, 0x8d, 0x9c, 0x33, 0xdc, 0x10, 0x96, 0x32, 0xc3, 0xaf, 0xb1,
	0x68, 0xf7, 0xa0, 0x39, 0x24, 0x03, 0xa6, 0xd3, 0xb9, 0xa5, 0x56, 0x44, 0x80, 0x4a, 0xb6, 0xfb,
	0x1c, 0x56, 0x84, 0x96, 0x3d, 0xd2, 0xdf, 0x46, 0xee, 0x47, 0xc3, 0x4b, 0x9d, 0x6e, 0x27, 0xa4,
	0x6f, 0x4e, 0xb7, 0x13, 0xd2, 0x77, 0x7f, 0x0f, 0xb7, 0x4a, 0x18, 0xd7, 0xb0, 0xf7, 0x63, 0x68,
	0x9d, 0x18, 0x20, 0x19, 0x94, 0x2c, 0x8d, 0x72, 0xfc, 0x5c, 0xc2, 0xfd, 0x73, 0x1d, 0x5a, 0xd9,
	0x80, 0x88, 0xa8, 0x6c, 0xf8, 0x5f, 0x47, 0x59, 0x01, 0xc9, 0x19, 0x42, 0x29, 0xc6, 0xa1, 0x1c,
	0xd3, 0x4a, 0x35, 0x59, 0xb8, 0x0d, 0x34, 0x4a, 0xb7, 0x81, 0x4f, 0x61, 0x4e, 0x5c, 0x42, 0x84,
	0xa9, 0x2a, 0xab, 0xef, 0x96, 0xcc, 0x59, 0x3f, 0x54, 0xc3, 0xaa, 0x1e, 0x18, 0x61, 0xe7, 0x11,
	0xb4, 0x19, 0xc7, 0xc4, 0x43, 0x96, 0x0e, 0x39, 0xeb, 0xce, 0xc8, 0xb9, 0xcb, 0x6a, 0xee, 0x61,
	0x36, 0xe0, 0xd9, 0x42, 0xbd, 0x27, 0xd0, 0xb1, 0xc1, 0xae, 0xb4, 0xc7, 0xff, 0x5b, 0x07, 0xc8,
	0x71, 0x55, 0x77, 0x8a, 0x49, 0x56, 0x8b, 0x35, 0x55, 0x70, 0xb5, 0xae, 0x8e, 0xa5, 0xcc, 0xd5,
	0xbc, 0xa3, 0x6d, 0x94, 0x3b, 0x5a, 0xb3, 0x5a, 0xcd, 0xe2, 0x6a, 0x7d, 0x02, 0xb3, 0xf2, 0xfe,
	0x61, 0xfc, 0xbb, 0x5b, 0xf6, 0x6f, 0x7d, 0x57, 0x0e, 0xeb, 0xeb, 0xb6, 0x92, 0x75, 0x3e, 0x83,
	0x39, 0x92, 0x72, 0x39, 0x6d, 0x56, 0x4e, 0xbb, 0x37, 0x31, 0xed, 0x95, 0x1a, 0xd7, 0x31, 0xd5,
	0xd2, 0xe2, 0x9e, 0x6e, 0xe1, 0x5d, 0x25, 0x3c, 0x22, 0xb4, 0x36, 0xe6, 0x95, 0x42, 0x9b, 0xc2,
	0xd2, 0x6b, 0x55, 0x52, 0xae, 0x95, 0xda, 0xd3, 0xaf, 0xfc, 0x59, 0xe1, 0x69, 0xda, 0x67, 0xed,
	0xbf, 0x6b, 0xb0, 0xbc, 0xe5, 0xc7, 0x01, 0x0e, 0x2f, 0x75, 0x60, 0x7f, 0x57, 0x9d, 0xcc, 0x14,
	0x34, 0xec, 0xca, 0x76, 0x1f, 0xc0, 0x1f, 0x0e, 0x0f, 0x30, 0x0e, 0xf3, 0x23, 0xcb, 0xe2, 0xe8,
	0x71, 0x4f, 0x1f, 0x69, 0x33, 0xd9, 0xb8, 0xe6, 0xb8, 0x23, 0xb8, 0x61, 0xd9, 0x77, 0x8d, 0xc8,
	0x7c, 0x08, 0x0b, 0x81, 0x04, 0xc2, 0xc2, 0xd9, 0x52, 0x64, 0x3e, 0xfa, 0xe7, 0x32, 0xb4, 0x4d,
	0xd7, 0xb1, 0x79, 0xb0, 0xeb, 0xfc, 0x0c, 0xda, 0x56, 0xf3, 0xe8, 0x74, 0xf5, 0x5d, 0x68, 0xa2,
	0x9f, 0xec, 0xe9, 0x07, 0x87, 0xf2, 0x1a, 0xbe, 0x84, 0x85, 0x42, 0xb7, 0xe5, 0xf4, 0xcc, 0x6d,
	0x6a, 0xb2, 0x09, 0xec, 0x7d, 0x50, 0x39, 0xa6, 0x91, 0x1e, 0xc3, 0xbc, 0x69, 0xac, 0x9c, 0x5b,
	0x96, 0x60, 0xbe, 0x6e, 0xd3, 0x6c, 0xd8, 0x80, 0xe6, 0x81, 0x08, 0xb5, 0xbe, 0xc8, 0xed, 0x8c,
	0x12, 0x3e, 0xfe, 0xa5, 0x8a, 0x4a, 0xef, 0xa6, 0xe2, 0x3d, 0xf7, 0x59, 0x14, 0x64, 0x13, 0xb6,
	0x61, 0xa9, 0xd4, 0x80, 0x39, 0x7a, 0xd3, 0x55, 0xf7, 0x65, 0xd5, 0x28, 0x9b, 0xb0, 0x60, 0x5f,
	0x22, 0x98, 0xb3, 0xa2, 0x31, 0x54, 0x2e, 0x99, 0xb9, 0x3a, 0x20, 0x95, 0xf7, 0x8d, 0x27, 0xb0,
	0xb0, 0x25, 0x3b, 0x98, 0x03, 0x93, 0xc4, 0x95, 0x10, 0x95, 0xea, 0x9f, 0xc2, 0xb2, 0xee, 0xfc,
	0x5e, 0x93, 0xd2, 0xf4, 0x62, 0x47, 0x58, 0x3d, 0xfd, 0x53, 0xe8, 0x6c, 0x86, 0xe1, 0x61, 0x9a,
	0x20, 0x15, 0xb2, 0xce, 0x0d, 0x25, 0x74, 0x99, 0x79, 0xc2, 0x15, 0xad, 0x91, 0x39, 0x6d, 0x2b,
	0xe8, 0xbd, 0x3b, 0xb9, 0xaf, 0x99, 0x0b, 0x7a, 0xde, 0x1e, 0xdc, 0x98, 0xb8, 0x93, 0x4f, 0x71,
	0xf7, 0x41, 0x8e, 0x52, 0x7d, 0x85, 0xff, 0x52, 0x5c, 0x32, 0x26, 0xaf, 0xb9, 0xce, 0xf7, 0x4c,
	0xda, 0x4c, 0xbd, 0x02, 0x57, 0xfb, 0xf4, 0x0c, 0x96, 0x5e, 0x60, 0x41, 0x97, 0x73, 0xa7, 0xe2,
	0x51, 0x40, 0x43, 0x54, 0xbc, 0x17, 0x38, 0xdf, 0xc0, 0xed, 0xc9, 0x57, 0x8e, 0xad, 0x63, 0x0c,
	0x4e, 0x9d, 0x07, 0x93, 0xe2, 0x85, 0xf7, 0x94, 0xde, 0xda, 0x74, 0x01, 0x6d, 0xdf, 0xd7, 0xe0,
	0x98, 0x67, 0x1f, 0x4b, 0x67, 0x05, 0x70, 0xe1, 0xc5, 0xaa, 0x0a, 0xb8, 0xf4, 0x7a, 0xb4, 0x0d,
	0x8e, 0x18, 0x3d, 0xc3, 0xcb, 0xfa, 0x5e, 0x19, 0xbe, 0x1d, 0x58, 0x7c, 0x81, 0x5c, 0x1c, 0x3c,
	0x07, 0x7e, 0x70, 0x2a, 0xab, 0x74, 0x7e, 0x16, 0x69, 0x96, 0x01, 0xb8, 0x53, 0x31, 0xa2, 0x61,
	0x3e, 0x07, 0xd0, 0x2d, 0x90, 0x68, 0x07, 0x75, 0x6a, 0x14, 0xfb, 0x4e, 0x53, 0x01, 0xca, 0x4d,
	0xdd, 0x4b, 0x58, 0x28, 0x74, 0x4f, 0xa6, 0x0a, 0x55, 0xb5, 0x65, 0xa6, 0x0a, 0x55, 0xb7, 0x5b,
	0x5f, 0x81, 0xf3, 0x02, 0x79, 0xf9, 0xed, 0xf4, 0x6e, 0xf5, 0x6b, 0xab, 0x06, 0xbc, 0x37, 0x65,
	0x34, 0xdb, 0xe4, 0x90, 0xff, 0x45, 0x70, 0x6e, 0x9b, 0x00, 0x94, 0xfe, 0x2b, 0x54, 0x87, 0xf6,
	0xa7, 0xd0, 0xb6, 0x7e, 0x07, 0x98, 0xb8, 0x4e, 0xfe, 0x21, 0x98, 0x36, 0xbb, 0xf5, 0x02, 0xf5,
	0x73, 0x89, 0x09, 0x49, 0xd5, 0x1b, 0x8a, 0x99, 0x5d, 0xfc, 0x13, 0xf0, 0x0c, 0xe6, 0xcd, 0x6c,
	0x93, 0x12, 0x15, 0x6f, 0x38, 0xd9, 0x8a, 0x56, 0xfc, 0x73, 0x78, 0x0c, 0xad, 0xec, 0x8e, 0xe2,
	0xac, 0xe6, 0x61, 0xb7, 0x2f, 0x2d, 0x46, 0x77, 0xf1, 0x6a, 0xf5, 0x14, 0x20, 0x3b, 0x15, 0x99,
	0x99, 0x5a, 0x3e, 0xc7, 0x7b, 0xb7, 0x27, 0xf8, 0x79, 0x81, 0xdf, 0x8e, 0x98, 0xdf, 0x1f, 0xe2,
	0x44, 0x81, 0xaf, 0xfc, 0x3f, 0x54, 0x1d, 0xbe, 0x2d, 0x58, 0xdc, 0x89, 0xdf, 0x03, 0x88, 0xda,
	0x62, 0xd7, 0x01, 0xf9, 0x11, 0x74, 0x0e, 0xfc, 0x94, 0x65, 0x75, 0xb3, 0x50, 0x74, 0x2b, 0x67,
	0x3c, 0x82, 0xc5, 0x37, 0x71, 0x72, 0xa5, 0x39, 0xcf, 0x7f, 0xfc, 0xeb, 0x8d, 0x41, 0xc4, 0x8f,
	0xd3, 0xfe, 0x7a, 0x40, 0x46, 0x1b, 0x7e, 0x92, 0x70, 0x8a, 0xc8, 0xc8, 0x11, 0x3f, 0xf7, 0x29,
	0x6e, 0x0c, 0xc8, 0xc7, 0xa6, 0x15, 0xda, 0x48, 0x4e, 0x07, 0x1b, 0x02, 0xa0, 0x3f, 0x2b, 0x7f,
	0xbc, 0xfd, 0xe4, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x1f, 0xa1, 0xde, 0xa2, 0x1b, 0x00,
	0x00,
}
